# apps/authentication/models/biometric_credential.py
"""
BiometricCredential Model — FIDO2/WebAuthn Passwordless Auth
=============================================================

Stores WebAuthn/FIDO2 credentials for biometric (fingerprint, Face ID)
and hardware key authentication.

Import:
    from apps.authentication.models import BiometricCredential
"""

from apps.common.models import TimeStampedModel
from django.db import models


class BiometricCredential(TimeStampedModel):
    """
    Stores FIDO2/WebAuthn credentials for Passwordless/Biometric Auth.

    One credential per device/authenticator. A user can register multiple
    credentials (e.g., laptop fingerprint AND iPhone Face ID).
    """
    user = models.ForeignKey(
        "authentication.UnifiedUser",
        on_delete=models.CASCADE,
        related_name='biometric_credentials',
        help_text="The user this credential belongs to.",
    )
    credential_id = models.BinaryField(
        unique=True,
        help_text="The Credential ID generated by the authenticator.",
    )
    public_key = models.BinaryField(
        help_text="The Public Key for signature verification.",
    )
    sign_count = models.IntegerField(
        default=0,
        help_text="Counter to prevent replay attacks.",
    )
    device_name = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text="User-friendly name (e.g., 'MacBook TouchID').",
    )

    class Meta:
        verbose_name = "Biometric Credential"
        verbose_name_plural = "Biometric Credentials"

    def __str__(self):
        return f"{self.user} - {self.device_name or 'Key'}"
