# apps/scheduler/apis/async_/scheduler_views.py
"""
Django-Ninja async views for the scheduler app (reads/GETs).
"""

from typing import List, Dict, Any, Optional
from uuid import UUID
from datetime import datetime
from ninja import Router, Schema
from asgiref.sync import sync_to_async

from ...selectors import (
    get_task_definitions_queryset,
    get_scheduled_tasks_queryset,
    get_task_executions_queryset,
    get_task_logs_queryset,
    get_task_alerts_queryset,
    get_scheduler_statistics_overview,
    get_scheduler_performance_stats
)

router = Router(tags=["scheduler"])


# ── Schemas ───────────────────────────────────────────────────────────────────

class TaskDefinitionOut(Schema):
    id: UUID
    name: str
    task_path: str
    task_type: str
    description: str
    default_params: Dict[str, Any]
    queue_name: str
    is_active: bool
    created_at: datetime
    updated_at: datetime


class ScheduledTaskOut(Schema):
    id: UUID
    task_definition_id: UUID
    name: str
    schedule_type: str
    one_off_datetime: Optional[datetime] = None
    interval_seconds: Optional[int] = None
    cron_expression: str
    params: Dict[str, Any]
    status: str
    priority: int
    max_retries: int
    retry_delay: int
    start_datetime: datetime
    end_datetime: Optional[datetime] = None
    last_run_at: Optional[datetime] = None
    next_run_at: Optional[datetime] = None
    total_run_count: int
    success_count: int
    failure_count: int
    created_at: datetime
    updated_at: datetime


class TaskExecutionOut(Schema):
    id: UUID
    scheduled_task_id: Optional[UUID] = None
    task_definition_id: UUID
    celery_task_id: str
    status: str
    params: Dict[str, Any]
    queued_at: datetime
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    result: Optional[Dict[str, Any]] = None
    error_message: str
    retry_count: int
    duration_seconds: Optional[float] = None
    worker_name: str
    queue_name: str


class TaskLogOut(Schema):
    id: UUID
    execution_id: UUID
    level: str
    message: str
    extra_data: Dict[str, Any]
    created_at: datetime


class TaskAlertOut(Schema):
    id: UUID
    task_definition_id: Optional[UUID] = None
    scheduled_task_id: Optional[UUID] = None
    execution_id: Optional[UUID] = None
    alert_type: str
    severity: str
    title: str
    message: str
    details: Dict[str, Any]
    is_resolved: bool
    resolved_at: Optional[datetime] = None
    resolved_by_id: Optional[int] = None
    resolution_note: str
    created_at: datetime


class SchedulerOverviewOut(Schema):
    total_definitions: int
    active_definitions: int
    total_scheduled: int
    active_scheduled: int
    overdue_scheduled: int
    total_executions: int
    running_executions: int
    success_rate: float
    average_duration: float
    unresolved_alerts: int
    critical_alerts: int


class PerformanceItemOut(Schema):
    task_id: str
    task_name: str
    total_executions: int
    success_rate: float
    avg_duration: float
    min_duration: float
    max_duration: float


class PerformanceStatsOut(Schema):
    period_days: int
    performance: List[PerformanceItemOut]


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.get("/definitions/", response=List[TaskDefinitionOut])
async def list_definitions(request):
    """List all task definitions in the system."""
    qs = get_task_definitions_queryset()
    return [item async for item in qs]


@router.get("/schedules/", response=List[ScheduledTaskOut])
async def list_schedules(request, status: Optional[str] = None):
    """List all scheduled task schedules."""
    qs = get_scheduled_tasks_queryset()
    if status:
        qs = qs.filter(status=status)
    return [item async for item in qs]


@router.get("/executions/", response=List[TaskExecutionOut])
async def list_executions(request, status: Optional[str] = None, limit: int = 50):
    """List task run execution history."""
    qs = get_task_executions_queryset().order_by('-queued_at')
    if status:
        qs = qs.filter(status=status)
    qs = qs[:limit]
    return [item async for item in qs]


@router.get("/executions/{execution_id}/logs/", response=List[TaskLogOut])
async def get_execution_logs(request, execution_id: UUID):
    """Retrieve detailed logs for a specific task run execution."""
    qs = get_task_logs_queryset().filter(execution_id=execution_id).order_by('created_at')
    return [item async for item in qs]


@router.get("/alerts/", response=List[TaskAlertOut])
async def list_alerts(request, is_resolved: Optional[bool] = None):
    """List all task alerts generated by scheduler failures."""
    qs = get_task_alerts_queryset()
    if is_resolved is not None:
        qs = qs.filter(is_resolved=is_resolved)
    return [item async for item in qs]


@router.get("/statistics/", response=SchedulerOverviewOut)
async def get_statistics(request):
    """Retrieve aggregate system-wide scheduler overview statistics."""
    stats = await sync_to_async(get_scheduler_statistics_overview)()
    return stats


@router.get("/performance/", response=PerformanceStatsOut)
async def get_performance(request, days: int = 7):
    """Retrieve running duration and execution speed stats for tasks."""
    stats = await sync_to_async(get_scheduler_performance_stats)(days=days)
    return stats
