# Generated by Django 6.0.3 on 2026-06-28 03:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Task Name')),
                ('task_path', models.CharField(help_text='Example: app_name.tasks.function_name', max_length=500, verbose_name='Function Path')),
                ('task_type', models.CharField(choices=[('cleanup', 'Cleanup'), ('report', 'Reporting'), ('notification', 'Notification'), ('backup', 'Backup'), ('sync', 'Synchronization'), ('analytics', 'Analytics'), ('health_check', 'Health Check'), ('custom', 'Custom')], default='custom', max_length=20, verbose_name='Task Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('default_params', models.JSONField(blank=True, default=dict, verbose_name='Default Parameters')),
                ('queue_name', models.CharField(default='default', max_length=100, verbose_name='Queue Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_definitions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Task Definition',
                'verbose_name_plural': 'Task Definitions',
                'ordering': ['task_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Schedule Name')),
                ('schedule_type', models.CharField(choices=[('once', 'Once'), ('interval', 'Interval'), ('cron', 'Cron Expression'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, verbose_name='Schedule Type')),
                ('one_off_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Execution Time')),
                ('interval_seconds', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Interval (seconds)')),
                ('cron_expression', models.CharField(blank=True, help_text='Example: 0 0 * * * (Every day at midnight)', max_length=200, verbose_name='Cron Expression')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('disabled', 'Disabled')], default='active', max_length=20, verbose_name='Status')),
                ('priority', models.IntegerField(default=5, help_text='1=Highest, 10=Lowest', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Priority')),
                ('max_retries', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max Retries')),
                ('retry_delay', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Retry Delay (seconds)')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Next Run')),
                ('total_run_count', models.IntegerField(default=0, verbose_name='Total Run Count')),
                ('success_count', models.IntegerField(default=0, verbose_name='Successful Run Count')),
                ('failure_count', models.IntegerField(default=0, verbose_name='Failed Run Count')),
                ('celery_beat_id', models.IntegerField(blank=True, null=True, verbose_name='Celery Beat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('task_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='scheduler.taskdefinition', verbose_name='Task Definition')),
            ],
            options={
                'verbose_name': 'Scheduled Task',
                'verbose_name_plural': 'Scheduled Tasks',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(max_length=255, unique=True, verbose_name='Celery Task ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Execution Parameters')),
                ('queued_at', models.DateTimeField(auto_now_add=True, verbose_name='Queued Time')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completion Time')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Result')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('traceback', models.TextField(blank=True, verbose_name='Error Details')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('worker_name', models.CharField(blank=True, max_length=200, verbose_name='Worker Name')),
                ('queue_name', models.CharField(blank=True, max_length=100, verbose_name='Queue Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_executions', to=settings.AUTH_USER_MODEL, verbose_name='Executed By')),
                ('scheduled_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scheduler.scheduledtask', verbose_name='Scheduled Task')),
                ('task_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scheduler.taskdefinition', verbose_name='Task Definition')),
            ],
            options={
                'verbose_name': 'Task Execution',
                'verbose_name_plural': 'Task Executions',
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('failure', 'Execution Failure'), ('timeout', 'Timeout'), ('threshold', 'Threshold Breached'), ('missing', 'Missed Run'), ('performance', 'Performance Degradation')], max_length=20, verbose_name='Alert Type')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Severity')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Is Resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved Time')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Resolution Note')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Notification Sent Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('notified_users', models.ManyToManyField(blank=True, related_name='task_alert_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Notified Users')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_task_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
                ('scheduled_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scheduler.scheduledtask', verbose_name='Scheduled Task')),
                ('task_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scheduler.taskdefinition', verbose_name='Task Definition')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scheduler.taskexecution', verbose_name='Execution')),
            ],
            options={
                'verbose_name': 'Task Alert',
                'verbose_name_plural': 'Task Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='LogLevel')),
                ('message', models.TextField(verbose_name='Message')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Logged Time')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scheduler.taskexecution', verbose_name='Execution')),
            ],
            options={
                'verbose_name': 'Task Log',
                'verbose_name_plural': 'Task Logs',
                'ordering': ['execution', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['status', 'next_run_at'], name='scheduler_s_status_30491c_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['task_definition', 'status'], name='scheduler_s_task_de_4dfec1_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['status', 'queued_at'], name='scheduler_t_status_3cc2de_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['scheduled_task', 'status'], name='scheduler_t_schedul_9da932_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['celery_task_id'], name='scheduler_t_celery__192c03_idx'),
        ),
        migrations.AddIndex(
            model_name='taskalert',
            index=models.Index(fields=['severity', 'is_resolved'], name='scheduler_t_severit_3b135a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskalert',
            index=models.Index(fields=['alert_type', 'created_at'], name='scheduler_t_alert_t_3cd791_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['execution', 'level'], name='scheduler_t_executi_fa6233_idx'),
        ),
    ]
