# Generated by Django 6.0.3 on 2026-05-04 06:01

import cloudinary.models
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_short_description_alter_product_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeType',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('footwear', 'Footwear'), ('accessory', 'Accessory'), ('measurement', 'Measurement-Based'), ('custom', 'Custom')], default='clothing', help_text='UI hint for the product builder size picker.', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Product Size Type',
                'verbose_name_plural': 'Product Size Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ['name'], 'verbose_name': 'Product Color', 'verbose_name_plural': 'Product Colors'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Product Size', 'verbose_name_plural': 'Product Sizes'},
        ),
        migrations.AddField(
            model_name='product',
            name='age_group',
            field=models.CharField(blank=True, choices=[('adult', 'Adult'), ('teen', 'Teen (13-17)'), ('child', 'Child (4-12)'), ('toddler', 'Toddler (1-3)'), ('infant', 'Infant (0-12 months)')], help_text='Age group this product is designed for.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Brand New'), ('used', 'Used / Pre-owned'), ('refurbished', 'Refurbished')], default='new', help_text='Physical condition of the product.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='gender_target',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex'), ('boys', 'Boys'), ('girls', 'Girls'), ('kids', 'Kids')], help_text='Primary gender target for catalog segmentation.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, help_text='Client-generated UUID for safe network-retry. One product per key.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_pre_order',
            field=models.BooleanField(default=False, help_text='If True, the product is available for pre-order before stock arrives.'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_stock',
            field=models.PositiveIntegerField(blank=True, help_text='Optional stock ceiling. Service enforces this to prevent over-stocking.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description override. Shown in search-engine snippets.', max_length=320),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title tag override. Defaults to product title when blank.', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='pre_order_date',
            field=models.DateField(blank=True, help_text='Expected dispatch date for pre-order items.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Product weight in kg. Used as fallback when no shipping profile exists.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive colours are hidden from the product builder colour picker.'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='swatch_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional branded swatch image (e.g. fabric texture). Displayed instead of hex swatch when present.', max_length=255, null=True, verbose_name='swatch_image'),
        ),
        migrations.AddField(
            model_name='productgallerymedia',
            name='duration_sec',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Duration in seconds for video media items.', null=True),
        ),
        migrations.AddField(
            model_name='productgallerymedia',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='If True, this media item is used as the product cover image on listings.'),
        ),
        migrations.AddField(
            model_name='productgallerymedia',
            name='video_thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Static poster frame for video gallery items. Auto-extracted by Cloudinary.', max_length=255, null=True, verbose_name='video_thumbnail'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, help_text='Client-generated UUID. Prevents duplicate review on retry.', null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='abbreviation',
            field=models.CharField(blank=True, help_text="Short form displayed on product cards and size chips (e.g. 'XS', '44').", max_length=10),
        ),
        migrations.AddField(
            model_name='productsize',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower value = displayed first in the size picker.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, help_text='EAN-13 / UPC-A / QR barcode for warehouse/logistics integrations.', max_length=100),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='dimensions_cm',
            field=models.JSONField(blank=True, help_text='Packed dimensions in cm. Format: {"length": 30, "width": 20, "height": 10}', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If True, this variant is pre-selected on the product detail page.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal vendor notes for this variant (not shown to customers).'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Variant weight in kilograms. Used to calculate shipping cost.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='productwishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_wishlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductCertification',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('certification_type', models.CharField(choices=[('organic', 'Organic'), ('fair_trade', 'Fair Trade'), ('recycled', 'Recycled Materials'), ('handmade', 'Handmade'), ('quality', 'Quality Assured'), ('safety', 'Safety Tested'), ('vegan', 'Vegan'), ('cruelty_free', 'Cruelty-Free'), ('local', 'Locally Made'), ('nafdac', 'NAFDAC Certified'), ('son', 'SON Certified'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('name', models.CharField(help_text="Display name of the certification e.g. 'GOTS Certified Organic'.", max_length=120)),
                ('issuing_body', models.CharField(blank=True, max_length=200)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Set by platform admin after document verification.')),
                ('badge_image', cloudinary.models.CloudinaryField(blank=True, help_text='Official certification badge image displayed on PDP.', max_length=255, null=True, verbose_name='badge_image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Certification',
                'verbose_name_plural': 'Product Certifications',
                'ordering': ['-is_verified', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFabric',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('fabric_type', models.CharField(help_text="Primary fabric type e.g. 'Cotton', 'Silk', 'Polyester Blend'.", max_length=120)),
                ('composition', models.JSONField(blank=True, default=dict, help_text='Fabric composition percentages. Format: [{"material": "Cotton", "percentage": 80}, {"material": "Polyester", "percentage": 20}]')),
                ('care_instructions', models.CharField(choices=[('machine_wash', 'Machine Wash'), ('hand_wash', 'Hand Wash'), ('dry_clean', 'Dry Clean Only'), ('do_not_wash', 'Do Not Wash'), ('cold_wash', 'Cold Water Wash'), ('tumble_dry', 'Tumble Dry Low'), ('air_dry', 'Air Dry')], default='machine_wash', max_length=20)),
                ('care_notes', models.TextField(blank=True, help_text='Additional care instructions displayed to the buyer.')),
                ('is_organic', models.BooleanField(default=False, help_text='Certified organic fabric.')),
                ('is_vegan', models.BooleanField(default=False, help_text='Free from animal-derived materials.')),
                ('country_of_origin', models.CharField(blank=True, help_text='Country where the fabric was woven / manufactured.', max_length=80)),
                ('product', models.OneToOneField(help_text='Each product has at most one Fabric record.', on_delete=django.db.models.deletion.CASCADE, related_name='fabric', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Fabric',
                'verbose_name_plural': 'Product Fabrics',
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price before the change. Null for the initial listing.', max_digits=12, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('change_reason', models.CharField(choices=[('initial', 'Initial Listing'), ('promotion', 'Promotional Price'), ('market_adjustment', 'Market Adjustment'), ('cost_increase', 'Cost Increase'), ('seasonal', 'Seasonal Discount'), ('flash_sale', 'Flash Sale'), ('correction', 'Price Correction'), ('other', 'Other')], default='market_adjustment', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_price_changes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Price History',
                'verbose_name_plural': 'Product Price Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductShippingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, help_text='Packed weight in kilograms used for shipping rate calculation.', max_digits=7)),
                ('length_cm', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('width_cm', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('height_cm', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('is_fragile', models.BooleanField(default=False)),
                ('requires_signature', models.BooleanField(default=False)),
                ('restricted_countries', models.JSONField(blank=True, default=list, help_text='ISO-3166-1 alpha-2 country codes where this product cannot be shipped. Format: ["NG", "GH", "ZA"]')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='If order total exceeds this amount, shipping is free. Null = use platform default.', max_digits=12, null=True)),
                ('processing_days', models.PositiveSmallIntegerField(default=1, help_text='Number of business days to prepare the item for dispatch.')),
                ('preferred_couriers', models.ManyToManyField(blank=True, help_text='Couriers the vendor prefers for this product.', related_name='preferred_for_products', to='product.deliverycourier')),
                ('product', models.OneToOneField(help_text='Each product has at most one shipping profile.', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_profile', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Shipping Profile',
                'verbose_name_plural': 'Product Shipping Profiles',
            },
        ),
        migrations.AddField(
            model_name='productsize',
            name='size_type',
            field=models.ForeignKey(blank=True, help_text='Taxonomy category this size belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='product.productsizetype'),
        ),
        migrations.CreateModel(
            name='ProductMeasurementGuide',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('size_label', models.CharField(help_text="Display label e.g. 'S', 'M', '44', '38-40'. Used when size FK is not selected.", max_length=30)),
                ('chest_cm', models.CharField(blank=True, help_text="Chest range e.g. '90-100'.", max_length=20)),
                ('waist_cm', models.CharField(blank=True, help_text="Waist range e.g. '70-80'.", max_length=20)),
                ('hip_cm', models.CharField(blank=True, help_text="Hip range e.g. '90-100'.", max_length=20)),
                ('length_cm', models.CharField(blank=True, help_text="Garment length e.g. '110'.", max_length=20)),
                ('shoulder_cm', models.CharField(blank=True, max_length=20)),
                ('sleeve_cm', models.CharField(blank=True, max_length=20)),
                ('inseam_cm', models.CharField(blank=True, max_length=20)),
                ('foot_length_cm', models.CharField(blank=True, help_text='For footwear: foot length in cm.', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(help_text='Size guide rows for this product.', on_delete=django.db.models.deletion.CASCADE, related_name='measurement_guide', to='product.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_guides', to='product.productsize')),
            ],
            options={
                'verbose_name': 'Measurement Guide Row',
                'verbose_name_plural': 'Measurement Guide Rows',
                'ordering': ['sort_order'],
                'unique_together': {('product', 'size_label')},
            },
        ),
        migrations.CreateModel(
            name='ProductViewLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Django session key for anonymous tracking.', max_length=40)),
                ('referrer_url', models.CharField(blank=True, help_text='URL of the page that linked to this PDP (for traffic attribution).', max_length=500)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('duration_seconds', models.PositiveSmallIntegerField(blank=True, help_text='How long the user spent on the PDP (sent on page leave).', null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='product.product')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user who viewed the product. Null for anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product View Log',
                'verbose_name_plural': 'Product View Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='idx_viewlog_product_date'), models.Index(fields=['user', 'created_at'], name='idx_viewlog_user_date'), models.Index(fields=['session_key'], name='idx_viewlog_session')],
            },
        ),
    ]
