# Generated by Django 6.0.3 on 2026-05-06 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_canonical_categories_remove_brand'),
        ('vendor', '0002_fix_cartitem_related_name_to_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Null = applies to all products from this vendor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_specific_coupon', to='product.product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Null = platform-wide coupon.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_platform_wide_coupons', to='vendor.vendorprofile'),
        ),
        migrations.AlterField(
            model_name='productcertification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_certifications', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productcommissionsnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_commission_snapshots', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productcommissionsnapshot',
            name='set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_commission_snapshots_set_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productfabric',
            name='product',
            field=models.OneToOneField(help_text='Each product has at most one Fabric record.', on_delete=django.db.models.deletion.CASCADE, related_name='product_fabric', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productmeasurementguide',
            name='product',
            field=models.ForeignKey(help_text='Size guide rows for this product.', on_delete=django.db.models.deletion.CASCADE, related_name='product_measurement_guide', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productmeasurementguide',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_size_measurement_guides', to='product.productsize'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_product_price_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_history', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productshippingprofile',
            name='preferred_couriers',
            field=models.ManyToManyField(blank=True, help_text='Couriers the vendor prefers for this product.', related_name='preferred_for_custom_shipping_products', to='product.deliverycourier'),
        ),
        migrations.AlterField(
            model_name='productshippingprofile',
            name='product',
            field=models.OneToOneField(help_text='Each product has at most one custom shipping profile.', on_delete=django.db.models.deletion.CASCADE, related_name='product_custom_shipping_profile', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_type',
            field=models.ForeignKey(blank=True, help_text='Taxonomy category this size belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_size_types', to='product.productsizetype'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_color_variants', to='product.productcolor'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_size_variants', to='product.productsize'),
        ),
        migrations.AlterField(
            model_name='productviewlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_view_logs', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productviewlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who viewed the product. Null for anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_product_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productwishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_wishlist_entries', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productwishlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_product_wishlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
