# Generated by Django 6.0.3 on 2026-06-06 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productdraftsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_description',
            field=models.TextField(blank=True, help_text='AI-generated product description. Auto-populated by catalog AI pipeline.'),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_trend_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Trending score 0–100 from AI pipeline. Used to rank catalog feeds.', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='body_type_fit',
            field=models.JSONField(blank=True, default=list, help_text="Body types this product is recommended for e.g. ['slim','curvy','athletic']."),
        ),
        migrations.AddField(
            model_name='product',
            name='carbon_footprint_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Estimated carbon footprint in kg CO₂ equivalent. Surfaced on product detail page.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion_tags',
            field=models.JSONField(blank=True, default=list, help_text="AI-inferred occasion labels e.g. ['wedding','everyday','office']."),
        ),
        migrations.AddField(
            model_name='product',
            name='style_tags',
            field=models.JSONField(blank=True, default=list, help_text="AI-inferred style labels e.g. ['casual','boho','formal']. Used for recommendation engine."),
        ),
        migrations.AddField(
            model_name='product',
            name='sustainability_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Sustainability score 0–100. Computed from material, supply chain, and packaging data.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
