# Generated by Django 6.0.3 on 2026-06-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
