# Generated by Django 6.0.3 on 2026-06-13 22:15

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_shipping_amount_and_more'),
        ('vendor', '0008_vendorprofile_last_active_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallerymedia',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Optional color link to show this media when a color is selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_media', to='product.productcolor'),
        ),
        migrations.AddField(
            model_name='productgallerymedia',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Optional variant link to display specific color/size media.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_media', to='product.productvariant'),
        ),
        migrations.CreateModel(
            name='VendorMeasurementTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('name', models.CharField(help_text="e.g. 'Men's Slim Senator', 'Standard Kaftan'", max_length=120)),
                ('description', models.TextField(blank=True, help_text='Optional description of this measurement profile.')),
                ('vendor', models.ForeignKey(help_text='Vendor who owns this reusable sizing template.', on_delete=django.db.models.deletion.CASCADE, related_name='measurement_templates', to='vendor.vendorprofile')),
            ],
            options={
                'verbose_name': 'Vendor Measurement Template',
                'verbose_name_plural': 'Vendor Measurement Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_template',
            field=models.ForeignKey(blank=True, help_text='Optional measurement template applied to this product to populate size chart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.vendormeasurementtemplate'),
        ),
        migrations.AddField(
            model_name='productmeasurementguide',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Optional template this guide row was copied/referenced from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_guides', to='product.vendormeasurementtemplate'),
        ),
        migrations.CreateModel(
            name='VendorMeasurementTemplateRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(help_text="Display label e.g. 'S', 'M', '44', '38-40'.", max_length=30)),
                ('chest_cm', models.CharField(blank=True, max_length=20)),
                ('waist_cm', models.CharField(blank=True, max_length=20)),
                ('hip_cm', models.CharField(blank=True, max_length=20)),
                ('length_cm', models.CharField(blank=True, max_length=20)),
                ('shoulder_cm', models.CharField(blank=True, max_length=20)),
                ('sleeve_cm', models.CharField(blank=True, max_length=20)),
                ('inseam_cm', models.CharField(blank=True, max_length=20)),
                ('foot_length_cm', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_size_rows', to='product.productsize')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_rows', to='product.vendormeasurementtemplate')),
            ],
            options={
                'verbose_name': 'Template Row',
                'verbose_name_plural': 'Template Rows',
                'ordering': ['sort_order'],
                'unique_together': {('template', 'size_label')},
            },
        ),
    ]
