# Generated by Django 6.0.3 on 2026-06-14 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productgallerymedia_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendormeasurementtemplaterow',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vendormeasurementtemplaterow',
            name='size',
        ),
        migrations.RemoveField(
            model_name='vendormeasurementtemplaterow',
            name='template',
        ),
        migrations.AlterUniqueTogether(
            name='productmeasurementguide',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=2500, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productmeasurementguide',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Size guide rows for this product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_measurement_guide', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productmeasurementguide',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template this guide row belongs to (or was copied/referenced from).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_rows', to='product.vendormeasurementtemplate'),
        ),
        migrations.AddConstraint(
            model_name='productmeasurementguide',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product', 'size_label'), name='unique_product_size_label'),
        ),
        migrations.AddConstraint(
            model_name='productmeasurementguide',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', True), ('template__isnull', False)), fields=('template', 'size_label'), name='unique_template_size_label'),
        ),
        migrations.DeleteModel(
            name='VendorMeasurementTemplateRow',
        ),
    ]
