# Generated by Django 6.0.3 on 2026-06-14 02:48

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_vendormeasurementtemplaterow_unique_together_and_more'),
        ('vendor', '0008_vendorprofile_last_active_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeAndMeasurementGuide',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('name', models.CharField(help_text="e.g. 'Men's Slim Senator', 'Standard Kaftan'", max_length=120)),
                ('description', models.CharField(choices=[('clothing', 'Clothing'), ('footwear', 'Footwear'), ('accessory', 'Accessory'), ('measurement', 'Measurement-Based'), ('custom', 'Custom')], default='custom', help_text='Description of this measurement guide.', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='This is the default measurement guide for this product.')),
                ('save_as_template', models.BooleanField(default=False, help_text='Save this measurement guide as a reusable template for future use.')),
                ('size_label', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('All_Sizes', 'All_Sizes'), ('Custom', 'Custom')], default='M', help_text="Display label e.g. 'XS', 'S', 'M', 'L', 'XL', 'XXL', 'Custom'.", max_length=30)),
                ('chest_cm', models.CharField(blank=True, help_text="Chest range e.g. '90-100'.", max_length=20)),
                ('waist_cm', models.CharField(blank=True, help_text="Waist range e.g. '70-80'.", max_length=20)),
                ('hip_cm', models.CharField(blank=True, help_text="Hip range e.g. '90-100'.", max_length=20)),
                ('length_cm', models.CharField(blank=True, help_text="Garment length e.g. '110'.", max_length=20)),
                ('shoulder_cm', models.CharField(blank=True, max_length=20)),
                ('sleeve_cm', models.CharField(blank=True, max_length=20)),
                ('inseam_cm', models.CharField(blank=True, max_length=20)),
                ('foot_length_cm', models.CharField(blank=True, help_text='For footwear: foot length in cm.', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower value = displayed first in the size picker.')),
            ],
            options={
                'verbose_name': 'Measurement Guide Row',
                'verbose_name_plural': 'Measurement Guide Rows',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='productmeasurementguide',
            name='unique_product_size_label',
        ),
        migrations.RemoveConstraint(
            model_name='productmeasurementguide',
            name='unique_template_size_label',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size_type',
        ),
        migrations.RemoveField(
            model_name='vendormeasurementtemplate',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_template',
            field=models.CharField(blank=True, help_text='Optional measurement template name applied to this product to populate size chart.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productsizeandmeasurementguide',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Size guide rows for this product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_measurement_guide', to='product.product'),
        ),
        migrations.AddField(
            model_name='productsizeandmeasurementguide',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor who owns this reusable sizing template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_templates', to='vendor.vendorprofile'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='product_size_and_measurement_guides', to='product.productsizeandmeasurementguide'),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_size_variants', to='product.productsizeandmeasurementguide'),
        ),
        migrations.RemoveField(
            model_name='productmeasurementguide',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productmeasurementguide',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productmeasurementguide',
            name='template',
        ),
        migrations.DeleteModel(
            name='ProductSizeType',
        ),
        migrations.AddConstraint(
            model_name='productsizeandmeasurementguide',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product', 'size_label'), name='unique_product_size_label'),
        ),
        migrations.AddConstraint(
            model_name='productsizeandmeasurementguide',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', True), ('vendor__isnull', False)), fields=('vendor', 'name', 'size_label'), name='unique_vendor_template_size_label'),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='ProductMeasurementGuide',
        ),
        migrations.DeleteModel(
            name='VendorMeasurementTemplate',
        ),
    ]
