# Generated by Django 6.0.3 on 2026-06-14 22:50

import cloudinary.models
import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productsizeandmeasurementguide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallerymedia',
            name='color',
        ),
        # IMPORTANT: Clear unique_together BEFORE removing 'color' field —
        # otherwise Django tries to lookup the dropped column while deleting the index.
        # Use SeparateDatabaseAndState because the constraint was recorded in migration
        # state but was NEVER applied to the actual database — running DROP CONSTRAINT
        # would fail with "Found wrong number (0) of constraints".
        migrations.SeparateDatabaseAndState(
            database_operations=[],   # no-op: constraint doesn't exist in DB
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='productvariant',
                    unique_together=None,
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productgallerymedia',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productgallerymedia',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productsizeandmeasurementguide',
            name='product',
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='save_as_template',
            field=models.BooleanField(default=True, help_text='Save this measurement guide as a reusable template for future use.'),
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='size_label',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('Custom', 'Custom')], default='M', help_text="Display label e.g. 'XS', 'S', 'M', 'L', 'XL', 'XXL', 'Custom'.", max_length=30),
        ),
        migrations.CreateModel(
            name='ProductVariantGalleryMedia',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('sku', models.CharField(blank=True, max_length=80, unique=True)),
                ('color_name', models.CharField(blank=True, max_length=100)),
                ('color_hex', models.CharField(blank=True, help_text='e.g. #FDA600', max_length=7)),
                ('swatch_image', cloudinary.models.CloudinaryField(blank=True, help_text='Optional branded swatch image (e.g. fabric texture).', max_length=255, null=True, verbose_name='swatch_image')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='If set, overrides the parent product price for this variant.', max_digits=12, null=True)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='variant_image')),
                ('media', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False, help_text='If True, this media item is used as the product cover image on listings.')),
                ('video_thumbnail', cloudinary.models.CloudinaryField(blank=True, help_text='Static poster frame for video gallery items. Auto-extracted by Cloudinary.', max_length=255, null=True, verbose_name='video_thumbnail')),
                ('duration_sec', models.PositiveSmallIntegerField(blank=True, help_text='Duration in seconds for video media items.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='If True, this variant is pre-selected on the product detail page.')),
                ('barcode', models.CharField(blank=True, help_text='EAN-13 / UPC-A / QR barcode for warehouse/logistics integrations.', max_length=100)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Variant weight in kilograms. Used to calculate shipping cost.', max_digits=6, null=True)),
                ('dimensions_cm', models.JSONField(blank=True, help_text='Packed dimensions in cm. Format: {"length": 30, "width": 20, "height": 10}', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal vendor notes for this variant (not shown to customers).')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_size_variants', to='product.productsizeandmeasurementguide')),
            ],
            options={
                'verbose_name': 'Product Variant Gallery Media',
                'verbose_name_plural': 'Product Variant Gallery Media',
                'unique_together': {('product', 'size', 'color_name')},
            },
        ),
        migrations.AlterField(
            model_name='productinventorylog',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='product.productvariantgallerymedia'),
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductGalleryMedia',
        ),
    ]
