# Generated by Django 6.0.3 on 2026-06-14 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_consolidate_product_variant_gallery_media'),
        ('product', '0020_consolidate_product_variant_gallery_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
