# Generated by Django 6.0.3 on 2026-06-14 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_consolidate_product_variant_gallery_media'),
        ('vendor', '0008_vendorprofile_last_active_at_and_more'),
    ]

    operations = [
        # These constraints reference the removed 'product' field; their condition SQL
        # cannot be built after the field deletion. Skip DB execution via SeparateDatabaseAndState.
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # no-op in DB
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='productsizeandmeasurementguide',
                    name='unique_product_size_label',
                ),
                migrations.RemoveConstraint(
                    model_name='productsizeandmeasurementguide',
                    name='unique_vendor_template_size_label',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='productvariantgallerymedia',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_size_variants', to='product.productsizeandmeasurementguide'),
        ),
        migrations.AlterField(
            model_name='productvariantgallerymedia',
            name='sku',
            field=models.CharField(blank=True, help_text='Auto-generated SKU. Unique across all variants.', max_length=80, unique=True),
        ),
        migrations.AddConstraint(
            model_name='productsizeandmeasurementguide',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor__isnull', False)), fields=('vendor', 'name', 'size_label'), name='unique_vendor_template_size_label'),
        ),
    ]
