# Generated by Django 6.0.3 on 2026-06-15 05:28

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_phase12_catalog_2026_scale_fields'),
        ('product', '0022_add_sku_fix_constraints'),
        ('vendor', '0008_vendorprofile_last_active_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='measurement_template',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='productshippingprofile',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariantgallerymedia',
            name='dimensions_cm',
        ),
        migrations.RemoveField(
            model_name='productvariantgallerymedia',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productvariantgallerymedia',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productvariantgallerymedia',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='productvariantgallerymedia',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='productvariantgallerymedia',
            name='price_override',
        ),
        migrations.RemoveField(
            model_name='productvariantgallerymedia',
            name='stock_qty',
        ),
        migrations.RemoveField(
            model_name='productvariantgallerymedia',
            name='swatch_image',
        ),
        migrations.RemoveField(
            model_name='productvariantgallerymedia',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_shipping_profiles', to='product.productshippingprofile'),
        ),
        migrations.AddField(
            model_name='productshippingprofile',
            name='dimensions_cm',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productshippingprofile',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_shipping_profiles', to='vendor.vendorprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_specific_coupon', to='product.product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_platform_wide_coupons', to='vendor.vendorprofile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='age_group',
            field=models.CharField(blank=True, choices=[('adult', 'Adult'), ('teen', 'Teen (13-17)'), ('child', 'Child (4-12)'), ('toddler', 'Toddler (1-3)'), ('infant', 'Infant (0-12 months)')], help_text='Age-segment target for catalog organization.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='ai_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ai_trend_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Trendiness index (0–100). Computed from trending hashtags, sales velocity, and social buzz.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='body_type_fit',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbon_footprint_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Estimated CO₂e in kilograms per unit, computed from materials, dyeing, and transport legs.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cash_payment_mode',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('cod', 'Cash On Delivery'), ('pay_at_shop', 'Pay At Shop'), ('both', 'Both')], default='disabled', help_text='Enables or disables Cash on Delivery (COD) channels.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(help_text='Primary classification groups. Capped at 1 to 15 allocations.', related_name='category_products', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Calculated platform cut snapshot recorded on item listings.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Brand New'), ('used', 'Used / Pre-owned'), ('refurbished', 'Refurbished')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, help_text='Unique key generated on client forms to prevent network duplications.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_customisable',
            field=models.BooleanField(default=False, help_text='Allows customization requests via direct negotiation.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_pre_order',
            field=models.BooleanField(default=False, help_text='Specifies if items can be purchased prior to materials arriving.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_stock',
            field=models.PositiveIntegerField(blank=True, help_text='Operational threshold to prevent oversell situations.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description tag override, Optional search snippet descriptive block.', max_length=320),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasion_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='pre_order_date',
            field=models.DateField(blank=True, help_text='Estimated shipment date for pre-order purchases.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_measurement',
            field=models.BooleanField(default=False, help_text='Forces the buyer to submit exact body sizes prior to checking out.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique SKU identifier generated automatically upon saving.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='style_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, help_text='Deep classification groups used for recommendation indices.', related_name='sub_category_products', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(help_text='The associated designer storefront profile.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_products', to='vendor.vendorprofile'),
        ),
        migrations.AlterField(
            model_name='productdraftsession',
            name='linked_product',
            field=models.ForeignKey(blank=True, help_text='The product that this draft is for, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_sessions', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productdraftsession',
            name='payload',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='productdraftsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('committed', 'Committed'), ('discarded', 'Discarded'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='productfaq',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productinventorylog',
            name='quantity_delta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinventorylog',
            name='reason',
            field=models.CharField(choices=[('sale', 'Sale'), ('restock', 'Restock'), ('adjustment', 'Manual Adjustment'), ('return', 'Customer Return'), ('damage', 'Damage / Loss'), ('reservation', 'Cart Reservation'), ('release', 'Cart Release (Abandoned)'), ('refund', 'Refund')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productinventorylog',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productinventorylog',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='product.productvariantgallerymedia'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='reply',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productshippingprofile',
            name='free_shipping_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides platform default shipping configuration limits.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productshippingprofile',
            name='preferred_couriers',
            field=models.ManyToManyField(blank=True, related_name='preferred_shipping_products', to='product.deliverycourier'),
        ),
        migrations.AlterField(
            model_name='productshippingprofile',
            name='processing_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productshippingprofile',
            name='restricted_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='productshippingprofile',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='chest_cm',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='description',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('footwear', 'Footwear'), ('accessory', 'Accessory'), ('measurement', 'Measurement-Based'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='foot_length_cm',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='hip_cm',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='length_cm',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='name',
            field=models.CharField(help_text="e.g. 'Men Senator Fit Guide'", max_length=120),
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='save_as_template',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='size_label',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('Custom', 'Custom')], default='M', max_length=30),
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_templates', to='vendor.vendorprofile'),
        ),
        migrations.AlterField(
            model_name='productsizeandmeasurementguide',
            name='waist_cm',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariantgallerymedia',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Visual swatch hex key. e.g. #FDA600', max_length=7),
        ),
        migrations.AlterField(
            model_name='productvariantgallerymedia',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Specifies if this asset serves as the primary catalog listing cover.'),
        ),
        migrations.AlterField(
            model_name='productvariantgallerymedia',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants_gallery_media', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productvariantgallerymedia',
            name='sku',
            field=models.CharField(blank=True, help_text='Variant-specific Stock Keeping Unit identifier.', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='productviewlog',
            name='referrer_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='productviewlog',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='productviewlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_product_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productwishlist',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='ProductFabricSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('fabric_type', models.CharField(help_text='e.g. Cashmere Blend', max_length=120)),
                ('care_instructions', models.CharField(choices=[('machine_wash', 'Machine Wash'), ('hand_wash', 'Hand Wash'), ('dry_clean', 'Dry Clean Only'), ('do_not_wash', 'Do Not Wash'), ('cold_wash', 'Cold Water Wash'), ('tumble_dry', 'Tumble Dry Low'), ('air_dry', 'Air Dry')], default='machine_wash', max_length=20)),
                ('is_organic', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('country_of_origin', models.CharField(blank=True, max_length=80)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_fabric_specification', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Fabric Specification',
                'verbose_name_plural': 'Product Fabric Specifications',
            },
        ),
        migrations.DeleteModel(
            name='ProductFabric',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
    ]
