# Generated by Django 6.0.3 on 2026-06-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_productspecification_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantgallerymedia',
            options={'ordering': ['ordering', 'created_at'], 'verbose_name': 'Product Variant Gallery Media', 'verbose_name_plural': 'Product Variant Gallery Media'},
        ),
    ]
