# Generated by Django 6.0.3 on 2026-06-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_productvariantgallerymedia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfabricspecification',
            name='care_notes',
            field=models.TextField(blank=True, help_text='Additional care instructions displayed to the buyer.'),
        ),
        migrations.AddField(
            model_name='productfabricspecification',
            name='composition',
            field=models.JSONField(blank=True, default=dict, help_text='Fabric composition percentages. Format: [{"material": "Cotton", "percentage": 80}, {"material": "Polyester", "percentage": 20}]'),
        ),
    ]
