# Generated by Django 6.0.3 on 2026-06-16 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_productfabricspecification_care_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfabricspecification',
            name='care_notes',
        ),
        migrations.RemoveField(
            model_name='productfabricspecification',
            name='composition',
        ),
    ]
