# Generated by Django 6.0.3 on 2026-06-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_productfabricspecification_care_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productdraftsession',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='productdraftsession',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='product',
            name='cash_payment_mode',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('cod', 'Cash On Delivery'), ('pay_at_shop', 'Pay At Shop'), ('payment_on_delivery', 'Payment On Delivery'), ('payment_before_delivery', 'Payment Before Delivery'), ('part_payment_before_delivery', 'Part Payment Before Delivery'), ('allow_all', 'Allow All')], default='disabled', help_text='Enables or disables Cash on Delivery (COD) channels.', max_length=32),
        ),
        migrations.AlterField(
            model_name='productfabricspecification',
            name='care_instructions',
            field=models.CharField(choices=[('machine_wash', 'Machine Wash'), ('hand_wash', 'Hand Wash'), ('dry_clean', 'Dry Clean Only'), ('do_not_wash', 'Do Not Wash'), ('cold_wash', 'Cold Water Wash'), ('tumble_dry', 'Tumble Dry Low'), ('air_dry', 'Air Dry'), ('allow_all', 'Allow All')], default='machine_wash', max_length=20),
        ),
    ]
