# Generated by Django 6.0.3 on 2026-06-19 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_remove_sku_from_product_fix_cash_payment_mode_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_categories',
        ),
    ]
