# Generated by Django 6.0.3 on 2026-06-30 04:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Provider Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Unique Slug')),
                ('provider_type', models.CharField(choices=[('sms', 'SMS'), ('payment', 'Payment Gateway'), ('ai', 'Artificial Intelligence'), ('storage', 'Cloud Storage'), ('notification', 'Notification Services'), ('analytics', 'Analytics Platforms'), ('other', 'Other Services')], max_length=20, verbose_name='Service Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('api_base_url', models.URLField(blank=True, verbose_name='API Base URL')),
                ('documentation_url', models.URLField(blank=True, verbose_name='Documentation URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Integration Provider',
                'verbose_name_plural': 'Integration Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Rule Name')),
                ('endpoint_pattern', models.CharField(help_text='Supports wildcards like *', max_length=255, verbose_name='Endpoint Pattern')),
                ('max_requests', models.IntegerField(verbose_name='Max Requests')),
                ('time_window_seconds', models.IntegerField(verbose_name='Time Window (Seconds)')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('user', 'User'), ('ip', 'IP Address')], default='user', max_length=20, verbose_name='Scope')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='integrations.integrationprovider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Rate Limit Rule',
                'verbose_name_plural': 'Rate Limit Rules',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Webhook Name')),
                ('endpoint_url', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Endpoint URL can only contain letters, numbers, hyphens and underscores.', regex='^[a-zA-Z0-9-_/]+$')], verbose_name='Endpoint URL')),
                ('secret_key', models.CharField(help_text='Used to verify webhook payload signatures.', max_length=255, verbose_name='Secret Key')),
                ('events', models.JSONField(default=list, help_text='List of event slugs this webhook processes.', verbose_name='Subscribed Events')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('retry_count', models.IntegerField(default=3, verbose_name='Retry Count')),
                ('timeout_seconds', models.IntegerField(default=30, verbose_name='Timeout (Seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='integrations.integrationprovider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='Log Level')),
                ('service_name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='Request Data')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Response Data')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Status Code')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='Duration (ms)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Logged At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integrationprovider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Integration Log',
                'verbose_name_plural': 'Integration Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'created_at'], name='integration_provide_939066_idx'), models.Index(fields=['log_level', 'created_at'], name='integration_log_lev_10bfc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=100, verbose_name='Key Name')),
                ('key_value', models.TextField(help_text='Stored in encrypted format.', verbose_name='Key Value')),
                ('is_encrypted', models.BooleanField(default=True, verbose_name='Is Encrypted')),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='production', max_length=20, verbose_name='Environment')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credentials', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='integrations.integrationprovider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Integration Credential',
                'verbose_name_plural': 'Integration Credentials',
                'ordering': ['provider', 'key_name'],
                'unique_together': {('provider', 'key_name', 'environment')},
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100, verbose_name='Event Type')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('headers', models.JSONField(default=dict, verbose_name='Headers')),
                ('signature', models.CharField(blank=True, max_length=255, verbose_name='Signature')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Is Signature Valid')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Is Processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_received', to='integrations.webhookendpoint', verbose_name='Webhook')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['webhook', 'received_at'], name='integration_webhook_20c54a_idx'), models.Index(fields=['is_processed', 'received_at'], name='integration_is_proc_9e6c6e_idx')],
            },
        ),
    ]
