# Generated by Django 6.0.3 on 2026-04-27 02:48

import django.db.models.deletion
import uuid
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial_product_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='product.coupon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('action', models.CharField(choices=[('item_added', 'Item Added'), ('item_removed', 'Item Removed'), ('quantity_updated', 'Quantity Updated'), ('coupon_applied', 'Coupon Applied'), ('coupon_removed', 'Coupon Removed'), ('cart_cleared', 'Cart Cleared'), ('cart_merged', 'Cart Merged (Guest → Auth)')], max_length=30)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='cart.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
            options={
                'verbose_name': 'Cart Activity Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_saved_for_later', models.BooleanField(default=False)),
                ('idempotency_key', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='product.productvariant')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'unique_together': {('cart', 'product', 'variant')},
            },
        ),
    ]
