# Generated by Django 6.0.3 on 2026-06-14 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_id_alter_cartactivitylog_id_and_more'),
        ('product', '0020_consolidate_product_variant_gallery_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='product.productvariantgallerymedia'),
        ),
    ]
