# Generated by Django 6.0.3 on 2026-04-23 21:39

import apps.admin_backend.models.collection
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='brand.jpg', null=True, upload_to='brand_images/')),
                ('cloudinary_url', models.URLField(blank=True, help_text='Auto-populated by Cloudinary webhook after presign upload.', max_length=800, null=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, default='category.jpg', null=True, upload_to='category_images/')),
                ('cloudinary_url', models.URLField(blank=True, help_text='Auto-populated by Cloudinary webhook after presign upload.', max_length=800, null=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='gallery/bg_img/', validators=[apps.admin_backend.models.collection.validate_image_cover_extension])),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/product_img/', validators=[apps.admin_backend.models.collection.validate_image_cover_extension])),
                ('cloudinary_url', models.URLField(blank=True, help_text='Main collection image — auto-populated by Cloudinary webhook.', max_length=800, null=True)),
                ('background_cloudinary_url', models.URLField(blank=True, help_text='Background hero image — auto-populated by Cloudinary webhook.', max_length=800, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='EmailBackendConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP (Gmail)'), ('django.core.mail.backends.console.EmailBackend', 'Console'), ('anymail.backends.mailgun.EmailBackend', 'Mailgun'), ('zoho_zeptomail.backend.zeptomail_backend.ZohoZeptoMailEmailBackend', 'Zoho ZeptoMail'), ('anymail.backends.sendgrid.EmailBackend', 'SendGrid')], db_index=True, default='django.core.mail.backends.smtp.EmailBackend', help_text='Choose the email backend you wish to use for sending emails.  Consider factors like reliability, cost, and integration with your existing infrastructure.  SMTP (Gmail) is suitable for development or low-volume sending. For production environments, consider Mailgun, SendGrid, or Zoho ZeptoMail.', max_length=250, verbose_name='Select Email Backend')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Backend Configuration',
                'verbose_name_plural': 'Email Backend Configuration',
            },
        ),
        migrations.CreateModel(
            name='SMSBackendConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_backend', models.CharField(choices=[('apps.common.providers.SMS.twilio.TwilioSMSProvider', 'Twilio (Global/Robust)'), ('apps.common.providers.SMS.termii.TermiiSMSProvider', 'Termii (Nigeria Focused)'), ('apps.common.providers.SMS.bulksmsNG.BulksmsNGSMSProvider', 'BulkSMS Nigeria (Cost Effective)')], db_index=True, default='apps.common.providers.SMS.twilio.TwilioSMSProvider', help_text='Choose the active SMS provider class for the system. NOTE: Ensure the corresponding API Credentials (Keys/Secrets) are correctly set in your Server Environment Variables before switching.', max_length=250, verbose_name='Select SMS Backend Provider')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The timestamp when this configuration was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this configuration was last modified.')),
            ],
            options={
                'verbose_name': 'SMS Backend Configuration',
                'verbose_name_plural': 'SMS Backend Configuration',
            },
        ),
    ]
