# Generated by Django 6.0.3 on 2026-04-27 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBackendConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP (Gmail)'), ('django.core.mail.backends.console.EmailBackend', 'Console'), ('anymail.backends.mailgun.EmailBackend', 'Mailgun'), ('zoho_zeptomail.backend.zeptomail_backend.ZohoZeptoMailEmailBackend', 'Zoho ZeptoMail'), ('anymail.backends.sendgrid.EmailBackend', 'SendGrid')], db_index=True, default='django.core.mail.backends.smtp.EmailBackend', help_text='Choose the email backend you wish to use for sending emails.  Consider factors like reliability, cost, and integration with your existing infrastructure.  SMTP (Gmail) is suitable for development or low-volume sending. For production environments, consider Mailgun, SendGrid, or Zoho ZeptoMail.', max_length=250, verbose_name='Select Email Backend')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Backend Configuration',
                'verbose_name_plural': 'Email Backend Configuration',
                'indexes': [models.Index(fields=['email_backend'], name='email_backend_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSBackendConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_backend', models.CharField(choices=[('apps.common.providers.SMS.twilio.TwilioSMSProvider', 'Twilio (Global/Robust)'), ('apps.common.providers.SMS.termii.TermiiSMSProvider', 'Termii (Nigeria Focused)'), ('apps.common.providers.SMS.bulksmsNG.BulksmsNGSMSProvider', 'BulkSMS Nigeria (Cost Effective)')], db_index=True, default='apps.common.providers.SMS.twilio.TwilioSMSProvider', help_text='Choose the active SMS provider class for the system. NOTE: Ensure the corresponding API Credentials (Keys/Secrets) are correctly set in your Server Environment Variables before switching.', max_length=250, verbose_name='Select SMS Backend Provider')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The timestamp when this configuration was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this configuration was last modified.')),
            ],
            options={
                'verbose_name': 'SMS Backend Configuration',
                'verbose_name_plural': 'SMS Backend Configuration',
                'indexes': [models.Index(fields=['sms_backend'], name='sms_backend_idx')],
            },
        ),
    ]
