# Generated by Django 6.0.3 on 2026-05-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbackendconfig',
            name='email_backend',
            field=models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP (Gmail)'), ('django.core.mail.backends.console.EmailBackend', 'Console'), ('anymail.backends.sendgrid.EmailBackend', 'SendGrid'), ('anymail.backends.mailgun.EmailBackend', 'Mailgun'), ('zoho_zeptomail.backend.zeptomail_backend.ZohoZeptoMailEmailBackend', 'Zoho ZeptoMail'), ('anymail.backends.brevo.EmailBackend', 'Brevo')], db_index=True, default='django.core.mail.backends.smtp.EmailBackend', help_text='Choose the transactional email backend used by the platform. SMTP (Gmail) is acceptable for development or low-volume flows. Production environments should use Mailgun, SendGrid, Zoho ZeptoMail, or Brevo.', max_length=250, verbose_name='Select Email Backend'),
        ),
    ]
