# Generated by Django 6.0.3 on 2026-05-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0002_alter_emailbackendconfig_email_backend'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailbackendconfig',
            name='email_backend_idx',
        ),
        migrations.DeleteModel(
            name='EmailBackendConfig',
        ),
        migrations.RemoveIndex(
            model_name='smsbackendconfig',
            name='sms_backend_idx',
        ),
        migrations.DeleteModel(
            name='SMSBackendConfig',
        ),
    ]
