# Generated by Django 4.2.7 on 2024-05-29 16:42

import admin_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='background_image',
            field=models.ImageField(upload_to='bg_img/', validators=[admin_backend.models.validate_image_cover_extension]),
        ),
        migrations.AlterField(
            model_name='collections',
            name='image',
            field=models.ImageField(upload_to='product_img/', validators=[admin_backend.models.validate_image_cover_extension]),
        ),
    ]
