# Generated by Django 6.0.3 on 2026-03-22 21:37

import admin_backend.models.collection
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cloudinary_url',
            field=models.URLField(blank=True, help_text='Auto-populated by Cloudinary webhook after presign upload.', max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='cloudinary_url',
            field=models.URLField(blank=True, help_text='Auto-populated by Cloudinary webhook after presign upload.', max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='background_cloudinary_url',
            field=models.URLField(blank=True, help_text='Background hero image — auto-populated by Cloudinary webhook.', max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='cloudinary_url',
            field=models.URLField(blank=True, help_text='Main collection image — auto-populated by Cloudinary webhook.', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/bg_img/', validators=[admin_backend.models.collection.validate_image_cover_extension]),
        ),
        migrations.AlterField(
            model_name='collections',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/product_img/', validators=[admin_backend.models.collection.validate_image_cover_extension]),
        ),
    ]
