# Generated by Django 6.0.3 on 2026-04-23 21:39

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('bio', models.TextField(blank=True, default='', help_text='Short personal bio (max 500 chars).', max_length=500)),
                ('default_shipping_address', models.TextField(blank=True, default='', help_text='Default shipping address for checkout.')),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='Nigeria', max_length=100)),
                ('preferred_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='', help_text='Preferred clothing size.', max_length=10)),
                ('style_preferences', models.JSONField(blank=True, default=list, help_text='Style tags: ["casual", "afrocentric", "formal"]. Used by AI engine.')),
                ('favourite_colours', models.JSONField(blank=True, default=list, help_text='Favourite colour hex codes or names.')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent_ngn', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_profile_complete', models.BooleanField(default=False, help_text='True once size, address, and style preferences are filled in.')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Receive order and promo email notifications.')),
                ('sms_notifications_enabled', models.BooleanField(default=False, help_text='Receive SMS alerts for order updates.')),
                ('user', models.OneToOneField(help_text='The client user this profile belongs to.', limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'db_table': 'client_profile',
            },
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('label', models.CharField(blank=True, default='Home', help_text="Short label: 'Home', 'Office', or 'Mum\\'s place'.", max_length=80)),
                ('full_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('street_address', models.TextField(help_text='Street, house number, landmark.')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='True if this is the primary address shown at checkout.')),
                ('client', models.ForeignKey(help_text='The client profile this address belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='client.clientprofile')),
            ],
            options={
                'verbose_name': 'Client Address',
                'verbose_name_plural': 'Client Addresses',
                'db_table': 'client_address',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['user'], name='client_profile_user_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['country'], name='client_profile_country_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaddress',
            index=models.Index(fields=['client', 'is_default'], name='client_addr_default_idx'),
        ),
    ]
