# Generated by Django 6.0.3 on 2026-05-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='client',
            field=models.ForeignKey(help_text='The client profile this address belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='client_addresses', to='client.clientprofile'),
        ),
    ]
