# Generated by Django 6.0.3 on 2026-06-05 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_clientaddress_id_alter_clientprofile_id'),
        ('measurements', '0004_measurementsharetoken_measurementaccesslog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='ai_style_embedding',
            field=models.JSONField(blank=True, help_text='768-dim style embedding vector for personalised product recommendations.', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='body_type',
            field=models.CharField(blank=True, choices=[('slim', 'Slim'), ('athletic', 'Athletic'), ('curvy', 'Curvy'), ('plus_size', 'Plus Size'), ('petite', 'Petite'), ('tall', 'Tall')], help_text='Body type for fit-based AI recommendations.', max_length=30),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='data_portability_requested_at',
            field=models.DateTimeField(blank=True, help_text='GDPR Article 20 — timestamp of last data portability export request.', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='default_measurement_profile',
            field=models.ForeignKey(blank=True, help_text="The client's active measurement profile for size recommendations.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_clients', to='measurements.measurementprofile'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text='Redeemable loyalty points (100 pts = ₦1).'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='loyalty_tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], db_index=True, default='standard', max_length=12),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='occasion_preferences',
            field=models.JSONField(blank=True, default=list, help_text='Occasion tags: ["wedding", "casual", "office", "traditional"].'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text="Client's unique referral code for inviting friends.", max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='referral_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['loyalty_tier'], name='cp_loyalty_tier_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['referral_code'], name='cp_referral_idx'),
        ),
    ]
