# Generated by Django 6.0.3 on 2026-06-06 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_phase12_vendor_client_2026_scale_fields'),
        ('measurements', '0004_measurementsharetoken_measurementaccesslog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='default_measurement_profile',
            field=models.ForeignKey(blank=True, help_text="The client's active measurement profile for size recommendations.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_measurement_for_clients', to='measurements.measurementprofile'),
        ),
    ]
