# Generated by Django 6.0.3 on 2026-06-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_clientprofile_default_measurement_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of the client's last dashboard activity.", null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text="True if the client's phone number has been verified via OTP."),
        ),
    ]
