# Generated by Django 6.0.3 on 2026-06-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_clientprofile_last_active_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
