# Generated by Django 6.0.3 on 2026-06-28 03:24

import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentConfig',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Environment name can only contain letters, numbers, underscores, and dashes.', regex='^[a-zA-Z0-9_-]+$')], verbose_name='Environment Name')),
                ('environment_type', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production'), ('testing', 'Testing')], max_length=20, verbose_name='Environment Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Environment Config',
                'verbose_name_plural': 'Environment Configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('commit_hash', models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(message='Commit hash must be a 40-character hexadecimal string.', regex='^[a-f0-9]{40}$')], verbose_name='Commit Hash')),
                ('branch', models.CharField(default='main', max_length=100, verbose_name='Branch')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('rollback', 'Rollback')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('deployment_logs', models.TextField(blank=True, verbose_name='Deployment Logs')),
                ('artifacts_url', models.URLField(blank=True, verbose_name='Artifacts URL')),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Deployed By')),
                ('rollback_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollbacks', to='devops.deploymenthistory', verbose_name='Rollback From')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='devops.environmentconfig', verbose_name='Environment')),
            ],
            options={
                'verbose_name': 'Deployment History',
                'verbose_name_plural': 'Deployment Histories',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('endpoint_url', models.URLField(verbose_name='Endpoint URL')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('unknown', 'Unknown')], max_length=20, verbose_name='Status')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='Response Time (ms)')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP Status Code')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Response Data')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Checked At')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='devops.environmentconfig', verbose_name='Environment')),
            ],
            options={
                'verbose_name': 'Health Check',
                'verbose_name_plural': 'Health Checks',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['environment', 'service_name', '-checked_at'], name='devops_heal_environ_36f0a8_idx'), models.Index(fields=['status', '-checked_at'], name='devops_heal_status_738bbc_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecretConfig',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Key name must start with an uppercase letter and only contain uppercase letters, numbers, and underscores.', regex='^[A-Z][A-Z0-9_]*$')], verbose_name='Key Name')),
                ('encrypted_value', encrypted_model_fields.fields.EncryptedTextField(verbose_name='Encrypted Value')),
                ('category', models.CharField(choices=[('database', 'Database'), ('api_key', 'API Key'), ('oauth', 'OAuth'), ('smtp', 'SMTP'), ('sms', 'SMS'), ('payment', 'Payment Gateway'), ('ssl', 'SSL Certificate'), ('encryption', 'Encryption Key'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='devops.environmentconfig', verbose_name='Environment')),
            ],
            options={
                'verbose_name': 'Secret Config',
                'verbose_name_plural': 'Secret Configs',
                'ordering': ['-created_at'],
                'unique_together': {('environment', 'key_name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceMonitoring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('service_type', models.CharField(choices=[('web', 'Web Server'), ('database', 'Database'), ('cache', 'Cache'), ('queue', 'Message Queue'), ('storage', 'Object Storage'), ('proxy', 'Reverse Proxy'), ('monitoring', 'Monitoring'), ('external', 'External Service')], max_length=20, verbose_name='Service Type')),
                ('health_check_url', models.URLField(verbose_name='Health Check URL')),
                ('check_interval', models.PositiveIntegerField(default=300, verbose_name='Check Interval (seconds)')),
                ('timeout', models.PositiveIntegerField(default=30, verbose_name='Timeout (seconds)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('alert_on_failure', models.BooleanField(default=True, verbose_name='Alert On Failure')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_services', to='devops.environmentconfig', verbose_name='Environment')),
            ],
            options={
                'verbose_name': 'Service Monitoring',
                'verbose_name_plural': 'Service Monitorings',
                'ordering': ['service_name'],
                'unique_together': {('environment', 'service_name')},
            },
        ),
    ]
