# Generated by Django 6.0.3 on 2026-06-13 22:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_platform_settings', '0003_alter_platformsettings_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='default_free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Fallback free shipping threshold in NGN. Overridden per product in shipping profiles.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Default Free Shipping Threshold (₦)'),
        ),
    ]
