# Generated by Django 6.0.3 on 2026-06-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_platform_settings', '0004_platformsettings_default_free_shipping_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
