# Generated by Django 6.0.3 on 2026-06-26 03:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_platform_settings', '0005_platformsettings_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='measurement_fee_ngn',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Amount in NGN charged to clients for each precision measurement request.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precision Measurement Fee (₦)'),
        ),
    ]
