# Generated by Django 4.2.7 on 2024-07-19 00:11

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to=userauths.models.user_directory_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
