# Generated by Django 6.0.3 on 2026-06-30 04:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('greeting', 'Greeting'), ('sizing_inquiry', 'Sizing Inquiry'), ('styling_recommendation', 'Styling Recommendation'), ('order_help', 'Order Help'), ('shipping_returns', 'Shipping & Returns'), ('product_info', 'Product Info'), ('farewell', 'Farewell'), ('error', 'Error'), ('unknown', 'Unknown')], max_length=25, verbose_name='Category')),
                ('target_user', models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor'), ('both', 'Both')], default='both', max_length=10, verbose_name='Target User')),
                ('trigger_keywords', models.JSONField(default=list, verbose_name='Trigger Keywords')),
                ('response_text', models.TextField(verbose_name='Response Text')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Response Data')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('priority', models.IntegerField(default=1, help_text='Higher number = higher priority', verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Chatbot Response',
                'verbose_name_plural': 'Chatbot Responses',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='chatbot_cha_categor_7dc9cc_idx'), models.Index(fields=['target_user', 'is_active'], name='chatbot_cha_target__5bce7b_idx'), models.Index(fields=['priority'], name='chatbot_cha_priorit_82e60c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor')], max_length=10, verbose_name='Session Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=10, verbose_name='Status')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Contextual info to maintain conversation state', verbose_name='Context Data')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chatbot Session',
                'verbose_name_plural': 'Chatbot Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_type', models.CharField(choices=[('style_advice', 'Style Advice'), ('size_recommendation', 'Size Recommendation'), ('product_search', 'Product Search'), ('order_inquiry', 'Order Inquiry'), ('general_support', 'General Support'), ('general', 'General')], default='general', max_length=25, verbose_name='Conversation Type')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chatbot.chatbotsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('system', 'System')], max_length=10, verbose_name='Sender Type')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('quick_reply', 'Quick Reply'), ('attachment', 'Attachment'), ('card', 'Card'), ('carousel', 'Carousel'), ('typing', 'Typing')], default='text', max_length=15, verbose_name='Message Type')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Content')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Structured options or response details', verbose_name='Response Data')),
                ('ai_confidence', models.FloatField(blank=True, help_text='Confidence score of AI response (0.0 to 1.0)', null=True, verbose_name='AI Confidence')),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True, verbose_name='Processing Time')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Does the message contain sensitive info?', verbose_name='Is Sensitive')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Edited At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatbotsession',
            index=models.Index(fields=['user', 'status'], name='chatbot_cha_user_id_64f027_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotsession',
            index=models.Index(fields=['session_type', 'status'], name='chatbot_cha_session_3315ba_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotsession',
            index=models.Index(fields=['started_at'], name='chatbot_cha_started_323461_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotsession',
            index=models.Index(fields=['last_activity'], name='chatbot_cha_last_ac_871227_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['session', 'is_active'], name='chatbot_con_session_08f322_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type'], name='chatbot_con_convers_cbbe10_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['started_at'], name='chatbot_con_started_271f80_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chatbot_mes_convers_b353f0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_type', 'created_at'], name='chatbot_mes_sender__6e9fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='chatbot_mes_message_c09c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_sensitive'], name='chatbot_mes_is_sens_a79bfd_idx'),
        ),
    ]
