# Generated by Django 6.0.3 on 2026-04-25 17:12

import django.db.models.deletion
import django.utils.timezone
import uuid6
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('transaction_type', models.CharField(choices=[('order_payment', 'Order Payment'), ('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release'), ('commission', 'Commission'), ('measurement_fee', 'Measurement Fee'), ('vendor_subscription', 'Vendor Subscription'), ('platform_usage_fee', 'Platform Usage Fee'), ('advertisement_fee', 'Advertisement Fee'), ('affiliate_revenue', 'Affiliate Revenue'), ('refund', 'Refund'), ('payout', 'Payout'), ('transfer', 'Transfer'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=30)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal')], db_index=True, default='internal', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('reference', models.CharField(db_index=True, max_length=120, unique=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('order_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('measurement_request_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('from_balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('from_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('to_balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('to_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions_sent', to=settings.AUTH_USER_MODEL)),
                ('from_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_transactions', to='wallet.wallet')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions_received', to=settings.AUTH_USER_MODEL)),
                ('to_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRevenueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('category', models.CharField(choices=[('order_commission', 'Order Commission'), ('measurement_service', 'Measurement Service'), ('vendor_service', 'Vendor Service'), ('advertising', 'Advertising'), ('affiliate', 'Affiliate'), ('adjustment', 'Adjustment')], db_index=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('source_reference', models.CharField(db_index=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.currency')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company_revenue', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionDispute',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='opened', max_length=30)),
                ('reason', models.TextField()),
                ('disputed_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_financial_disputes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionFee',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('fee_type', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionIdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('key', models.CharField(db_index=True, max_length=160, unique=True)),
                ('request_hash', models.CharField(blank=True, default='', max_length=128)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('previous_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, default='', max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5)),
                ('min_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=5)),
                ('max_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('vendor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['vendor_user', 'is_active'], name='transaction_vendor__1c6b17_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_user', '-created_at'], name='transaction_from_us_3e4e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_user', '-created_at'], name='transaction_to_user_68c069_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='transaction_transac_ed11cf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order_id', 'transaction_type'], name='transaction_order_i_fabac5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['idempotency_key'], name='transaction_idempot_68455c_idx'),
        ),
        migrations.AddIndex(
            model_name='companyrevenueentry',
            index=models.Index(fields=['category', '-created_at'], name='transaction_categor_9e03d7_idx'),
        ),
    ]
