# Generated by Django 6.0.3 on 2026-05-11 03:54

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_wave_d_fk_protect_dispute_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrule',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyrevenueentry',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactiondispute',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionidempotencykey',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
    ]
