# Generated by Django 6.0.3 on 2026-04-23 21:39

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, help_text="Django model class name (e.g. 'UnifiedUser').", max_length=100, unique=True)),
                ('app_label', models.CharField(blank=True, default='', help_text="Django app label (e.g. 'authentication').", max_length=100)),
                ('total_created', models.PositiveBigIntegerField(default=0, help_text='Cumulative records ever created. Never decrements.')),
                ('total_active', models.PositiveBigIntegerField(default=0, help_text='Records currently alive (is_deleted=False).')),
                ('total_updated', models.PositiveBigIntegerField(default=0, help_text='Cumulative update (save) operations on existing records. Captures every vendor/client field change.')),
                ('total_soft_deleted', models.PositiveBigIntegerField(default=0, help_text='Records currently soft-deleted (recoverable).')),
                ('total_hard_deleted', models.PositiveBigIntegerField(default=0, help_text='Cumulative permanently purged records. Never decrements.')),
                ('total_records', models.PositiveBigIntegerField(default=0, help_text='Live count of ALL rows in the DB (active + soft-deleted). Decrements on hard-delete. Use for real-time capacity reports.')),
                ('total_lifetime_records', models.PositiveBigIntegerField(default=0, help_text="Monotonically increasing. NEVER decrements. Counts every row ever inserted since first migration — the ultimate source of truth for 'how many X have ever used our platform?'")),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last counter mutation timestamp.')),
            ],
            options={
                'verbose_name': 'Model Analytics',
                'verbose_name_plural': 'Model Analytics',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='CloudinaryProcessedWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, help_text='SHA256(public_id + timestamp + asset_type) — prevents duplicates.', max_length=64, unique=True)),
                ('public_id', models.CharField(db_index=True, help_text='Cloudinary public_id (includes folder path).', max_length=500)),
                ('payload_hash', models.CharField(help_text='SHA256 of the original webhook payload — for validation.', max_length=64)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('unknown', 'Unknown')], db_index=True, help_text='Asset media type (image, video, document).', max_length=30)),
                ('model_target', models.CharField(db_index=True, help_text='Target Django model (avatar, product_image, category_image, etc).', max_length=100)),
                ('model_pk', models.CharField(db_index=True, help_text='PK of the model instance that was updated.', max_length=255)),
                ('secure_url', models.URLField(help_text='Cloudinary secure_url that was saved to the model.', max_length=500)),
                ('success', models.BooleanField(db_index=True, default=True, help_text='Whether webhook processing succeeded.')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed.', null=True)),
                ('processing_time_ms', models.FloatField(default=0.0, help_text='How long webhook processing took (milliseconds).')),
                ('processed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the webhook was received and processed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this audit record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated (should rarely happen).')),
            ],
            options={
                'verbose_name': 'Cloudinary Processed Webhook',
                'verbose_name_plural': 'Cloudinary Processed Webhooks',
                'db_table': 'cloudinary_processed_webhooks',
                'ordering': ['-processed_at'],
                'permissions': [('view_webhook', 'Can view processed webhooks')],
                'indexes': [models.Index(fields=['public_id'], name='cloudinary__public__0d263f_idx'), models.Index(fields=['model_target', 'model_pk'], name='cloudinary__model_t_a2c6be_idx'), models.Index(fields=['asset_type'], name='cloudinary__asset_t_9c0d60_idx'), models.Index(fields=['processed_at'], name='cloudinary__process_0846bc_idx'), models.Index(fields=['-processed_at'], name='cloudinary__process_5f5a02_idx'), models.Index(fields=['success', 'processed_at'], name='cloudinary__success_c8b704_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeletedRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Name of the model that was deleted.', max_length=100)),
                ('record_id', models.CharField(help_text='Primary key of the deleted record (UUID or Int).', max_length=255)),
                ('data', models.JSONField(help_text='Serialized data of the deleted record.')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of deletion.')),
            ],
            options={
                'verbose_name': 'Deleted Record',
                'verbose_name_plural': 'Deleted Records',
                'indexes': [models.Index(fields=['model_name', 'record_id'], name='idx_deleted_model_record')],
            },
        ),
        migrations.CreateModel(
            name='DeletionAuditCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="Django model class name (e.g. 'UnifiedUser').", max_length=100)),
                ('action', models.CharField(choices=[('soft_delete', 'Soft Delete'), ('hard_delete', 'Hard Delete (Permanent)'), ('restore', 'Restore')], help_text='Type of deletion operation.', max_length=20)),
                ('total', models.PositiveBigIntegerField(default=0, help_text='Cumulative count of this action on this model. Atomically incremented — safe under concurrent load.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent increment.')),
            ],
            options={
                'verbose_name': 'Deletion Audit Counter',
                'verbose_name_plural': 'Deletion Audit Counters',
                'ordering': ['model_name', 'action'],
                'indexes': [models.Index(fields=['model_name'], name='idx_del_counter_model')],
                'unique_together': {('model_name', 'action')},
            },
        ),
        migrations.CreateModel(
            name='UserLifecycleRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered.', primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(db_index=True, help_text='UnifiedUser.pk at time of registration. Preserved even after the live account is hard-deleted. UNIQUE: one registry row per user ever created.', unique=True)),
                ('member_id', models.CharField(blank=True, db_index=True, default='', help_text='Fashionistar member ID (e.g. FASTAR000001).', max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email address captured at registration. NOT unique — may be reused after hard-delete.', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, help_text='Phone (E.164 format) captured at registration.', max_length=30, null=True)),
                ('role', models.CharField(blank=True, default='', help_text='User role at registration: admin, vendor, client.', max_length=20)),
                ('auth_provider', models.CharField(blank=True, default='email', help_text='Auth provider: email, google, facebook, apple, etc.', max_length=30)),
                ('country', models.CharField(blank=True, db_index=True, help_text='Country at registration (from profile or IP geo-detection). Use for regional analytics and marketing campaigns.', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State/Province at registration.', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='City at registration.', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="IP address at registration (for geo-detection if user didn't set location).", null=True)),
                ('source', models.CharField(choices=[('web', 'Web Browser'), ('mobile_ios', 'Mobile (iOS)'), ('mobile_android', 'Mobile (Android)'), ('api', 'Direct API')], default='web', help_text='Registration channel: web, mobile_ios, mobile_android, api.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this registry entry was created (~ user registration time).')),
                ('soft_deleted_at', models.DateTimeField(blank=True, help_text='When the live account was soft-deleted. Null if never soft-deleted.', null=True)),
                ('hard_deleted_at', models.DateTimeField(blank=True, help_text='When the live account was permanently purged. Null if still in DB. Set even if account was previously soft-deleted.', null=True)),
                ('restored_at', models.DateTimeField(blank=True, help_text='Most recent restore timestamp (soft-delete reversed).', null=True)),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful login.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('soft_deleted', 'Soft Deleted (Recoverable)'), ('hard_deleted', 'Hard Deleted (Permanent)')], db_index=True, default='active', help_text='Current lifecycle state of the user account.', max_length=20)),
                ('total_logins', models.PositiveBigIntegerField(default=0, help_text='Cumulative successful login count. Never decrements.')),
            ],
            options={
                'verbose_name': 'User Lifecycle Registry',
                'verbose_name_plural': 'User Lifecycle Registry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_uuid'], name='idx_ulr_user_uuid'), models.Index(fields=['email'], name='idx_ulr_email'), models.Index(fields=['phone'], name='idx_ulr_phone'), models.Index(fields=['country'], name='idx_ulr_country'), models.Index(fields=['status'], name='idx_ulr_status'), models.Index(fields=['created_at'], name='idx_ulr_created')],
            },
        ),
    ]
