# Generated by Django 6.0.2 on 2026-03-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, help_text="Django model class name (e.g. 'UnifiedUser').", max_length=100, unique=True)),
                ('app_label', models.CharField(blank=True, default='', help_text="Django app label (e.g. 'authentication').", max_length=100)),
                ('total_created', models.PositiveBigIntegerField(default=0, help_text='Cumulative records ever created. Never decrements.')),
                ('total_active', models.PositiveBigIntegerField(default=0, help_text='Records currently alive (is_deleted=False).')),
                ('total_updated', models.PositiveBigIntegerField(default=0, help_text='Cumulative update (save) operations on existing records. Captures every vendor/client field change.')),
                ('total_soft_deleted', models.PositiveBigIntegerField(default=0, help_text='Records currently soft-deleted (recoverable).')),
                ('total_hard_deleted', models.PositiveBigIntegerField(default=0, help_text='Cumulative permanently purged records. Never decrements.')),
                ('total_records', models.PositiveBigIntegerField(default=0, help_text='Live count of ALL rows in the DB (active + soft-deleted). Decrements on hard-delete. Use for real-time capacity reports.')),
                ('total_lifetime_records', models.PositiveBigIntegerField(default=0, help_text="Monotonically increasing. NEVER decrements. Counts every row ever inserted since first migration — the ultimate source of truth for 'how many X have ever used our platform?'")),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last counter mutation timestamp.')),
            ],
            options={
                'verbose_name': 'Model Analytics',
                'verbose_name_plural': 'Model Analytics',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='DeletedRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Name of the model that was deleted.', max_length=100)),
                ('record_id', models.CharField(help_text='Primary key of the deleted record (UUID or Int).', max_length=255)),
                ('data', models.JSONField(help_text='Serialized data of the deleted record.')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of deletion.')),
            ],
            options={
                'verbose_name': 'Deleted Record',
                'verbose_name_plural': 'Deleted Records',
                'indexes': [models.Index(fields=['model_name', 'record_id'], name='idx_deleted_model_record')],
            },
        ),
        migrations.CreateModel(
            name='DeletionAuditCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="Django model class name (e.g. 'UnifiedUser').", max_length=100)),
                ('action', models.CharField(choices=[('soft_delete', 'Soft Delete'), ('hard_delete', 'Hard Delete (Permanent)'), ('restore', 'Restore')], help_text='Type of deletion operation.', max_length=20)),
                ('total', models.PositiveBigIntegerField(default=0, help_text='Cumulative count of this action on this model. Atomically incremented — safe under concurrent load.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent increment.')),
            ],
            options={
                'verbose_name': 'Deletion Audit Counter',
                'verbose_name_plural': 'Deletion Audit Counters',
                'ordering': ['model_name', 'action'],
                'indexes': [models.Index(fields=['model_name'], name='idx_del_counter_model')],
                'unique_together': {('model_name', 'action')},
            },
        ),
    ]
