# Generated by Django 6.0.2 on 2026-02-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletedrecords',
            options={'verbose_name': 'Deleted Record', 'verbose_name_plural': 'Deleted Records'},
        ),
        migrations.RenameIndex(
            model_name='deletedrecords',
            new_name='idx_deleted_model_record',
            old_name='common_dele_model_n_c49967_idx',
        ),
    ]
