# Generated by Django 6.0.2 on 2026-03-14 20:27

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLifecycleRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered.', primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(db_index=True, help_text='UnifiedUser.pk at time of registration. Preserved even after the live account is hard-deleted.')),
                ('member_id', models.CharField(blank=True, db_index=True, default='', help_text='Fashionistar member ID (e.g. FASTAR000001).', max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email address captured at registration. NOT unique — may be reused after hard-delete.', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, help_text='Phone (E.164 format) captured at registration.', max_length=30, null=True)),
                ('role', models.CharField(blank=True, default='', help_text='User role at registration: admin, vendor, client.', max_length=20)),
                ('auth_provider', models.CharField(blank=True, default='email', help_text='Auth provider: email, google, facebook, apple, etc.', max_length=30)),
                ('country', models.CharField(blank=True, db_index=True, help_text='Country at registration (from profile or IP geo-detection). Use for regional analytics and marketing campaigns.', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State/Province at registration.', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='City at registration.', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="IP address at registration (for geo-detection if user didn't set location).", null=True)),
                ('source', models.CharField(choices=[('web', 'Web Browser'), ('mobile_ios', 'Mobile (iOS)'), ('mobile_android', 'Mobile (Android)'), ('api', 'Direct API')], default='web', help_text='Registration channel: web, mobile_ios, mobile_android, api.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this registry entry was created (~ user registration time).')),
                ('soft_deleted_at', models.DateTimeField(blank=True, help_text='When the live account was soft-deleted. Null if never soft-deleted.', null=True)),
                ('hard_deleted_at', models.DateTimeField(blank=True, help_text='When the live account was permanently purged. Null if still in DB. Set even if account was previously soft-deleted.', null=True)),
                ('restored_at', models.DateTimeField(blank=True, help_text='Most recent restore timestamp (soft-delete reversed).', null=True)),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful login.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('soft_deleted', 'Soft Deleted (Recoverable)'), ('hard_deleted', 'Hard Deleted (Permanent)')], db_index=True, default='active', help_text='Current lifecycle state of the user account.', max_length=20)),
                ('total_logins', models.PositiveBigIntegerField(default=0, help_text='Cumulative successful login count. Never decrements.')),
            ],
            options={
                'verbose_name': 'User Lifecycle Registry',
                'verbose_name_plural': 'User Lifecycle Registry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_uuid'], name='idx_ulr_user_uuid'), models.Index(fields=['email'], name='idx_ulr_email'), models.Index(fields=['phone'], name='idx_ulr_phone'), models.Index(fields=['country'], name='idx_ulr_country'), models.Index(fields=['status'], name='idx_ulr_status'), models.Index(fields=['created_at'], name='idx_ulr_created')],
            },
        ),
    ]
