# Generated by Django 6.0.3 on 2026-05-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlifecycleregistry',
            name='country',
            field=models.CharField(blank=True, db_index=True, help_text='Country at registration (from profile or IP geo-detection).', max_length=100, null=True),
        ),
    ]
