# Generated by Django 6.0.2 on 2026-02-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_deletedrecords_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionAuditCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="Django model class name (e.g. 'UnifiedUser').", max_length=100)),
                ('action', models.CharField(choices=[('soft_delete', 'Soft Delete'), ('hard_delete', 'Hard Delete (Permanent)'), ('restore', 'Restore')], help_text='Type of deletion operation.', max_length=20)),
                ('total', models.PositiveBigIntegerField(default=0, help_text='Cumulative count of this action on this model. Atomically incremented — safe under concurrent load.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent increment.')),
            ],
            options={
                'verbose_name': 'Deletion Audit Counter',
                'verbose_name_plural': 'Deletion Audit Counters',
                'ordering': ['model_name', 'action'],
                'indexes': [models.Index(fields=['model_name'], name='idx_del_counter_model')],
                'unique_together': {('model_name', 'action')},
            },
        ),
    ]
