# Generated by Django 6.0.3 on 2026-03-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_user_lifecycle_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlifecycleregistry',
            name='user_uuid',
            field=models.UUIDField(db_index=True, help_text='UnifiedUser.pk at time of registration. Preserved even after the live account is hard-deleted. UNIQUE: one registry row per user ever created.', unique=True),
        ),
    ]
