# Generated by Django 6.0.3 on 2026-06-22 17:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_userlifecycleregistry_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlowPerformanceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Log ID')),
                ('metric_id', models.CharField(db_index=True, help_text='Unique browser-generated metric ID (from web-vitals library). Used to deduplicate multiple readings for the same navigation.', max_length=128, verbose_name='Metric ID')),
                ('metric_name', models.CharField(db_index=True, help_text='Core Web Vital name: LCP, FID, CLS, INP, TTFB, FCP.', max_length=10, verbose_name='Metric Name')),
                ('metric_value', models.FloatField(help_text='Measured value. Units: ms for time-based metrics; unitless for CLS.', verbose_name='Metric Value')),
                ('page_path', models.CharField(help_text="URL path where the metric was measured, e.g., '/' or '/products/agbada-senator'.", max_length=512, verbose_name='Page Path')),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser UA string. Used to correlate slow metrics with specific browser families.', verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Anonymized or hashed in production. Retained for 30 days per GDPR Article 5.', null=True, verbose_name='Client IP Address')),
                ('logged_at', models.DateTimeField(db_index=True, help_text='Timestamp when the SLA breach was recorded server-side.', verbose_name='Logged At')),
            ],
            options={
                'verbose_name': 'Slow Performance Audit Log',
                'verbose_name_plural': 'Slow Performance Audit Logs',
                'db_table': 'common_slow_performance_audit_log',
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['metric_name', 'logged_at'], name='telemetry_metric_logged_idx'), models.Index(fields=['page_path', 'logged_at'], name='telemetry_page_logged_idx')],
            },
        ),
    ]
