# Generated by Django 6.0.2 on 2026-02-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_deletionauditcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, help_text="Django model class name (e.g. 'UnifiedUser').", max_length=100, unique=True)),
                ('app_label', models.CharField(blank=True, default='', help_text="Django app label (e.g. 'authentication').", max_length=100)),
                ('total_created', models.PositiveBigIntegerField(default=0, help_text='Cumulative records ever created. Never decrements.')),
                ('total_active', models.PositiveBigIntegerField(default=0, help_text='Records currently alive (is_deleted=False).')),
                ('total_soft_deleted', models.PositiveBigIntegerField(default=0, help_text='Records currently soft-deleted (recoverable).')),
                ('total_hard_deleted', models.PositiveBigIntegerField(default=0, help_text='Cumulative permanently purged records. Never decrements.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last counter mutation timestamp.')),
            ],
            options={
                'verbose_name': 'Model Analytics',
                'verbose_name_plural': 'Model Analytics',
                'ordering': ['model_name'],
            },
        ),
    ]
