# Generated by Django 6.0.2 on 2026-02-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_modelanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelanalytics',
            name='total_updated',
            field=models.PositiveBigIntegerField(default=0, help_text='Cumulative update (save) operations on existing records. Captures every vendor/client field change.'),
        ),
    ]
