# Generated by Django 6.0.3 on 2026-03-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_add_cloudinary_processed_webhook'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cloudinaryprocessedwebhook',
            new_name='cloudinary__public__0d263f_idx',
            old_name='cloudinary_p_public_d73d8c_idx',
        ),
        migrations.RenameIndex(
            model_name='cloudinaryprocessedwebhook',
            new_name='cloudinary__model_t_a2c6be_idx',
            old_name='cloudinary_p_model_t_e1a2f3_idx',
        ),
        migrations.RenameIndex(
            model_name='cloudinaryprocessedwebhook',
            new_name='cloudinary__asset_t_9c0d60_idx',
            old_name='cloudinary_p_asset_t_b4c5d6_idx',
        ),
        migrations.RenameIndex(
            model_name='cloudinaryprocessedwebhook',
            new_name='cloudinary__process_0846bc_idx',
            old_name='cloudinary_p_proceed_a7b8c9_idx',
        ),
        migrations.RenameIndex(
            model_name='cloudinaryprocessedwebhook',
            new_name='cloudinary__process_5f5a02_idx',
            old_name='cloudinary_p_proceed_d1e2f3_idx',
        ),
        migrations.RenameIndex(
            model_name='cloudinaryprocessedwebhook',
            new_name='cloudinary__success_c8b704_idx',
            old_name='cloudinary_p_success_g4h5i6_idx',
        ),
    ]
