# Generated by Django 6.0.2 on 2026-02-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_modelanalytics_total_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelanalytics',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Model Analytics', 'verbose_name_plural': 'Model Analytics'},
        ),
        migrations.AddField(
            model_name='modelanalytics',
            name='total_lifetime_records',
            field=models.PositiveBigIntegerField(default=0, help_text="Monotonically increasing. NEVER decrements. Counts every row ever inserted since first migration — the ultimate source of truth for 'how many X have ever used our platform?'"),
        ),
        migrations.AddField(
            model_name='modelanalytics',
            name='total_records',
            field=models.PositiveBigIntegerField(default=0, help_text='Live count of ALL rows in the DB (active + soft-deleted). Decrements on hard-delete. Use for real-time capacity reports.'),
        ),
    ]
