# Generated by Django 6.0.3 on 2026-05-08 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy ✅'), ('degraded', 'Degraded ⚠️'), ('unhealthy', 'Unhealthy ❌')], default='unknown', help_text='Last recorded health check result for this provider.', max_length=20, verbose_name='Health Status')),
                ('last_health_check', models.DateTimeField(blank=True, null=True, verbose_name='Last Health Check')),
                ('circuit_state', models.CharField(choices=[('closed', 'Closed (Normal)'), ('open', 'Open (Provider Failing — Switch Required)'), ('half_open', 'Half-Open (Probing)')], default='closed', help_text='OPEN means the provider is currently failing. Switch to another provider and save to reset the circuit.', max_length=20, verbose_name='Circuit State')),
                ('failure_count', models.PositiveSmallIntegerField(default=0, help_text='Resets to 0 when the provider call succeeds.', verbose_name='Consecutive Failure Count')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Failure Timestamp')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_backend', models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP (Gmail / Custom)'), ('django.core.mail.backends.console.EmailBackend', 'Console (Dev Only)'), ('anymail.backends.sendgrid.EmailBackend', 'SendGrid'), ('anymail.backends.mailgun.EmailBackend', 'Mailgun'), ('zoho_zeptomail.backend.zeptomail_backend.ZohoZeptoMailEmailBackend', 'Zoho ZeptoMail'), ('anymail.backends.brevo.EmailBackend', 'Brevo (Sendinblue)')], db_index=True, default='django.core.mail.backends.smtp.EmailBackend', help_text='Choose the transactional email backend used by the platform. SMTP (Gmail) is acceptable for development or low-volume flows. Production environments should use Mailgun, SendGrid, Zoho ZeptoMail, or Brevo.', max_length=250, verbose_name='Active Email Backend')),
            ],
            options={
                'verbose_name': 'Email Provider Configuration',
                'verbose_name_plural': 'Email Provider Configuration',
                'indexes': [models.Index(fields=['email_backend'], name='prov_email_backend_idx')],
            },
        ),
        migrations.CreateModel(
            name='KYCProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy ✅'), ('degraded', 'Degraded ⚠️'), ('unhealthy', 'Unhealthy ❌')], default='unknown', help_text='Last recorded health check result for this provider.', max_length=20, verbose_name='Health Status')),
                ('last_health_check', models.DateTimeField(blank=True, null=True, verbose_name='Last Health Check')),
                ('circuit_state', models.CharField(choices=[('closed', 'Closed (Normal)'), ('open', 'Open (Provider Failing — Switch Required)'), ('half_open', 'Half-Open (Probing)')], default='closed', help_text='OPEN means the provider is currently failing. Switch to another provider and save to reset the circuit.', max_length=20, verbose_name='Circuit State')),
                ('failure_count', models.PositiveSmallIntegerField(default=0, help_text='Resets to 0 when the provider call succeeds.', verbose_name='Consecutive Failure Count')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Failure Timestamp')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_slug', models.CharField(choices=[('smileid', 'Smile Identity (Biometric + BVN/NIN)'), ('dojah', 'Dojah (BVN / NIN Nigeria-Native)'), ('youverify', 'Youverify (Identity + Document Check)')], db_index=True, default='dojah', help_text='Select the active KYC identity verification provider. Switch here when rotating providers without redeploying.', max_length=30, verbose_name='KYC Provider')),
                ('api_key', models.CharField(blank=True, default='', help_text='Primary API key or Application ID for the selected provider.', max_length=512, verbose_name='API Key / App ID')),
                ('api_secret', models.CharField(blank=True, default='', help_text='API secret or private key. Leave blank if not required by the provider.', max_length=512, verbose_name='API Secret / Private Key')),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='HMAC signing secret for validating inbound KYC provider webhook callbacks. Required for idempotent webhook processing.', max_length=512, verbose_name='Webhook Secret')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text="Provider-specific JSON extras. Examples: {'partner_id': 'xxx'} for Smile ID, {'account_id': 'yyy'} for Youverify.", verbose_name='Extra Configuration')),
                ('base_url', models.URLField(blank=True, default='', help_text="Leave blank to use the provider's default production URL. Set to the sandbox URL when sandbox_mode=True.", max_length=500, verbose_name='API Base URL Override')),
                ('sandbox_mode', models.BooleanField(default=True, help_text='When enabled, all KYC requests are routed to the provider sandbox. Disable only after live credentials have been validated end-to-end.', verbose_name='Sandbox / Test Mode')),
                ('webhook_idempotency_ttl_seconds', models.PositiveIntegerField(default=86400, help_text='Time window for deduplicating repeated webhook deliveries for the same provider_reference. Default: 86400 (24 hours).', verbose_name='Webhook Idempotency TTL (seconds)')),
            ],
            options={
                'verbose_name': 'KYC Provider Configuration',
                'verbose_name_plural': 'KYC Provider Configuration',
                'indexes': [models.Index(fields=['provider_slug'], name='prov_kyc_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy ✅'), ('degraded', 'Degraded ⚠️'), ('unhealthy', 'Unhealthy ❌')], default='unknown', help_text='Last recorded health check result for this provider.', max_length=20, verbose_name='Health Status')),
                ('last_health_check', models.DateTimeField(blank=True, null=True, verbose_name='Last Health Check')),
                ('circuit_state', models.CharField(choices=[('closed', 'Closed (Normal)'), ('open', 'Open (Provider Failing — Switch Required)'), ('half_open', 'Half-Open (Probing)')], default='closed', help_text='OPEN means the provider is currently failing. Switch to another provider and save to reset the circuit.', max_length=20, verbose_name='Circuit State')),
                ('failure_count', models.PositiveSmallIntegerField(default=0, help_text='Resets to 0 when the provider call succeeds.', verbose_name='Consecutive Failure Count')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Failure Timestamp')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sms_backend', models.CharField(choices=[('apps.providers.SMS.twilio.TwilioSMSProvider', 'Twilio (Global / Robust)'), ('apps.providers.SMS.termii.TermiiSMSProvider', 'Termii (Nigeria-Focused)'), ('apps.providers.SMS.bulksmsNG.BulksmsNGSMSProvider', 'BulkSMS Nigeria (Cost Effective)')], db_index=True, default='apps.providers.SMS.twilio.TwilioSMSProvider', help_text='Choose the active SMS provider class for the system. NOTE: Ensure the corresponding API credentials (Keys/Secrets) are correctly set in your Server Environment Variables before switching.', max_length=250, verbose_name='Active SMS Provider')),
            ],
            options={
                'verbose_name': 'SMS Provider Configuration',
                'verbose_name_plural': 'SMS Provider Configuration',
                'indexes': [models.Index(fields=['sms_backend'], name='prov_sms_backend_idx')],
            },
        ),
    ]
