# Generated by Django 6.0.3 on 2026-05-09 04:50

import apps.providers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_add_cloudinary_mirrorsize_fix_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailproviderconfig',
            name='api_key',
            field=apps.providers.fields.EncryptedCharField(blank=True, default='', help_text='Optional provider API key stored encrypted for API-backed email providers.', max_length=512, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='api_secret',
            field=apps.providers.fields.EncryptedCharField(blank=True, default='', help_text='Optional provider API secret stored encrypted when required.', max_length=512, verbose_name='API Secret'),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='extra_config',
            field=apps.providers.fields.EncryptedJSONField(blank=True, default=dict, help_text='Provider-specific metadata such as region, domain, tags, or account IDs.', verbose_name='Extra Configuration'),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='sender_email',
            field=models.EmailField(blank=True, default='', help_text='Optional from-address override for this provider.', max_length=254, verbose_name='Sender Email Override'),
        ),
        migrations.AddField(
            model_name='smsproviderconfig',
            name='api_key',
            field=apps.providers.fields.EncryptedCharField(blank=True, default='', help_text='Encrypted SMS provider API key/token. Used before environment fallback.', max_length=512, verbose_name='API Key / Token'),
        ),
        migrations.AddField(
            model_name='smsproviderconfig',
            name='api_secret',
            field=apps.providers.fields.EncryptedCharField(blank=True, default='', help_text='Encrypted SMS provider API secret when the selected provider requires one.', max_length=512, verbose_name='API Secret'),
        ),
        migrations.AddField(
            model_name='smsproviderconfig',
            name='extra_config',
            field=apps.providers.fields.EncryptedJSONField(blank=True, default=dict, help_text='Provider-specific metadata such as route, channel, region, or DND policy.', verbose_name='Extra Configuration'),
        ),
        migrations.AddField(
            model_name='smsproviderconfig',
            name='sender_id',
            field=models.CharField(blank=True, default='', help_text='Provider sender ID, short code, or phone number override.', max_length=80, verbose_name='Sender ID / From Number'),
        ),
        migrations.AlterField(
            model_name='kycproviderconfig',
            name='api_key',
            field=apps.providers.fields.EncryptedCharField(blank=True, default='', help_text='Primary API key or Application ID for the selected provider.', max_length=512, verbose_name='API Key / App ID'),
        ),
        migrations.AlterField(
            model_name='kycproviderconfig',
            name='api_secret',
            field=apps.providers.fields.EncryptedCharField(blank=True, default='', help_text='API secret or private key. Leave blank if not required by the provider.', max_length=512, verbose_name='API Secret / Private Key'),
        ),
        migrations.AlterField(
            model_name='kycproviderconfig',
            name='extra_config',
            field=apps.providers.fields.EncryptedJSONField(blank=True, default=dict, help_text="Provider-specific JSON extras. Examples: {'partner_id': 'xxx'} for Smile ID, {'account_id': 'yyy'} for Youverify.", verbose_name='Extra Configuration'),
        ),
        migrations.AlterField(
            model_name='kycproviderconfig',
            name='webhook_secret',
            field=apps.providers.fields.EncryptedCharField(blank=True, default='', help_text='HMAC signing secret for validating inbound KYC provider webhook callbacks. Required for idempotent webhook processing.', max_length=512, verbose_name='Webhook Secret'),
        ),
    ]
