# Generated by Django 6.0.3 on 2026-05-11 03:54

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_provider_credentials_admin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinaryproviderconfig',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailproviderconfig',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kycproviderconfig',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mirrorsizeproviderconfig',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='smsproviderconfig',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
    ]
