# Generated by Django 6.0.3 on 2026-06-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_cloudinaryproviderconfig_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudinaryproviderconfig',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='kycproviderconfig',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='mirrorsizeproviderconfig',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='smsproviderconfig',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
