# Generated by Django 6.0.3 on 2026-06-26 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_cloudinaryproviderconfig_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MirrorSizeProviderConfig',
        ),
    ]
