# Generated by Django 6.0.3 on 2026-07-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_delete_mirrorsizeproviderconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsproviderconfig',
            name='sms_backend',
            field=models.CharField(choices=[('apps.providers.SMS.termii.TermiiSMSProvider', 'Termii (Nigerian-first)'), ('apps.providers.SMS.twilio.TwilioSMSProvider', 'Twilio (Global / WhatsApp)'), ('apps.providers.SMS.bulksmsNG.BulksmsNGSMSProvider', 'BulkSMS Nigeria'), ('apps.providers.SMS.kudi.KudiSMSProvider', 'Kudi SMS')], db_index=True, default='apps.providers.SMS.twilio.TwilioSMSProvider', help_text='Choose the active SMS provider class for the system. NOTE: Ensure the corresponding API credentials (Keys/Secrets) are correctly set in your Server Environment Variables before switching.', max_length=250, verbose_name='Active SMS Provider'),
        ),
    ]
