# Generated by Django 6.0.3 on 2026-04-27 22:17

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_payment_confirmed', 'Payment Confirmed'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_refunded', 'Order Refunded'), ('vendor_approved', 'Vendor Approved'), ('vendor_rejected', 'Vendor Rejected'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('payout_initiated', 'Payout Initiated'), ('payout_completed', 'Payout Completed'), ('escrow_released', 'Escrow Released'), ('new_message', 'New Message'), ('chat_offer', 'Chat Offer'), ('measurement_requested', 'Measurement Requested'), ('system_alert', 'System Alert'), ('promo', 'Promotional'), ('review_reminder', 'Review Reminder'), ('wishlist_price_drop', 'Wishlist Price Drop')], db_index=True, max_length=60, unique=True)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS')], default='in_app', max_length=10)),
                ('title_template', models.CharField(max_length=200)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'unique_together': {('notification_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_payment_confirmed', 'Payment Confirmed'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_refunded', 'Order Refunded'), ('vendor_approved', 'Vendor Approved'), ('vendor_rejected', 'Vendor Rejected'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('payout_initiated', 'Payout Initiated'), ('payout_completed', 'Payout Completed'), ('escrow_released', 'Escrow Released'), ('new_message', 'New Message'), ('chat_offer', 'Chat Offer'), ('measurement_requested', 'Measurement Requested'), ('system_alert', 'System Alert'), ('promo', 'Promotional'), ('review_reminder', 'Review Reminder'), ('wishlist_price_drop', 'Wishlist Price Drop')], db_index=True, max_length=60)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS')], db_index=True, default='in_app', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Context data for this notification. E.g. {'order_id': '...', 'order_number': 'FSN-ORD-ABC'}.")),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=300)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('failed', models.BooleanField(default=False)),
                ('error_msg', models.TextField(blank=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='SET_NULL: notification preserved after account deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='idx_notif_recipient_read'), models.Index(fields=['notification_type', 'channel'], name='idx_notif_type_channel'), models.Index(fields=['created_at'], name='idx_notif_created_at')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_payment_confirmed', 'Payment Confirmed'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_refunded', 'Order Refunded'), ('vendor_approved', 'Vendor Approved'), ('vendor_rejected', 'Vendor Rejected'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('payout_initiated', 'Payout Initiated'), ('payout_completed', 'Payout Completed'), ('escrow_released', 'Escrow Released'), ('new_message', 'New Message'), ('chat_offer', 'Chat Offer'), ('measurement_requested', 'Measurement Requested'), ('system_alert', 'System Alert'), ('promo', 'Promotional'), ('review_reminder', 'Review Reminder'), ('wishlist_price_drop', 'Wishlist Price Drop')], max_length=60)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'unique_together': {('user', 'notification_type', 'channel')},
            },
        ),
    ]
