# Generated by Django 6.0.3 on 2026-05-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_payment_confirmed', 'Payment Confirmed'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_refunded', 'Order Refunded'), ('custom_order_accepted', 'Custom Order Accepted'), ('custom_order_rejected', 'Custom Order Rejected'), ('vendor_approved', 'Vendor Approved'), ('vendor_rejected', 'Vendor Rejected'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('payout_initiated', 'Payout Initiated'), ('payout_completed', 'Payout Completed'), ('escrow_released', 'Escrow Released'), ('new_message', 'New Message'), ('chat_offer', 'Chat Offer'), ('measurement_requested', 'Measurement Requested'), ('system_alert', 'System Alert'), ('promo', 'Promotional'), ('review_reminder', 'Review Reminder'), ('wishlist_price_drop', 'Wishlist Price Drop'), ('tracking_id_added', 'Tracking ID Added'), ('tracking_id_changed', 'Tracking ID Changed')], db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_payment_confirmed', 'Payment Confirmed'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_refunded', 'Order Refunded'), ('custom_order_accepted', 'Custom Order Accepted'), ('custom_order_rejected', 'Custom Order Rejected'), ('vendor_approved', 'Vendor Approved'), ('vendor_rejected', 'Vendor Rejected'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('payout_initiated', 'Payout Initiated'), ('payout_completed', 'Payout Completed'), ('escrow_released', 'Escrow Released'), ('new_message', 'New Message'), ('chat_offer', 'Chat Offer'), ('measurement_requested', 'Measurement Requested'), ('system_alert', 'System Alert'), ('promo', 'Promotional'), ('review_reminder', 'Review Reminder'), ('wishlist_price_drop', 'Wishlist Price Drop'), ('tracking_id_added', 'Tracking ID Added'), ('tracking_id_changed', 'Tracking ID Changed')], max_length=60),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_payment_confirmed', 'Payment Confirmed'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_refunded', 'Order Refunded'), ('custom_order_accepted', 'Custom Order Accepted'), ('custom_order_rejected', 'Custom Order Rejected'), ('vendor_approved', 'Vendor Approved'), ('vendor_rejected', 'Vendor Rejected'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('payout_initiated', 'Payout Initiated'), ('payout_completed', 'Payout Completed'), ('escrow_released', 'Escrow Released'), ('new_message', 'New Message'), ('chat_offer', 'Chat Offer'), ('measurement_requested', 'Measurement Requested'), ('system_alert', 'System Alert'), ('promo', 'Promotional'), ('review_reminder', 'Review Reminder'), ('wishlist_price_drop', 'Wishlist Price Drop'), ('tracking_id_added', 'Tracking ID Added'), ('tracking_id_changed', 'Tracking ID Changed')], db_index=True, max_length=60, unique=True),
        ),
    ]
