# Generated by Django 6.0.3 on 2026-06-05 19:42

import django.db.models.deletion
import uuid
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Batch ID')),
                ('title', models.CharField(help_text="E.g. 'June 2026 Summer Sale Blast'.", max_length=200, verbose_name='Internal Title')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_payment_confirmed', 'Payment Confirmed'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_refunded', 'Order Refunded'), ('custom_order_accepted', 'Custom Order Accepted'), ('custom_order_rejected', 'Custom Order Rejected'), ('vendor_approved', 'Vendor Approved'), ('vendor_rejected', 'Vendor Rejected'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('payout_initiated', 'Payout Initiated'), ('payout_completed', 'Payout Completed'), ('escrow_released', 'Escrow Released'), ('new_message', 'New Message'), ('chat_offer', 'Chat Offer'), ('measurement_requested', 'Measurement Requested'), ('system_alert', 'System Alert'), ('promo', 'Promotional'), ('review_reminder', 'Review Reminder'), ('wishlist_price_drop', 'Wishlist Price Drop'), ('tracking_id_added', 'Tracking ID Added'), ('tracking_id_changed', 'Tracking ID Changed')], db_index=True, max_length=60, verbose_name='Notification Type')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS')], default='in_app', max_length=10, verbose_name='Channel')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='Role slugs to fan out to. Empty list = all active users.', verbose_name='Target Roles')),
                ('template_context', models.JSONField(blank=True, default=dict, help_text='Shared context dict for template rendering.', verbose_name='Template Context')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='Total Recipients')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Sent Count')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Failed Count')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=10, verbose_name='Status')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='Null = immediate dispatch on approval.', null=True, verbose_name='Scheduled At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_batches', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Notification Batch',
                'verbose_name_plural': 'Notification Batches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='nb_status_sched_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationReadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('read_at', models.DateTimeField(db_index=True, verbose_name='Read At')),
                ('device_id', models.CharField(blank=True, db_index=True, help_text='Client device fingerprint for multi-device tracking.', max_length=128, verbose_name='Device ID')),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='Anonymized after 30 days per GDPR data minimization.', null=True, verbose_name='Client IP')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='notification.notification', verbose_name='Notification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_read_receipts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Read Receipt',
                'verbose_name_plural': 'Notification Read Receipts',
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['notification', 'user'], name='nrr_notif_user_idx'), models.Index(fields=['user', 'read_at'], name='nrr_user_read_idx')],
                'unique_together': {('notification', 'user', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('platform', models.CharField(choices=[('fcm', 'Firebase Cloud Messaging (Android/Web)'), ('apns', 'Apple Push Notification Service (iOS)'), ('web', 'Web Push (VAPID)')], db_index=True, max_length=5, verbose_name='Platform')),
                ('device_id', models.CharField(db_index=True, help_text='Client-generated UUID. Used for idempotent token upsert.', max_length=128, verbose_name='Device ID')),
                ('token', models.TextField(help_text='FCM registration token or APNs device token.', verbose_name='Push Token')),
                ('device_name', models.CharField(blank=True, help_text='Human-readable label, e.g. "My iPhone 15".', max_length=200, verbose_name='Device Name')),
                ('app_version', models.CharField(blank=True, max_length=30, verbose_name='App Version')),
                ('os_version', models.CharField(blank=True, max_length=30, verbose_name='OS Version')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False = token invalidated. Pruned by cleanup task.', verbose_name='Active')),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Used At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Push Device',
                'verbose_name_plural': 'Push Devices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'is_active'], name='pd_platform_active_idx'), models.Index(fields=['user', 'is_active'], name='pd_user_active_idx'), models.Index(fields=['last_used_at'], name='pd_last_used_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
