# Generated by Django 6.0.3 on 2026-05-04 22:14

import django.core.validators
import django.db.models.deletion
import uuid6
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial_order_domain'),
        ('product', '0003_phase1_enterprise_expansion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('sku_snapshot', models.CharField(blank=True, help_text='Product SKU at time of order. Preserved for returns/exchanges.', max_length=80)),
                ('title_snapshot', models.CharField(help_text='Product title at time of order.', max_length=300)),
                ('variant_snapshot', models.CharField(blank=True, help_text="Variant label (e.g. 'Red / XL') at time of order.", max_length=200)),
                ('cover_image_url', models.URLField(blank=True, help_text='Cloudinary URL of product cover image at order time.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price snapshot from CartItem at checkout.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveIntegerField(help_text='Quantity ordered.')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='unit_price × quantity, frozen at placement.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Platform commission % at time of order. Used for vendor payout calc.', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='commission_rate / 100 × line_total, frozen at placement.', max_digits=12)),
                ('vendor_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='line_total - commission_amount, frozen at placement.', max_digits=12)),
                ('size_snapshot', models.CharField(blank=True, max_length=80)),
                ('color_snapshot', models.CharField(blank=True, max_length=80)),
                ('cart_item_idempotency_key', models.UUIDField(blank=True, help_text='Original CartItem.idempotency_key. Enables dedup on retry.', null=True)),
                ('order', models.ForeignKey(help_text='Parent order. CASCADE: snapshot deleted with order if hard-deleted.', on_delete=django.db.models.deletion.CASCADE, related_name='cart_order_items', to='order.order')),
                ('product', models.ForeignKey(blank=True, help_text='SET_NULL: snapshot preserved if product is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_order_snapshots', to='product.product')),
                ('variant', models.ForeignKey(blank=True, help_text='SET_NULL: snapshot preserved if variant is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_order_snapshots', to='product.productvariant')),
            ],
            options={
                'verbose_name': 'Cart Order Item',
                'verbose_name_plural': 'Cart Order Items',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order', 'product'], name='idx_cart_order_item_order_prod')],
            },
        ),
    ]
