# Generated by Django 6.0.3 on 2026-05-11 03:54

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_decimal_min_value_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderidempotencyrecord',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
    ]
