# Generated by Django 6.0.3 on 2026-05-16 15:32

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cartorderitem_id_alter_order_id_and_more'),
        ('payment', '0005_alter_paymentintent_id_alter_paymentprovider_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active_payment_path',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('gateway', 'Gateway'), ('cod', 'Cash On Delivery'), ('pay_at_shop', 'Pay At Shop')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_outstanding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_payment_mode_snapshot',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('cod', 'Cash On Delivery'), ('pay_at_shop', 'Pay At Shop'), ('both', 'Both')], default='disabled', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(choices=[('platform_courier', 'Platform Courier'), ('vendor_shop_pickup', 'Vendor Shop Pickup'), ('cod', 'Cash On Delivery')], default='platform_courier', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='final_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='first_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='percent_paid_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_confirmed', 'Payment Confirmed'), ('awaiting_cash_confirmation', 'Awaiting Cash Confirmation'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refund_requested', 'Refund Requested'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_index=True, default='pending_payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_confirmed', 'Payment Confirmed'), ('awaiting_cash_confirmation', 'Awaiting Cash Confirmation'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refund_requested', 'Refund Requested'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], max_length=30),
        ),
        migrations.CreateModel(
            name='OrderPaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('sequence_number', models.PositiveIntegerField()),
                ('payment_source', models.CharField(choices=[('wallet', 'Wallet'), ('gateway', 'Gateway'), ('cod_commitment', 'COD Commitment'), ('pay_at_shop_commitment', 'Pay At Shop Commitment'), ('manual_adjustment', 'Manual Adjustment'), ('refund', 'Refund')], max_length=30)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('selected_percent', models.PositiveSmallIntegerField()),
                ('applied_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('cumulative_amount_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cumulative_percent_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remaining_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_final_payment', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField()),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment_record_actor', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='order.order')),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment_records', to='payment.paymentintent')),
            ],
            options={
                'verbose_name': 'Order Payment Record',
                'verbose_name_plural': 'Order Payment Records',
                'ordering': ['sequence_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderCommercialTransitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('transition_type', models.CharField(choices=[('payment_initialized', 'Payment Initialized'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('commitment_created', 'Commitment Created'), ('commitment_confirmed', 'Commitment Confirmed'), ('wallet_credited', 'Wallet Credited'), ('escrow_held', 'Escrow Held'), ('escrow_released', 'Escrow Released'), ('refund_issued', 'Refund Issued'), ('delivery_mode_selected', 'Delivery Mode Selected'), ('courier_assigned', 'Courier Assigned'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('vendor_shop_collected', 'Vendor Shop Collected'), ('cod_confirmed', 'COD Confirmed'), ('order_completed', 'Order Completed'), ('dispute_opened', 'Dispute Opened')], max_length=40)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(blank=True, default='', max_length=30)),
                ('delivery_mode', models.CharField(blank=True, choices=[('platform_courier', 'Platform Courier'), ('vendor_shop_pickup', 'Vendor Shop Pickup'), ('cod', 'Cash On Delivery')], default='', max_length=30)),
                ('cash_payment_mode_snapshot', models.CharField(choices=[('disabled', 'Disabled'), ('cod', 'Cash On Delivery'), ('pay_at_shop', 'Pay At Shop'), ('both', 'Both')], default='disabled', max_length=20)),
                ('selected_percent', models.PositiveSmallIntegerField(default=0)),
                ('cumulative_percent_paid', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount_delta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actor_role', models.CharField(blank=True, default='', max_length=40)),
                ('occurred_at', models.DateTimeField()),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_commercial_transition_actor', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_transition_logs', to='order.order')),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_transition_logs', to='payment.paymentintent')),
                ('payment_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_transitions', to='order.orderpaymentrecord')),
            ],
            options={
                'verbose_name': 'Order Commercial Transition Log',
                'verbose_name_plural': 'Order Commercial Transition Logs',
                'ordering': ['occurred_at', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='orderpaymentrecord',
            constraint=models.UniqueConstraint(fields=('order', 'sequence_number'), name='uq_order_payment_record_sequence'),
        ),
    ]
