# Generated by Django 6.0.3 on 2026-05-26 13:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_active_payment_path_order_amount_outstanding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, help_text='Human-readable reference e.g. CO-20260526-0001', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Vendor'), ('approved', 'Vendor Approved'), ('in_production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], db_index=True, default='draft', max_length=20)),
                ('design_brief', models.TextField(help_text="Detailed description of the client's custom design requirements.")),
                ('reference_images', models.JSONField(blank=True, default=list, help_text='List of uploaded image URLs for style reference.')),
                ('product_snapshot_id', models.CharField(blank=True, default='', help_text='Product PID used as style reference.', max_length=255)),
                ('order_snapshot_id', models.CharField(blank=True, default='', help_text='Existing order_number used as style reference.', max_length=255)),
                ('budget_ngn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Client's proposed budget in NGN.", max_digits=14)),
                ('agreed_amount_ngn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Agreed total set by vendor on approval.', max_digits=14)),
                ('vendor_approval_note', models.TextField(blank=True, default='', help_text="Vendor's note when approving/declining the design brief.")),
                ('client', models.ForeignKey(help_text='The client who initiated the commission.', limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='custom_orders_as_client', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text='The vendor fulfilling the commission.', limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.PROTECT, related_name='custom_orders_as_vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Order',
                'verbose_name_plural': 'Custom Orders',
                'db_table': 'custom_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomOrderMilestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_pct', models.PositiveSmallIntegerField(help_text='Percentage of total order this milestone covers: 30, 50, 70, or 100.')),
                ('amount_ngn', models.DecimalField(decimal_places=2, help_text='NGN amount for this tranche.', max_digits=14)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('waived', 'Waived')], db_index=True, default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, default='', help_text='External payment provider reference.', max_length=255)),
                ('custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='order.customorder')),
            ],
            options={
                'verbose_name': 'Custom Order Milestone',
                'verbose_name_plural': 'Custom Order Milestones',
                'db_table': 'custom_order_milestone',
                'ordering': ['milestone_pct'],
            },
        ),
        migrations.AddIndex(
            model_name='customorder',
            index=models.Index(fields=['client', 'status'], name='co_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customorder',
            index=models.Index(fields=['vendor', 'status'], name='co_vendor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customorder',
            index=models.Index(fields=['reference'], name='co_reference_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customordermilestone',
            unique_together={('custom_order', 'milestone_pct')},
        ),
    ]
