# Generated by Django 6.0.3 on 2026-05-26 17:21 — handcrafted with SeparateDatabaseAndState
"""
Migration 0009 for apps.order:

The CustomOrder / CustomOrderMilestone models have been extracted to the
dedicated apps.custom_order Django application. This migration tells Django's
migration state to stop tracking those models in apps.order, WITHOUT touching
the physical database tables (which live at `custom_order` and
`custom_order_milestone` and are now managed by apps.custom_order.0001).

SeparateDatabaseAndState ensures zero DDL is executed.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_custom_order_milestone_flow"),
        # custom_order 0001 must run first so Django state knows where the
        # models now live before we remove them from the order state.
        ("custom_order", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # State operations: remove the old model tracking from apps.order
            state_operations=[
                migrations.RemoveIndex(
                    model_name="customorder",
                    name="co_client_status_idx",
                ),
                migrations.RemoveIndex(
                    model_name="customorder",
                    name="co_vendor_status_idx",
                ),
                migrations.RemoveIndex(
                    model_name="customorder",
                    name="co_reference_idx",
                ),
                migrations.RemoveField(
                    model_name="customorder",
                    name="client",
                ),
                migrations.RemoveField(
                    model_name="customorder",
                    name="vendor",
                ),
                migrations.DeleteModel(
                    name="CustomOrderMilestone",
                ),
                migrations.DeleteModel(
                    name="CustomOrder",
                ),
            ],
            # Database operations: nothing — tables are managed by apps.custom_order
            database_operations=[],
        ),
    ]
