# Generated by Django 6.0.3 on 2026-06-05 15:15

import django.core.validators
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_customorder_co_client_status_idx_and_more'),
        ('vendor', '0005_add_vendor_bank_account_and_kyc_legal_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('code', models.CharField(db_index=True, help_text='Case-insensitive coupon code, e.g. FASHION20.', max_length=50, unique=True, verbose_name='Code')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('free_shipping', 'Free Shipping'), ('bogo', 'Buy One Get One Free')], db_index=True, max_length=15, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='% value for PERCENTAGE type, NGN amount for FIXED type.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Value')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on percentage discounts in NGN. Leave blank for no cap.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max Discount Amount (NGN)')),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Order Value (NGN)')),
                ('valid_from', models.DateTimeField(db_index=True, verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(db_index=True, verbose_name='Valid Until')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited.', verbose_name='Max Total Uses')),
                ('max_uses_per_user', models.PositiveIntegerField(default=0, help_text='0 = unlimited.', verbose_name='Max Uses Per User')),
                ('current_uses', models.PositiveIntegerField(default=0, help_text='Atomically incremented on each redemption.', verbose_name='Current Total Uses')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_first_order_only', models.BooleanField(default=False, help_text='Restrict this code to clients with no previous orders.', verbose_name='First Order Only')),
                ('description', models.TextField(blank=True, help_text='Admin/internal note about this campaign.', verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='UTM params, campaign IDs, or A/B test labels.', verbose_name='Metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discount_codes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('vendor', models.ForeignKey(blank=True, help_text='Null = platform-wide discount.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_codes', to='vendor.vendorprofile', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='dc_code_idx'), models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='dc_active_validity_idx'), models.Index(fields=['vendor', 'is_active'], name='dc_vendor_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('reason', models.CharField(choices=[('not_received', 'Item Not Received'), ('not_as_described', 'Item Not as Described'), ('quality_issue', 'Quality Issue'), ('wrong_item', 'Wrong Item Sent'), ('measurement_mismatch', 'Measurement Mismatch'), ('late_delivery', 'Late Delivery'), ('vendor_unresponsive', 'Vendor Unresponsive'), ('other', 'Other')], db_index=True, max_length=25, verbose_name='Reason')),
                ('description', models.TextField(verbose_name='Description')),
                ('client_evidence', models.JSONField(blank=True, default=list, help_text='List of Cloudinary public_ids uploaded by the client.', verbose_name='Client Evidence')),
                ('vendor_evidence', models.JSONField(blank=True, default=list, help_text='List of Cloudinary public_ids uploaded by the vendor.', verbose_name='Vendor Evidence')),
                ('status', models.CharField(choices=[('open', 'Open'), ('vendor_responded', 'Vendor Responded'), ('under_review', 'Under Moderator Review'), ('resolved_buyer', 'Resolved — Buyer Wins'), ('resolved_vendor', 'Resolved — Vendor Wins'), ('escalated', 'Escalated to Senior Moderator'), ('closed', 'Closed Without Resolution')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('resolution_outcome', models.CharField(blank=True, choices=[('open', 'Open'), ('vendor_responded', 'Vendor Responded'), ('under_review', 'Under Moderator Review'), ('resolved_buyer', 'Resolved — Buyer Wins'), ('resolved_vendor', 'Resolved — Vendor Wins'), ('escalated', 'Escalated to Senior Moderator'), ('closed', 'Closed Without Resolution')], help_text='Write-once — set only on final resolution.', max_length=20, verbose_name='Resolution Outcome')),
                ('resolution_note', models.TextField(blank=True, help_text="Moderator's reasoning for the resolution decision.", verbose_name='Resolution Note')),
                ('escrow_held', models.BooleanField(default=True, help_text='True = funds locked in escrow during dispute.', verbose_name='Escrow Held')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to refund to client if resolved in their favour.', max_digits=14, null=True, verbose_name='Refund Amount')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('sla_deadline', models.DateTimeField(blank=True, help_text='Platform-enforced resolution deadline (typically 7 days).', null=True, verbose_name='SLA Deadline')),
                ('assigned_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Moderator')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_disputes', to=settings.AUTH_USER_MODEL, verbose_name='Opened By')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Dispute',
                'verbose_name_plural': 'Order Disputes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='od_status_created_idx'), models.Index(fields=['assigned_moderator', 'status'], name='od_mod_status_idx'), models.Index(fields=['sla_deadline', 'status'], name='od_sla_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('from_status', models.CharField(blank=True, help_text='Status snapshot BEFORE this transition.', max_length=30, verbose_name='Previous Status')),
                ('to_status', models.CharField(db_index=True, help_text='Status snapshot AFTER this transition.', max_length=30, verbose_name='New Status')),
                ('actor_role', models.CharField(blank=True, help_text="Snapshot of actor's primary role at transition time.", max_length=30, verbose_name='Actor Role')),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Actor IP')),
                ('note', models.TextField(blank=True, help_text='Staff/system commentary visible in the admin timeline.', verbose_name='Note')),
                ('is_system_event', models.BooleanField(default=False, help_text='True if triggered by Celery task, webhook, or cron.', verbose_name='System Event')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Carrier updates, webhook payloads, or other context.', verbose_name='Metadata')),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered transition. Null = system/Celery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_timeline_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Timeline Event',
                'verbose_name_plural': 'Order Timeline Events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='otl_order_created_idx'), models.Index(fields=['to_status', 'created_at'], name='otl_status_created_idx')],
            },
        ),
    ]
