# Generated by Django 6.0.3 on 2026-06-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_discountcode_orderdispute_ordertimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carbon_offset_purchased',
            field=models.BooleanField(default=False, help_text='Customer opted into carbon offset at checkout. ₦200 surcharge routed to sustainability fund.'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_service',
            field=models.CharField(blank=True, help_text="Courier company name (e.g. 'DHL', 'GIG Logistics', 'Kwik'). Shown to customer.", max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_at',
            field=models.DateTimeField(blank=True, help_text='Precise delivery timestamp (replaces date-only estimated_delivery). Used for real-time delivery countdown on order detail page.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_message',
            field=models.CharField(blank=True, help_text='Message printed on the gift note. Only used when is_gift=True.', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='is_gift',
            field=models.BooleanField(default=False, help_text='Customer flagged this order as a gift. Suppresses price on packing slip.'),
        ),
    ]
