# Generated by Django 6.0.3 on 2026-06-14 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_2026_scale_fields'),
        ('product', '0020_consolidate_product_variant_gallery_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='SET_NULL: snapshot preserved if variant is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_order_variant_snapshots', to='product.productvariantgallerymedia'),
        ),
    ]
