# Generated by Django 6.0.3 on 2026-06-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_consolidate_product_variant_gallery_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('custom', 'Custom (Tailor-made)')], default='delivery', max_length=20),
        ),
    ]
