# Generated by Django 6.0.3 on 2026-06-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_fulfillment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='ordercommercialtransitionlog',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='orderidempotencyrecord',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='orderpaymentrecord',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='ordertimeline',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
