# Generated by Django 6.0.3 on 2026-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial_support_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('order_dispute', 'Order Dispute'), ('payment_issue', 'Payment Issue'), ('product_complaint', 'Product Complaint'), ('vendor_conduct', 'Vendor Conduct'), ('delivery_problem', 'Delivery Problem'), ('refund_request', 'Refund Request'), ('measurement_issue', 'Measurement Issue'), ('general', 'General Inquiry')], db_index=True, default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Arbitrary context for this ticket. E.g. {'order_number': 'FASTAR-ORD-ABC', 'product_slug': 'silk-gown'}."),
        ),
    ]
