# Generated by Django 6.0.3 on 2026-06-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_supportticket_id_alter_ticketescalation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='ticketescalation',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
