# Generated by Django 6.0.3 on 2026-04-27 22:17

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementProfile',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('name', models.CharField(default='My Measurements', help_text="Profile label, e.g. 'Slim Fit', 'Maternity', 'Gym Build'.", max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text="Mark as the user's default profile for checkout gating.")),
                ('unit', models.CharField(choices=[('cm', 'Centimetres'), ('inch', 'Inches')], default='cm', max_length=4)),
                ('bust', models.DecimalField(blank=True, decimal_places=2, help_text='Bust/chest circumference (cm).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('waist', models.DecimalField(blank=True, decimal_places=2, help_text='Natural waist circumference (cm).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('hips', models.DecimalField(blank=True, decimal_places=2, help_text='Hip circumference at the fullest point (cm).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('shoulder_width', models.DecimalField(blank=True, decimal_places=2, help_text='Shoulder seam to seam across the back (cm).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('neck', models.DecimalField(blank=True, decimal_places=2, help_text='Neck base circumference (cm).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('inseam', models.DecimalField(blank=True, decimal_places=2, help_text='Inseam length (cm).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('thigh', models.DecimalField(blank=True, decimal_places=2, help_text='Thigh circumference at the fullest point (cm).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('knee', models.DecimalField(blank=True, decimal_places=2, help_text='Knee circumference (cm).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ankle', models.DecimalField(blank=True, decimal_places=2, help_text='Ankle circumference (cm).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('arm_length', models.DecimalField(blank=True, decimal_places=2, help_text='Arm length from shoulder to wrist (cm).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('bicep', models.DecimalField(blank=True, decimal_places=2, help_text='Bicep circumference at the fullest point (cm).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('wrist', models.DecimalField(blank=True, decimal_places=2, help_text='Wrist circumference (cm).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Total height (cm).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms (for fabric allowance).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('reference_photo', cloudinary.models.CloudinaryField(blank=True, help_text='Full-body reference photo for measurement verification. Uploaded via Cloudinary direct-upload two-phase flow.', max_length=255, null=True, verbose_name='reference_photo')),
                ('is_verified', models.BooleanField(default=False, help_text='Set by admin/vendor after manually validating measurements. Some vendors may require verified profiles for high-end custom orders.')),
                ('notes', models.TextField(blank=True, help_text="Optional notes from client or tailor (e.g. 'prefer relaxed fit').")),
                ('owner', models.ForeignKey(help_text='The client who owns this measurement profile.', on_delete=django.db.models.deletion.CASCADE, related_name='measurement_profiles', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Staff user who verified this measurement profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Measurement Profile',
                'verbose_name_plural': 'Measurement Profiles',
                'ordering': ['-is_default', '-updated_at'],
                'indexes': [models.Index(fields=['owner', 'is_default'], name='idx_measure_owner_default')],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
