# Generated by Django 6.0.3 on 2026-05-08 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementprofile',
            name='owner',
            field=models.ForeignKey(help_text='The client who owns this measurement profile.', on_delete=django.db.models.deletion.CASCADE, related_name='client_measurement_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
