# Generated by Django 6.0.3 on 2026-06-05 14:08

import django.db.models.deletion
import uuid
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_measurementprofile_id'),
        ('product', '0012_productdraftsession'),
        ('vendor', '0005_add_vendor_bank_account_and_kyc_legal_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementShareToken',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('fields_allowed', models.JSONField(default=list, help_text='Subset of MeasurementProfile field names the client consented to share. E.g. ["bust", "waist", "hips"]', verbose_name='Fields Allowed')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_revoked', models.BooleanField(db_index=True, default=False, verbose_name='Revoked')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('revoked_reason', models.CharField(blank=True, max_length=200, verbose_name='Revocation Reason')),
                ('accessed_count', models.PositiveIntegerField(default=0, verbose_name='Access Count')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Accessed At')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_measurement_shares', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='measurements.measurementprofile', verbose_name='Measurement Profile')),
                ('vendor', models.ForeignKey(blank=True, help_text='Null = public link valid for any vendor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_measurement_tokens', to='vendor.vendorprofile', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Measurement Share Token',
                'verbose_name_plural': 'Measurement Share Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('accessor_ip', models.GenericIPAddressField(verbose_name='Accessor IP')),
                ('accessed_fields', models.JSONField(default=list, help_text='Fields actually served during this access.', verbose_name='Accessed Fields')),
                ('access_purpose', models.TextField(blank=True, help_text="Self-declared purpose by the accessor's system.", verbose_name='Access Purpose')),
                ('retention_expires_at', models.DateTimeField(help_text='Auto-set to created_at + 3 years at save time.', verbose_name='Retention Expires At')),
                ('accessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Accessor')),
                ('share_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='measurements.measurementsharetoken', verbose_name='Share Token')),
            ],
            options={
                'verbose_name': 'Measurement Access Log',
                'verbose_name_plural': 'Measurement Access Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SizeRecommendationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('recommended_size', models.CharField(blank=True, max_length=10, verbose_name='Recommended Size')),
                ('confidence', models.FloatField(blank=True, help_text='0.0 = low confidence, 1.0 = high confidence.', null=True, verbose_name='Confidence')),
                ('fit_notes', models.JSONField(blank=True, default=dict, help_text='Per-field fit commentary. E.g. {"bust": "relaxed_fit", "waist": "true_to_size"}', verbose_name='Fit Notes')),
                ('alternative_sizes', models.JSONField(blank=True, default=list, help_text='Ordered alternative size options with confidence and notes.', verbose_name='Alternative Sizes')),
                ('reasoning', models.TextField(blank=True, help_text='Plain English explanation from the AI model.', verbose_name='Reasoning')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10, verbose_name='Status')),
                ('model_version', models.CharField(blank=True, help_text='ML model version for reproducibility audit.', max_length=50, verbose_name='Model Version')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('error_message', models.TextField(blank=True, help_text='Set on FAILED status.', verbose_name='Error Message')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_recommendation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('measurement_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_recommendation_requests', to='measurements.measurementprofile', verbose_name='Measurement Profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_recommendation_requests', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Size Recommendation Request',
                'verbose_name_plural': 'Size Recommendation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BodyScanSession',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Session ID')),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10, verbose_name='Device Type')),
                ('scan_provider', models.CharField(choices=[('mirrorsize', 'MirrorSize'), ('manual', 'Manual Entry'), ('ai_camera', 'AI Camera')], max_length=12, verbose_name='Scan Provider')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12, verbose_name='Status')),
                ('raw_data_url', models.CharField(blank=True, help_text='Provider or Cloudinary URL for raw scan data.', max_length=500, verbose_name='Raw Data URL')),
                ('scan_confidence', models.FloatField(blank=True, help_text='Provider confidence score 0.0–1.0.', null=True, verbose_name='Scan Confidence')),
                ('extracted_measurements', models.JSONField(blank=True, default=dict, help_text='JSON dict matching MeasurementProfile field names.', verbose_name='Extracted Measurements')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Processing Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User Agent')),
                ('measurement_profile', models.ForeignKey(blank=True, help_text='Created after COMPLETED scan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_scans', to='measurements.measurementprofile', verbose_name='Measurement Profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Body Scan Session',
                'verbose_name_plural': 'Body Scan Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='scan_owner_status_idx'), models.Index(fields=['status', 'created_at'], name='scan_status_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='measurementsharetoken',
            index=models.Index(fields=['token'], name='mst_token_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementsharetoken',
            index=models.Index(fields=['vendor', 'is_revoked'], name='mst_vendor_revoked_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementsharetoken',
            index=models.Index(fields=['profile', 'is_revoked'], name='mst_profile_revoked_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementsharetoken',
            index=models.Index(fields=['expires_at', 'is_revoked'], name='mst_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementaccesslog',
            index=models.Index(fields=['accessor', 'created_at'], name='mal_accessor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementaccesslog',
            index=models.Index(fields=['share_token', 'created_at'], name='mal_token_created_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementaccesslog',
            index=models.Index(fields=['retention_expires_at'], name='mal_retention_idx'),
        ),
        migrations.AddIndex(
            model_name='sizerecommendationrequest',
            index=models.Index(fields=['client', 'status'], name='srr_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sizerecommendationrequest',
            index=models.Index(fields=['product', 'status'], name='srr_product_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sizerecommendationrequest',
            index=models.Index(fields=['measurement_profile', 'product'], name='srr_profile_product_idx'),
        ),
    ]
