# Generated by Django 6.0.3 on 2026-06-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_measurementsharetoken_measurementaccesslog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyscansession',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='measurementaccesslog',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='measurementprofile',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='measurementsharetoken',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='sizerecommendationrequest',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
