# Generated by Django 6.0.3 on 2026-06-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_bodyscansession_active_measurementaccesslog_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyscansession',
            name='scan_provider',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera')], max_length=12, verbose_name='Scan Provider'),
        ),
    ]
