# Generated by Django 6.0.3 on 2026-07-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0008_add_ai_engine_version_and_scan_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementprofile',
            name='ai_scan_confidence',
            field=models.FloatField(blank=True, default=None, help_text='MediaPipe pose confidence score (0.0–1.0) at scan time. Profiles below MEASUREMENT_MIN_CONFIDENCE (default: 0.65) are rejected and never stored.', null=True, verbose_name='Scan Confidence'),
        ),
    ]
