# Generated by Antigravity — 2026-07-18
# TASK-052: Add measurement_url + qr_code_url to BodyScanSession
#
# These fields support the device-aware measurement routing (Phase 2 of SONET-4.6):
#   - measurement_url: full frontend URL for cross-device QR handoff
#   - qr_code_url:     Cloudinary URL of the persisted QR PNG
#
# Both are additive (blank=True) — no data migration, zero risk to existing rows.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0009_add_ai_engine_version_and_scan_confidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodyscansession",
            name="measurement_url",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="Measurement URL",
                help_text=(
                    "Full frontend URL for this scan session. "
                    "Used to generate the QR code and for cross-device handoff."
                ),
            ),
        ),
        migrations.AddField(
            model_name="bodyscansession",
            name="qr_code_url",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="QR Code URL",
                help_text="Cloudinary URL of the persisted QR code PNG for this session.",
            ),
        ),
    ]
