# Generated by Django 6.0.3
# Migration 0011: Add default="" to MeasurementProfile.notes
# The notes column already exists (added in 0001_initial.py with blank=True).
# This migration adds the Python-level default so new instances get ""
# instead of NULL, hardening the API against missing notes in POST payloads.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0010_bodyscansession_qr_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurementprofile",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional notes from client or tailor (e.g. 'prefer relaxed fit').",
            ),
        ),
    ]
