# Generated by Django 6.0.3 on 2026-05-26 17:21 — handcrafted with SeparateDatabaseAndState
"""
Migration 0002 for apps.custom_order.

This migration reconciles the difference between the migration-0001 state
snapshot (taken from apps.order.0008) and the current apps.custom_order model
definition.

Database operations performed:
  - Add columns deleted_at, is_deleted, transaction_ref to custom_order_milestone
    (these are genuinely new columns not present in the DB yet)

State-only operations (no DDL — help_text / FK target adjustments):
  - All AlterField operations that only change metadata, help_text, or
    FK target from AUTH_USER_MODEL (still same integer column in DB).

The vendor FK change from AUTH_USER_MODEL → VendorProfile is a state-only
change here because the physical column (vendor_id integer) is the same;
no constraint rename is performed on the live database.
"""
import django.db.models.deletion
import uuid6
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_order", "0001_initial"),
        ("order", "0009_remove_customorder_co_client_status_idx_and_more"),
        ("vendor", "0005_add_vendor_bank_account_and_kyc_legal_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── Database: add genuinely new columns ───────────────────────────────
        migrations.AddField(
            model_name="customordermilestone",
            name="deleted_at",
            field=models.DateTimeField(blank=True, help_text="Timestamp of soft deletion.", null=True),
        ),
        migrations.AddField(
            model_name="customordermilestone",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, help_text="Flag indicating if the record is soft-deleted."),
        ),
        migrations.AddField(
            model_name="customordermilestone",
            name="transaction_ref",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        # ── State-only: AlterField to sync metadata and FK targets ────────────
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="customorder",
                    name="agreed_amount_ngn",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), help_text="Agreed total set by vendor on approval.", max_digits=14),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="budget_ngn",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), help_text="Client's proposed budget in NGN.", max_digits=14),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="client",
                    field=models.ForeignKey(help_text="The client who initiated the commission.", limit_choices_to={"role": "client"}, on_delete=django.db.models.deletion.PROTECT, related_name="custom_orders_as_client", to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="created_at",
                    field=models.DateTimeField(auto_now_add=True, db_index=True, help_text="Timestamp when the record was created."),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="deleted_at",
                    field=models.DateTimeField(blank=True, help_text="Timestamp of soft deletion.", null=True),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="design_brief",
                    field=models.TextField(help_text="Detailed description of the client's custom design requirements."),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="id",
                    field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text="UUID7 — globally unique, time-ordered primary key.", primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="is_deleted",
                    field=models.BooleanField(db_index=True, default=False, help_text="Flag indicating if the record is soft-deleted."),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="order_snapshot_id",
                    field=models.CharField(blank=True, default="", help_text="Existing order_number used as style reference.", max_length=255),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="product_snapshot_id",
                    field=models.CharField(blank=True, default="", help_text="Product PID used as style reference.", max_length=255),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="reference",
                    field=models.CharField(blank=True, editable=False, help_text="Human-readable reference e.g. CO-20260526-0001", max_length=30, unique=True),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="reference_images",
                    field=models.JSONField(blank=True, default=list, help_text="List of uploaded image URLs for style reference."),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True, help_text="Timestamp when the record was last updated."),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="vendor",
                    field=models.ForeignKey(help_text="The vendor fulfilling the commission.", limit_choices_to={"role": "vendor"}, on_delete=django.db.models.deletion.PROTECT, related_name="custom_orders_as_vendor", to="vendor.vendorprofile"),
                ),
                migrations.AlterField(
                    model_name="customorder",
                    name="vendor_approval_note",
                    field=models.TextField(blank=True, default="", help_text="Vendor's note when approving/declining the design brief."),
                ),
                migrations.AlterField(
                    model_name="customordermilestone",
                    name="amount_ngn",
                    field=models.DecimalField(decimal_places=2, help_text="NGN amount for this tranche.", max_digits=14),
                ),
                migrations.AlterField(
                    model_name="customordermilestone",
                    name="created_at",
                    field=models.DateTimeField(auto_now_add=True, db_index=True, help_text="Timestamp when the record was created."),
                ),
                migrations.AlterField(
                    model_name="customordermilestone",
                    name="id",
                    field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text="UUID7 — globally unique, time-ordered primary key.", primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name="customordermilestone",
                    name="milestone_pct",
                    field=models.PositiveSmallIntegerField(help_text="Percentage of total order this milestone covers: 30, 50, 70, or 100."),
                ),
                migrations.AlterField(
                    model_name="customordermilestone",
                    name="payment_reference",
                    field=models.CharField(blank=True, default="", help_text="External payment provider reference.", max_length=255),
                ),
                migrations.AlterField(
                    model_name="customordermilestone",
                    name="payment_status",
                    field=models.CharField(choices=[("pending", "Pending"), ("paid", "Paid"), ("failed", "Failed"), ("waived", "Waived")], db_index=True, default="pending", max_length=12),
                ),
                migrations.AlterField(
                    model_name="customordermilestone",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True, help_text="Timestamp when the record was last updated."),
                ),
            ],
            database_operations=[],  # All AlterFields above are metadata-only
        ),
    ]
