# Generated by Django 6.0.3 on 2026-06-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0003_reconcile_legacy_custom_order_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='customordermilestone',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
