# Generated by Django 6.0.3 on 2026-06-28 06:03

import django.db.models.deletion
import uuid
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0030_product_active_productcommissionsnapshot_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBChangeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Event ID')),
                ('app_label', models.CharField(db_index=True, max_length=50, verbose_name='App Label')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='Model Name')),
                ('object_id', models.CharField(help_text='Primary key of the changed object, stored as string.', max_length=200, verbose_name='Object ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], default='updated', max_length=10, verbose_name='Event Type')),
                ('is_processed', models.BooleanField(db_index=True, default=False, verbose_name='Processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('celery_task_id', models.CharField(blank=True, max_length=200, verbose_name='Celery Task ID')),
            ],
            options={
                'verbose_name': 'DB Change Event',
                'verbose_name_plural': 'DB Change Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_processed', 'created_at'], name='ai_dbc_pending_idx'), models.Index(fields=['app_label', 'model_name'], name='ai_dbc_model_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('image_vector', models.JSONField(blank=True, help_text='marqo-FashionSigLIP image embedding (512d). L2-normalized.', null=True, verbose_name='Image Vector')),
                ('text_vector', models.JSONField(blank=True, help_text='marqo-FashionSigLIP text embedding (512d). L2-normalized.', null=True, verbose_name='Text Vector')),
                ('combined_vector', models.JSONField(blank=True, help_text='Weighted average: 60% image + 40% text (512d). Primary vector used for similarity search.', null=True, verbose_name='Combined Vector')),
                ('model_version', models.CharField(default='marqo-FashionSigLIP-B-16', max_length=100, verbose_name='Model Version')),
                ('last_embedded_at', models.DateTimeField(auto_now=True, verbose_name='Last Embedded At')),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('embedded', 'Embedded'), ('failed', 'Failed'), ('skipped', 'Skipped — No Image')], db_index=True, default='pending', max_length=20, verbose_name='Embedding Status')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Embedding',
                'verbose_name_plural': 'Product Embeddings',
                'ordering': ['-last_embedded_at'],
                'indexes': [models.Index(fields=['embedding_status'], name='ai_pe_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_type', models.CharField(choices=[('measurement', 'Measurement'), ('recommendation', 'Recommendation'), ('analytics', 'Analytics'), ('ingestion', 'DB Ingestion'), ('embedding', 'Product Embedding'), ('size_reasoning', 'LLM Size Reasoning')], db_index=True, max_length=20, verbose_name='Workflow Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], db_index=True, default='pending', max_length=10, verbose_name='Status')),
                ('input_snapshot', models.JSONField(blank=True, default=dict, help_text='Sanitized workflow input. No raw image bytes.', verbose_name='Input Snapshot')),
                ('output_snapshot', models.JSONField(blank=True, default=dict, help_text='Final workflow output (measurements, recommendations, insights).', verbose_name='Output Snapshot')),
                ('error_detail', models.TextField(blank=True, help_text='Exception traceback on FAILED status.', verbose_name='Error Detail')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (ms)')),
                ('model_version', models.CharField(blank=True, help_text='AI model version for reproducibility audit.', max_length=100, verbose_name='Model Version')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Celery Task ID')),
                ('user', models.ForeignKey(blank=True, help_text='Null for system-triggered workflows (e.g., analytics cron).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_workflow_executions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Workflow Execution',
                'verbose_name_plural': 'Workflow Executions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_type', 'status'], name='ai_wf_type_status_idx'), models.Index(fields=['user', 'workflow_type'], name='ai_wf_user_type_idx'), models.Index(fields=['created_at'], name='ai_wf_created_idx')],
            },
        ),
    ]
