# Generated by Django 6.0.3 on 2026-07-01 01:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_add_pgvector_hnsw_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productembedding',
            name='combined_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, help_text='Weighted average: 60% image + 40% text (512d). Primary vector used for similarity search.', null=True, verbose_name='Combined Vector'),
        ),
        migrations.AlterField(
            model_name='productembedding',
            name='image_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, help_text='marqo-FashionSigLIP image embedding (512d). L2-normalized.', null=True, verbose_name='Image Vector'),
        ),
        migrations.AlterField(
            model_name='productembedding',
            name='text_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, help_text='marqo-FashionSigLIP text embedding (512d). L2-normalized.', null=True, verbose_name='Text Vector'),
        ),
    ]
