# Generated by Django 6.0.3 on 2026-04-25 17:12

import django.db.models.deletion
import django.utils.timezone
import uuid6
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('symbol', models.CharField(default='₦', max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('exchange_rate_usd', models.DecimalField(decimal_places=8, default=Decimal('1.00000000'), max_digits=20)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('owner_type', models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor'), ('support', 'Support'), ('editor', 'Editor'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('company', 'Fashionistar Company')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('account_number', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('account_name', models.CharField(blank=True, default='', max_length=160)),
                ('bank_name', models.CharField(blank=True, default='Fashionistar Wallet', max_length=120)),
                ('provider', models.CharField(blank=True, default='internal', max_length=40)),
                ('provider_account_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('escrow_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('frozen', 'Frozen'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('is_default', models.BooleanField(default=True)),
                ('pin_hash', models.CharField(blank=True, default='', max_length=255)),
                ('pin_set_at', models.DateTimeField(blank=True, null=True)),
                ('failed_pin_attempts', models.PositiveSmallIntegerField(default=0)),
                ('pin_locked_until', models.DateTimeField(blank=True, null=True)),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('daily_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('monthly_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('last_daily_reset', models.DateField(default=django.utils.timezone.localdate)),
                ('last_monthly_reset', models.DateField(default=django.utils.timezone.localdate)),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='wallet.currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletHold',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('released_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('reference', models.CharField(db_index=True, max_length=120, unique=True)),
                ('order_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'owner_type'], name='wallet_wall_user_id_75f5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['owner_type', 'status'], name='wallet_wall_owner_t_328efc_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['currency', 'status'], name='wallet_wall_currenc_9b9a42_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'owner_type', 'currency', 'is_default'), name='wallet_unique_default_user_role_currency'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_type', 'company'), ('user__isnull', True)), fields=('owner_type', 'currency', 'is_default'), name='wallet_unique_company_currency'),
        ),
        migrations.AddIndex(
            model_name='wallethold',
            index=models.Index(fields=['wallet', 'status'], name='wallet_wall_wallet__354f88_idx'),
        ),
        migrations.AddIndex(
            model_name='wallethold',
            index=models.Index(fields=['order_id', 'status'], name='wallet_wall_order_i_8265e1_idx'),
        ),
    ]
