# Generated by Django 6.0.3 on 2026-06-05 15:15

import django.db.models.deletion
import uuid
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_discountcode_orderdispute_ordertimeline'),
        ('wallet', '0002_alter_currency_id_alter_wallet_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Amount (NGN)')),
                ('bank_account_name', models.CharField(max_length=150, verbose_name='Account Name')),
                ('bank_account_number', models.CharField(max_length=20, verbose_name='Account Number')),
                ('bank_code', models.CharField(max_length=10, verbose_name='Bank Code (CBN)')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Processing at Bank'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed at Bank')], db_index=True, default='pending', max_length=12)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Idempotency Key')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payout_requests', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL, verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Payout Request',
                'verbose_name_plural': 'Payout Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='pr_vendor_status_idx'), models.Index(fields=['status', 'created_at'], name='pr_status_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('transaction_type', models.CharField(choices=[('payment_received', 'Payment Received'), ('escrow_hold', 'Escrow Hold (Pending)'), ('escrow_release', 'Escrow Released to Available'), ('refund_received', 'Refund Received'), ('bonus_credit', 'Platform Bonus Credit'), ('reversal_credit', 'Reversal Credit'), ('payout_debit', 'Payout to Bank Account'), ('platform_fee', 'Platform Commission Fee'), ('refund_debit', 'Refund Issued to Buyer'), ('escrow_debit', 'Escrow Returned to Buyer'), ('adjustment_debit', 'Manual Adjustment Debit')], db_index=True, max_length=20, verbose_name='Type')),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], db_index=True, max_length=6, verbose_name='Entry')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Amount (NGN)')),
                ('status', models.CharField(choices=[('pending', 'Pending (Escrow)'), ('cleared', 'Cleared (Available)'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=10)),
                ('reference', models.CharField(db_index=True, help_text='Idempotency key: order_id, payment_id, payout_id, etc.', max_length=200, verbose_name='Reference')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('balance_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Available balance AFTER this transaction.', max_digits=14, null=True, verbose_name='Balance Snapshot')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_ledger_entries', to='order.order', verbose_name='Order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='wt2_wallet_created_idx'), models.Index(fields=['wallet', 'status', 'entry_type'], name='wt2_wallet_status_idx'), models.Index(fields=['reference'], name='wt2_reference_idx'), models.Index(fields=['transaction_type', 'status'], name='wt2_type_status_idx')],
            },
        ),
    ]
