# apps/product/selectors/__init__.py
from apps.product.selectors.product_selectors import (
    get_published_products,
    get_published_products_list,
    get_product_detail,
    get_featured_products,
    get_products_by_category,
    get_products_by_vendor,
    get_vendor_product_or_404,
    search_products,
    filter_products,
    get_product_reviews,
    get_user_review_for_product,
    get_wishlist_for_identity,
    get_user_wishlist,
    is_in_wishlist,
    get_vendor_coupons,
    get_coupon_by_code,
    get_vendor_review_summary,
    # Async selectors
    afilter_products,
    aget_product_detail,
    aget_product_detail_bundle,
    aget_vendor_product,
    alist_reviews_for_product_slug,
    auser_has_wishlist_slug,
    areviews_for_product,
    awishlist_for_identity,
    awishlist_for_user,
    avendor_coupons,
    avendor_products,
    alist_inventory_logs,
    asearch_suggest,
    aget_wishlist_status_for_products,
    # Phase 3 new async selectors
    alist_products,
    aget_featured_products,
    aget_products_by_vendor_async,
    # Phase 11 — Homepage bundle selectors
    aget_homepage_products,
    aget_homepage_hot_deals,
    aget_homepage_reviews,
)

__all__ = [
    # Sync selectors
    "filter_products",
    "get_coupon_by_code",
    "get_featured_products",
    "get_product_detail",
    "get_product_reviews",
    "get_products_by_category",
    "get_products_by_vendor",
    "get_published_products",
    "get_published_products_list",
    "get_user_review_for_product",
    "get_wishlist_for_identity",
    "get_user_wishlist",
    "get_vendor_coupons",
    "get_vendor_product_or_404",
    "get_vendor_review_summary",
    "is_in_wishlist",
    "search_products",
    # Async selectors
    "afilter_products",
    "aget_product_detail",
    "aget_product_detail_bundle",
    "aget_vendor_product",
    "aget_wishlist_status_for_products",
    "alist_inventory_logs",
    "alist_reviews_for_product_slug",
    "areviews_for_product",
    "asearch_suggest",
    "auser_has_wishlist_slug",
    "avendor_coupons",
    "avendor_products",
    "awishlist_for_identity",
    "awishlist_for_user",
    # Phase 3
    "alist_products",
    "aget_featured_products",
    "aget_products_by_vendor_async",
    # Phase 11 — Homepage bundle selectors
    "aget_homepage_products",
    "aget_homepage_hot_deals",
    "aget_homepage_reviews",
]
