# scratch/fix_collections_table.py
import os
import sys
import django

# Setup Django
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "backend.config.development")
django.setup()

from django.db import connection

SQL_DROP_M2M = "DROP TABLE IF EXISTS vendor_profile_collections CASCADE"

SQL_CREATE_COLLECTIONS = """
CREATE TABLE IF NOT EXISTS catalog_collections_new (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamptz NULL,
    user_id uuid NULL REFERENCES authentication_unifieduser(id) ON DELETE SET NULL,
    title varchar(255) NULL,
    sub_title varchar(255) NULL,
    description text NULL,
    slug varchar(255) NULL UNIQUE,
    image varchar(255) NULL,
    background_image varchar(255) NULL
)
"""

SQL_DROP_OLD = "DROP TABLE IF EXISTS catalog_collections CASCADE"
SQL_RENAME = "ALTER TABLE catalog_collections_new RENAME TO catalog_collections"

SQL_CREATE_M2M = """
CREATE TABLE vendor_profile_collections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendorprofile_id uuid NOT NULL REFERENCES vendor_profile(id) ON DELETE CASCADE,
    collections_id uuid NOT NULL REFERENCES catalog_collections(id) ON DELETE CASCADE,
    CONSTRAINT vendor_profile_collections_uniq UNIQUE (vendorprofile_id, collections_id)
)
"""

SQL_CREATE_INDEXES = """
CREATE INDEX IF NOT EXISTS vendor_profile_collections_vendorprofile_id_idx ON vendor_profile_collections(vendorprofile_id);
CREATE INDEX IF NOT EXISTS vendor_profile_collections_collections_id_idx ON vendor_profile_collections(collections_id);
"""

def main():
    with connection.cursor() as cur:
        print("Dropping intermediate M2M table...")
        cur.execute(SQL_DROP_M2M)
        
        print("Creating new catalog_collections table with UUID PK...")
        cur.execute(SQL_CREATE_COLLECTIONS)
        
        print("Dropping old catalog_collections table...")
        cur.execute(SQL_DROP_OLD)
        
        print("Renaming new table to catalog_collections...")
        cur.execute(SQL_RENAME)
        
        print("Creating new vendor_profile_collections M2M table...")
        cur.execute(SQL_CREATE_M2M)
        
        print("Creating indexes on M2M table...")
        cur.execute(SQL_CREATE_INDEXES)
        
        print("Table rebuild completed successfully!")

if __name__ == "__main__":
    main()
