# Generated by Django 6.0.3 on 2026-06-30 04:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rule Name')),
                ('metric_name', models.CharField(max_length=255, verbose_name='Metric Name')),
                ('operator', models.CharField(choices=[('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('eq', 'Equal'), ('ne', 'Not Equal')], max_length=5, verbose_name='Comparison Operator')),
                ('threshold', models.FloatField(verbose_name='Threshold')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10, verbose_name='Severity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['metric_name', 'is_active'], name='analytics_a_metric__859b57_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='Business Metric Name')),
                ('value', models.FloatField(verbose_name='Value')),
                ('period_start', models.DateTimeField(verbose_name='Period Start')),
                ('period_end', models.DateTimeField(verbose_name='Period End')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Business Metric',
                'verbose_name_plural': 'Business Metrics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['metric_name', 'period_start'], name='analytics_b_metric__5ba47f_idx'), models.Index(fields=['created_at'], name='analytics_b_created_473bc7_idx')],
                'unique_together': {('metric_name', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name identifier of the metric.', max_length=255, verbose_name='Metric Name')),
                ('metric_type', models.CharField(choices=[('counter', 'Counter'), ('gauge', 'Gauge'), ('histogram', 'Histogram'), ('timer', 'Timer')], default='gauge', max_length=20, verbose_name='Metric Type')),
                ('value', models.FloatField(help_text='Numeric value of the metric.', verbose_name='Value')),
                ('tags', models.JSONField(blank=True, default=dict, help_text='Categorization tags.', verbose_name='Tags')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['name', 'timestamp'], name='analytics_m_name_b1e977_idx'), models.Index(fields=['metric_type', 'timestamp'], name='analytics_m_metric__5d4c33_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('firing', 'Firing'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], default='firing', max_length=20, verbose_name='Status')),
                ('metric_value', models.FloatField(verbose_name='Current Value')),
                ('message', models.TextField(verbose_name='Alert Message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('fired_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Triggered At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.alertrule', verbose_name='Alert Rule')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-fired_at'],
                'indexes': [models.Index(fields=['rule', 'status'], name='analytics_a_rule_id_27c93b_idx'), models.Index(fields=['status', 'fired_at'], name='analytics_a_status_e314d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='Request URL pathway.', max_length=255, verbose_name='Endpoint Route')),
                ('method', models.CharField(help_text='HTTP verb used in the request.', max_length=10, verbose_name='HTTP Method')),
                ('response_time_ms', models.PositiveIntegerField(verbose_name='Response Time (ms)')),
                ('status_code', models.PositiveIntegerField(verbose_name='HTTP Status Code')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint', 'timestamp'], name='analytics_p_endpoin_c26a76_idx'), models.Index(fields=['status_code', 'timestamp'], name='analytics_p_status__ad88bc_idx'), models.Index(fields=['response_time_ms'], name='analytics_p_respons_2f935c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Type of action performed by the user.', max_length=100, verbose_name='Action Performed')),
                ('resource', models.CharField(blank=True, help_text='Affected resource or area of interaction.', max_length=100, verbose_name='Resource Name')),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Resource ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_id', models.CharField(blank=True, max_length=40, verbose_name='Session ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Action Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='analytics_u_user_id_54ee7d_idx'), models.Index(fields=['action', 'timestamp'], name='analytics_u_action_2b16c2_idx'), models.Index(fields=['resource', 'timestamp'], name='analytics_u_resourc_57f67f_idx')],
            },
        ),
    ]
