# Generated by Django 6.0.3 on 2026-07-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_metricrollup_performancemetricrollup'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='metricrollup',
            new_name='analytics_m_name_334540_idx',
            old_name='analytics_met_name_wind_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='metricrollup',
            new_name='analytics_m_window_9c9f75_idx',
            old_name='analytics_met_wind_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetricrollup',
            new_name='analytics_p_endpoin_673959_idx',
            old_name='analytics_per_endp_wind_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetricrollup',
            new_name='analytics_p_window_2acd1d_idx',
            old_name='analytics_per_wind_timestamp_idx',
        ),
    ]
