# Generated by Django 6.0.3 on 2026-05-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_fix_cartitem_related_name_to_items'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collections',
            table=None,
        ),
    ]
