# Generated by Django 6.0.3 on 2026-05-30 09:04

import cloudinary.models
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_brand_deleted_at_brand_is_deleted_and_more'),
        ('product', '0011_product_cash_payment_mode'),
        ('vendor', '0005_add_vendor_bank_account_and_kyc_legal_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAd',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('slot', models.CharField(choices=[('homepage_featured', 'Homepage Featured Products'), ('homepage_hot_deal', 'Homepage Hot Deals'), ('category_top', 'Category Page Top Banner'), ('collection_top', 'Collection Page Top Banner'), ('search_top', 'Search Results Top'), ('blog_sidebar', 'Blog Sidebar')], db_index=True, help_text='Which catalog slot this ad occupies.', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Must be True AND within start/end window to serve.')),
                ('start_date', models.DateTimeField(db_index=True, help_text='Campaign start datetime (UTC).')),
                ('end_date', models.DateTimeField(db_index=True, help_text='Campaign end datetime (UTC).')),
                ('budget_naira', models.DecimalField(decimal_places=2, default=0, help_text='Total campaign budget in Nigerian Naira (₦).', max_digits=12)),
                ('impressions', models.PositiveBigIntegerField(default=0, help_text='Total ad impressions served (incremented by Celery task).')),
                ('clicks', models.PositiveBigIntegerField(default=0, help_text='Total ad clicks (incremented by click-tracking endpoint).')),
            ],
            options={
                'verbose_name': 'Catalog Ad Campaign',
                'verbose_name_plural': 'Catalog Ad Campaigns',
                'ordering': ['-start_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatalogBanner',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('slot', models.CharField(choices=[('hero', 'Hero Carousel'), ('mid', 'Mid-Page Banner'), ('footer_cta', 'Footer CTA')], db_index=True, help_text='Which homepage slot this banner occupies.', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('cta_text', models.CharField(blank=True, default='Shop Now', help_text='Call-to-action button label.', max_length=80)),
                ('cta_url', models.CharField(blank=True, help_text='CTA destination URL (relative or absolute).', max_length=500)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Desktop banner image (recommended: 1920×600).', max_length=255, null=True, verbose_name='image')),
                ('mobile_image', cloudinary.models.CloudinaryField(blank=True, help_text='Mobile banner image (recommended: 390×500).', max_length=255, null=True, verbose_name='mobile_image')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower = displayed first within the carousel.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField(blank=True, db_index=True, help_text='Go-live datetime (UTC). Null = immediately active.', null=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, help_text='Expiry datetime (UTC). Null = never expires.', null=True)),
            ],
            options={
                'verbose_name': 'Catalog Banner',
                'verbose_name_plural': 'Catalog Banners',
                'ordering': ['sort_order', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('name', models.CharField(db_index=True, help_text="Unique, human-readable tag label (e.g. 'New Arrivals', 'Sustainable').", max_length=60, unique=True)),
                ('slug', models.SlugField(help_text='Auto-generated URL-safe slug.', unique=True)),
                ('color_hex', models.CharField(blank=True, help_text='#RRGGBB color for tag badge display.', max_length=7)),
                ('is_trending', models.BooleanField(db_index=True, default=False, help_text='Trending tags surface in the homepage tags rail.')),
            ],
            options={
                'verbose_name': 'Catalog Tag',
                'verbose_name_plural': 'Catalog Tags',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'managed': True, 'ordering': ['-premium', 'title'], 'verbose_name': 'Catalog Brand', 'verbose_name_plural': 'Catalog Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'ordering': ['sort_order', 'name'], 'verbose_name': 'Catalog Category', 'verbose_name_plural': 'Catalog Categories'},
        ),
        migrations.AlterModelOptions(
            name='collections',
            options={'managed': True, 'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Catalog Collection', 'verbose_name_plural': 'Catalog Collections'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_avatar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Author profile photo for post card display.', max_length=255, null=True, verbose_name='author_avatar'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO de-duplication.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached comment count. Updated by Celery task.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached likes count. Updated by Celery task.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Open Graph image used for social sharing (1200×630 recommended).', max_length=255, null=True, verbose_name='og_image'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Auto-calculated reading time (content word count ÷ 200 wpm).'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_posts',
            field=models.ManyToManyField(blank=True, help_text='Manually curated related blog posts (bi-directional).', to='catalog.blogpost'),
        ),
        migrations.AddField(
            model_name='brand',
            name='cached_product_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached product count. Refreshed by update_brand_product_count Celery task.'),
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, help_text="Country of origin (e.g. 'Nigeria', 'Ghana', 'South Africa').", max_length=60),
        ),
        migrations.AddField(
            model_name='brand',
            name='established_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year the brand was established.', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_banner',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Wide-format logo / hero banner for brand detail page.', max_length=255, null=True, verbose_name='logo_banner'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='brand',
            name='premium',
            field=models.BooleanField(db_index=True, default=False, help_text='Premium placement slot — shown first in brand grids.'),
        ),
        migrations.AddField(
            model_name='brand',
            name='verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin-verified brand. Shows a verified badge.'),
        ),
        migrations.AddField(
            model_name='brand',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Hero banner shown on the category detail / listing page.', max_length=255, null=True, verbose_name='banner_image'),
        ),
        migrations.AddField(
            model_name='category',
            name='cached_product_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Cached product count. Refreshed by update_category_product_count Celery task.'),
        ),
        migrations.AddField(
            model_name='category',
            name='color_hex',
            field=models.CharField(blank=True, help_text='#RRGGBB hex color for category pill / badge background.', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, help_text="CSS icon class or SVG slug (e.g. 'icon-dress', 'lucide-shirt').", max_length=60),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category for hierarchical browsing. Null = root category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Lower value = displayed first in grids.'),
        ),
        migrations.AddField(
            model_name='collections',
            name='banner_cta_text',
            field=models.CharField(blank=True, default='Shop Now', help_text='CTA button label shown on collection banner.', max_length=100),
        ),
        migrations.AddField(
            model_name='collections',
            name='banner_cta_url',
            field=models.CharField(blank=True, help_text='CTA button destination URL (relative or absolute).', max_length=500),
        ),
        migrations.AddField(
            model_name='collections',
            name='cached_product_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached product count. Refreshed by update_collection_product_count Celery task.'),
        ),
        migrations.AddField(
            model_name='collections',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Schedule collection expiry datetime (UTC). Null = never expires.', null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured collections appear in the homepage featured rail.'),
        ),
        migrations.AddField(
            model_name='collections',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='collections',
            name='meta_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='collections',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Lower value = displayed first.'),
        ),
        migrations.AddField(
            model_name='collections',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Schedule collection go-live datetime (UTC). Null = always live.', null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Main collection thumbnail image (public_id).', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_featured', 'published_at'], name='catalog_blog_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['verified', 'premium'], name='brand_verified_premium_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug'], name='brand_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'sort_order'], name='category_parent_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['active', 'sort_order'], name='category_active_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='collections',
            index=models.Index(fields=['is_featured', 'sort_order'], name='collection_featured_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='collections',
            index=models.Index(fields=['start_date', 'end_date'], name='collection_schedule_idx'),
        ),
        migrations.AddIndex(
            model_name='collections',
            index=models.Index(fields=['slug'], name='collection_slug_idx'),
        ),
        migrations.AddField(
            model_name='catalogad',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Specific product to boost. Null = brand/collection-level ad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to='product.product'),
        ),
        migrations.AddField(
            model_name='catalogad',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor running this ad campaign.', on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='vendor.vendorprofile'),
        ),
        migrations.AddIndex(
            model_name='catalogbanner',
            index=models.Index(fields=['slot', 'is_active'], name='banner_slot_active_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogbanner',
            index=models.Index(fields=['slot', 'start_date', 'end_date'], name='banner_slot_schedule_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_trending', 'name'], name='tag_trending_name_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogad',
            index=models.Index(fields=['slot', 'is_active', 'start_date', 'end_date'], name='catalog_ad_slot_active_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogad',
            index=models.Index(fields=['vendor', 'is_active'], name='catalog_ad_vendor_active_idx'),
        ),
    ]
