# Generated by Django 6.0.3 on 2026-05-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_catalog_model_expansion_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='catalog_tags',
            field=models.ManyToManyField(blank=True, help_text='Normalized shared taxonomy tags. Legacy JSON tags are preserved for backward compatibility.', related_name='blog_posts', to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='collections',
            name='catalog_tags',
            field=models.ManyToManyField(blank=True, help_text='Shared merchandising tags for discovery, campaigns, and future faceted search.', related_name='collections', to='catalog.tag'),
        ),
    ]
