# Generated by Django 6.0.3 on 2026-06-05 14:08

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_blogpost_catalog_tags_collections_catalog_tags'),
        ('measurements', '0003_alter_measurementprofile_id'),
        ('product', '0012_productdraftsession'),
        ('vendor', '0005_add_vendor_bank_account_and_kyc_legal_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('composition', models.JSONField(default=dict, help_text='Fiber percentage breakdown. E.g. {"cotton": 80, "polyester": 20}', verbose_name='Composition')),
                ('care_instructions', models.JSONField(default=list, help_text='List of care codes. E.g. ["machine_wash_cold", "do_not_bleach", "tumble_dry_low"]', verbose_name='Care Instructions')),
                ('texture_image', cloudinary.models.CloudinaryField(blank=True, help_text='Fabric swatch / texture photo — two-phase Cloudinary upload.', max_length=255, null=True, verbose_name='texture_image')),
                ('properties', models.JSONField(default=dict, help_text='Boolean property map. E.g. {"breathable": true, "stretch": false, "waterproof": false}', verbose_name='Properties')),
                ('sustainability_score', models.PositiveSmallIntegerField(default=0, help_text='0 = poorest, 100 = best eco-rating.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sustainability Score')),
                ('origin_country', models.CharField(blank=True, help_text='Primary textile production country.', max_length=100, verbose_name='Origin Country')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Fabric',
                'verbose_name_plural': 'Fabrics',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'sustainability_score'], name='fab_active_eco_idx')],
            },
        ),
        migrations.CreateModel(
            name='FashionStyleGuide',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, help_text='Hero image — uploaded via Cloudinary two-phase flow.', max_length=255, null=True, verbose_name='cover_image')),
                ('season', models.CharField(blank=True, choices=[('ss', 'Spring/Summer'), ('aw', 'Autumn/Winter'), ('pf', 'Pre-Fall'), ('cr', 'Cruise/Resort')], db_index=True, max_length=3, verbose_name='Season')),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='e.g. 2026 — used for seasonal archive.', null=True, verbose_name='Year')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('published_at', models.DateTimeField(blank=True, help_text='Scheduled publish time. Null = unpublished.', null=True, verbose_name='Published At')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='Share Count')),
                ('seo_title', models.CharField(blank=True, help_text='Overrides <title> tag if set.', max_length=180, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
                ('ai_generated', models.BooleanField(default=False, help_text='True if content was AI-drafted.', verbose_name='AI Generated')),
                ('ai_prompt_used', models.TextField(blank=True, help_text='Audit: the prompt used to generate this guide.', verbose_name='AI Prompt Used')),
                ('embedding_vector', models.JSONField(blank=True, help_text='Float array from embedding model — reserved for similarity search.', null=True, verbose_name='Embedding Vector')),
                ('editor', models.ForeignKey(blank=True, help_text='Staff user who curated or approved this guide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_guides', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
                ('featured_products', models.ManyToManyField(blank=True, help_text='Products showcased in this style guide.', to='product.product', verbose_name='Featured Products')),
                ('trend_tags', models.ManyToManyField(blank=True, help_text='Related taxonomy tags for discovery.', to='catalog.tag', verbose_name='Trend Tags')),
            ],
            options={
                'verbose_name': 'Fashion Style Guide',
                'verbose_name_plural': 'Fashion Style Guides',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FashionTrend',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, help_text='Hero image for this trend.', max_length=255, null=True, verbose_name='cover_image')),
                ('trend_type', models.CharField(choices=[('seasonal', 'Seasonal'), ('viral', 'Viral'), ('celebrity', 'Celebrity'), ('runway', 'Runway'), ('street', 'Street Style')], db_index=True, max_length=10, verbose_name='Trend Type')),
                ('trend_score', models.FloatField(db_index=True, default=0.0, help_text='Higher = hotter. Updated by ML pipeline or editor.', verbose_name='Trend Score')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('featured_until', models.DateTimeField(blank=True, null=True, verbose_name='Featured Until')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name='Origin Country')),
                ('origin_city', models.CharField(blank=True, max_length=100, verbose_name='Origin City')),
                ('embedding_vector', models.JSONField(blank=True, help_text='Float array — reserved for semantic similarity search.', null=True, verbose_name='Embedding Vector')),
                ('associated_categories', models.ManyToManyField(blank=True, related_name='fashion_trends', to='catalog.category', verbose_name='Associated Categories')),
                ('associated_tags', models.ManyToManyField(blank=True, related_name='fashion_trends', to='catalog.tag', verbose_name='Associated Tags')),
            ],
            options={
                'verbose_name': 'Fashion Trend',
                'verbose_name_plural': 'Fashion Trends',
                'ordering': ['-trend_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lookbook',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, help_text='Hero image — two-phase Cloudinary upload.', max_length=255, null=True, verbose_name='cover_image')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='Ordered list of Cloudinary public_ids.', verbose_name='Gallery Images')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('featured_until', models.DateTimeField(blank=True, help_text='Auto-expire feature prominence after this datetime.', null=True, verbose_name='Featured Until')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('style_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookbooks', to='catalog.fashionstyleguide', verbose_name='Style Guide')),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor owner. Null = platform editorial lookbook.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookbooks', to='vendor.vendorprofile', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Lookbook',
                'verbose_name_plural': 'Lookbooks',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LookbookItem',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort Order')),
                ('annotation_text', models.CharField(blank=True, help_text='Short caption displayed on hover.', max_length=200, verbose_name='Annotation')),
                ('position_x', models.FloatField(blank=True, help_text='Horizontal hotspot position (0–100%).', null=True, verbose_name='Position X (%)')),
                ('position_y', models.FloatField(blank=True, help_text='Vertical hotspot position (0–100%).', null=True, verbose_name='Position Y (%)')),
                ('lookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.lookbook', verbose_name='Lookbook')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookbook_items', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Lookbook Item',
                'verbose_name_plural': 'Lookbook Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex'), ('children', 'Children')], db_index=True, max_length=10, verbose_name='Gender')),
                ('size_type', models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes'), ('accessories', 'Accessories')], db_index=True, max_length=12, verbose_name='Size Type')),
                ('chart_data', models.JSONField(help_text='Size-to-measurement range mapping. E.g. {"XS": {"bust": [80,84], "waist": [60,64]}}', verbose_name='Chart Data')),
                ('unit', models.CharField(choices=[('cm', 'Centimetres'), ('inch', 'Inches')], default='cm', max_length=4, verbose_name='Unit')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort Order')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_charts', to='catalog.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_charts', to='catalog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Size Chart',
                'verbose_name_plural': 'Size Charts',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SizeRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('recommended_size', models.CharField(max_length=10, verbose_name='Recommended Size')),
                ('confidence_score', models.FloatField(help_text='0.0 = low confidence, 1.0 = high confidence.', verbose_name='Confidence Score')),
                ('reasoning', models.TextField(blank=True, help_text='AI explanation of why this size was recommended.', verbose_name='Reasoning')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('model_version', models.CharField(blank=True, help_text='ML model version for reproducibility audit.', max_length=50, verbose_name='Model Version')),
                ('measurement_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_recommendations', to='measurements.measurementprofile', verbose_name='Measurement Profile')),
                ('size_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='catalog.sizechart', verbose_name='Size Chart')),
            ],
            options={
                'verbose_name': 'Size Recommendation',
                'verbose_name_plural': 'Size Recommendations',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendingProduct',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('trend_score', models.FloatField(db_index=True, default=0.0, help_text='Composite: views×0.4 + orders×0.4 + wishlist×0.2.', verbose_name='Trend Score')),
                ('rank', models.PositiveIntegerField(db_index=True, help_text='1 = top trending for this period.', verbose_name='Rank')),
                ('period', models.CharField(choices=[('24h', 'Last 24 Hours'), ('7d', 'Last 7 Days'), ('30d', 'Last 30 Days')], db_index=True, max_length=3, verbose_name='Period')),
                ('refreshed_at', models.DateTimeField(auto_now=True, verbose_name='Refreshed At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_entries', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Trending Product',
                'verbose_name_plural': 'Trending Products',
                'ordering': ['period', 'rank'],
            },
        ),
        migrations.AddIndex(
            model_name='fashionstyleguide',
            index=models.Index(fields=['slug'], name='sg_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='fashionstyleguide',
            index=models.Index(fields=['season', 'year'], name='sg_season_year_idx'),
        ),
        migrations.AddIndex(
            model_name='fashionstyleguide',
            index=models.Index(fields=['is_published', 'published_at'], name='sg_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='fashiontrend',
            index=models.Index(fields=['is_active', 'trend_score'], name='ft_active_score_idx'),
        ),
        migrations.AddIndex(
            model_name='fashiontrend',
            index=models.Index(fields=['trend_type', 'trend_score'], name='ft_type_score_idx'),
        ),
        migrations.AddIndex(
            model_name='lookbook',
            index=models.Index(fields=['vendor', 'is_published'], name='lb_vendor_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='lookbook',
            index=models.Index(fields=['is_published', 'featured_until'], name='lb_featured_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lookbookitem',
            unique_together={('lookbook', 'product')},
        ),
        migrations.AddIndex(
            model_name='sizechart',
            index=models.Index(fields=['gender', 'size_type'], name='sc_gender_type_idx'),
        ),
        migrations.AddIndex(
            model_name='sizechart',
            index=models.Index(fields=['category', 'is_active'], name='sc_cat_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sizerecommendation',
            unique_together={('measurement_profile', 'size_chart')},
        ),
        migrations.AddIndex(
            model_name='trendingproduct',
            index=models.Index(fields=['period', 'rank'], name='tp_period_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingproduct',
            index=models.Index(fields=['period', 'trend_score'], name='tp_period_score_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trendingproduct',
            unique_together={('product', 'period')},
        ),
    ]
