# Generated by Django 6.0.3 on 2026-06-05 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_fabric_fashionstyleguide_fashiontrend_lookbook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ai_trend_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='AI-computed trend score (0.0 – 100.0). Refreshed every 6 hours.'),
        ),
        migrations.AddField(
            model_name='category',
            name='depth',
            field=models.PositiveSmallIntegerField(default=0, help_text='Hierarchy depth. 0 = root category. Updated on save.'),
        ),
        migrations.AddField(
            model_name='category',
            name='embedding_vector',
            field=models.JSONField(blank=True, help_text='768-dim embedding for category similarity matching.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='full_path',
            field=models.CharField(blank=True, db_index=True, help_text="Materialized full slug path: 'fashion/women/dresses'. Updated on save.", max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='gender_tags',
            field=models.JSONField(blank=True, default=list, help_text='Target gender list: ["female", "male", "unisex", "children"].'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_leaf_node',
            field=models.BooleanField(db_index=True, default=True, help_text='True if this category has no children. Updated by Celery beat.'),
        ),
        migrations.AddField(
            model_name='category',
            name='season_relevance',
            field=models.JSONField(blank=True, default=dict, help_text='Season-to-relevance score: {"SS": 0.9, "AW": 0.3}.'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_leaf_node', 'active'], name='category_leaf_active_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['ai_trend_score'], name='category_trend_score_idx'),
        ),
    ]
