# Generated by Django 6.0.3 on 2026-06-26 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_category_category_active_sort_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['active', 'sort_order'], name='category_active_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_leaf_node', 'active'], name='category_leaf_active_idx'),
        ),
    ]
