# Generated by Django 6.0.3 on 2026-05-07 23:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_review', 'Under Review'), ('approved', 'Approved ✅'), ('rejected', 'Rejected ❌'), ('resubmit', 'Resubmission Required')], db_index=True, default='pending', max_length=20)),
                ('provider_reference', models.CharField(blank=True, default='', help_text='External KYC provider job/session reference ID.', max_length=255)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submission', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'KYC Submission',
                'verbose_name_plural': 'KYC Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('nin_card', 'NIN Card — National Identity Number'), ('bvn_slip', 'BVN Slip — Bank Verification Number'), ('passport', 'International Passport'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card"), ('selfie', 'Live Selfie / Biometric Photo'), ('cac_certificate', 'CAC Certificate (Business Registration)'), ('utility_bill', 'Utility Bill (Address Proof)')], db_index=True, max_length=30)),
                ('document_number', models.CharField(blank=True, default='', help_text='The actual document number, e.g. NIN (11 digits), BVN, passport number. Encrypt at-rest in production.', max_length=50)),
                ('public_id', models.CharField(blank=True, default='', help_text='Cloudinary public_id returned after client-side upload.', max_length=500)),
                ('secure_url', models.URLField(blank=True, default='', help_text='Cloudinary secure_url returned after client-side upload.', max_length=1000)),
                ('provider_verified', models.BooleanField(default=False, help_text='True if the external KYC provider confirms this document is valid.')),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='Raw JSON result from external KYC provider for this document.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycsubmission')),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kycsubmission',
            index=models.Index(fields=['status'], name='kyc_submission_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kycsubmission',
            index=models.Index(fields=['user'], name='kyc_submission_user_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['submission', 'document_type'], name='kyc_doc_submission_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kycdocument',
            unique_together={('submission', 'document_type')},
        ),
    ]
