# Generated by Django 6.0.3 on 2026-05-10 22:06

import django.utils.timezone
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycdocument',
            options={'ordering': ['created_at'], 'verbose_name': 'KYC Document', 'verbose_name_plural': 'KYC Documents'},
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.'),
        ),
    ]
