# Generated by Django 6.0.3 on 2026-05-12 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_add_timestamped_fields_to_kycdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsubmission',
            name='user',
            field=models.OneToOneField(help_text='PROTECT: KYC records are CBN/NDPR/GDPR compliance documents with a 7-year retention requirement. User deletion MUST NOT cascade-destroy this record. Use the admin anonymization action to null PII fields while retaining the compliance audit trail. Attempting to delete a user who has a KYC submission will raise ProtectedError — resolve via the anonymize_user management command.', on_delete=django.db.models.deletion.PROTECT, related_name='kyc_submission', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
