# Generated by Django 6.0.3 on 2026-05-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_kyc_protect_user_fk_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='legal_name',
            field=models.CharField(blank=True, default='', help_text='Full legal name as it appears on the government-issued ID (NIN/BVN/CAC). Set by admin staff on KYC approval. Used to cross-check bank account holder names when vendors register payout accounts.', max_length=200),
        ),
    ]
