# Generated by Django 6.0.3 on 2026-06-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_add_vendor_bank_account_and_kyc_legal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
