# Generated by Django 6.0.3 on 2026-07-09 22:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Example',
                'verbose_name_plural': 'Examples',
            },
        ),
        migrations.CreateModel(
            name='UnifiedAccessPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('resource_type', models.CharField(max_length=50, verbose_name='Resource Type')),
                ('resource_id', models.CharField(max_length=100, verbose_name='Resource ID')),
                ('permission_type', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('delete', 'Delete'), ('share', 'Share'), ('admin', 'Admin')], max_length=20, verbose_name='Permission Type')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='Conditions')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Unified Access Permission',
                'verbose_name_plural': 'Unified Access Permissions',
                'indexes': [models.Index(fields=['user', 'resource_type'], name='app_standar_user_id_b1e223_idx'), models.Index(fields=['expires_at'], name='app_standar_expires_cd19a3_idx')],
                'unique_together': {('user', 'resource_type', 'resource_id', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='UnifiedAIUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('service_type', models.CharField(choices=[('chat', 'Chat Assistant'), ('text_generation', 'Text Generation'), ('embedding', 'Vector Embedding'), ('image_analysis', 'Image Analysis')], max_length=30, verbose_name='Service Type')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model Name')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='Input Tokens')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='Output Tokens')),
                ('processing_time', models.FloatField(verbose_name='Processing Time (Seconds)')),
                ('cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Cost')),
                ('request_data', models.JSONField(default=dict, verbose_name='Request Data')),
                ('response_data', models.JSONField(default=dict, verbose_name='Response Data')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Unified AI Usage',
                'verbose_name_plural': 'Unified AI Usages',
                'indexes': [models.Index(fields=['user', 'service_type', '-created_at'], name='app_standar_user_id_b66a81_idx'), models.Index(fields=['model_name', '-created_at'], name='app_standar_model_n_d45988_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnifiedAuthIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token'), ('otp', 'OTP Token')], max_length=20, verbose_name='Token Type')),
                ('token_value', models.TextField(verbose_name='Token Value')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_integrations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Unified Auth Integration',
                'verbose_name_plural': 'Unified Auth Integrations',
                'indexes': [models.Index(fields=['user', 'token_type'], name='app_standar_user_id_45918e_idx'), models.Index(fields=['expires_at'], name='app_standar_expires_6fd2a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnifiedBillingIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('status', models.CharField(choices=[], default='pending', max_length=20, verbose_name='Status')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Status Changed At')),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('subscription', 'Subscription')], max_length=30, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('gateway', models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('wallet', 'Wallet'), ('other', 'Other')], max_length=20, verbose_name='Payment Gateway')),
                ('reference_id', models.CharField(max_length=100, unique=True, verbose_name='Reference ID')),
                ('gateway_reference', models.CharField(blank=True, max_length=100, verbose_name='Gateway Reference')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Unified Billing Transaction',
                'verbose_name_plural': 'Unified Billing Transactions',
                'indexes': [models.Index(fields=['reference_id'], name='app_standar_referen_bba02e_idx'), models.Index(fields=['user', 'transaction_type', '-created_at'], name='app_standar_user_id_6adc94_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnifiedNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('status', models.CharField(choices=[], default='pending', max_length=20, verbose_name='Status')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Status Changed At')),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification'), ('in_app', 'In App')], max_length=30, verbose_name='Notification Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled For')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Unified Notification',
                'verbose_name_plural': 'Unified Notifications',
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='app_standar_user_id_6e5f01_idx'), models.Index(fields=['notification_type', 'status'], name='app_standar_notific_58c1bc_idx'), models.Index(fields=['scheduled_for'], name='app_standar_schedul_5a38e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnifiedRateLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('endpoint', models.CharField(max_length=200, verbose_name='Endpoint')),
                ('limit_type', models.CharField(choices=[('api_call', 'API Call'), ('ai_request', 'AI Request'), ('file_upload', 'File Upload'), ('sms_send', 'SMS Send')], max_length=20, verbose_name='Limit Type')),
                ('window_minutes', models.IntegerField(default=60, verbose_name='Window (Minutes)')),
                ('max_requests', models.IntegerField(verbose_name='Max Requests')),
                ('current_count', models.IntegerField(default=0, verbose_name='Current Count')),
                ('window_start', models.DateTimeField(verbose_name='Window Start')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Unified Rate Limit',
                'verbose_name_plural': 'Unified Rate Limits',
                'indexes': [models.Index(fields=['user', 'limit_type'], name='app_standar_user_id_5dca0c_idx'), models.Index(fields=['window_start'], name='app_standar_window__42735c_idx')],
                'unique_together': {('user', 'endpoint', 'limit_type')},
            },
        ),
    ]
