# Generated by Django 6.0.3 on 2026-04-25 17:12

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('code', models.CharField(choices=[('paystack', 'Paystack')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack')], db_index=True, max_length=40)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('success', models.BooleanField(default=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack')], db_index=True, max_length=40)),
                ('event', models.CharField(db_index=True, max_length=120)),
                ('event_id', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('payload_hash', models.CharField(max_length=128, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processing_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'event', 'processed'], name='payment_pay_provide_a8bc30_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaystackTransferRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('recipient_code', models.CharField(db_index=True, max_length=160, unique=True)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=180)),
                ('bank_name', models.CharField(max_length=180)),
                ('bank_code', models.CharField(max_length=20)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paystack_transfer_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack')], db_index=True, default='paystack', max_length=40)),
                ('purpose', models.CharField(choices=[('wallet_topup', 'Wallet Top-up'), ('order_payment', 'Order Payment'), ('measurement_fee', 'Measurement Fee'), ('vendor_service', 'Vendor Service'), ('advertisement_fee', 'Advertisement Fee')], db_index=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initialized', 'Initialized'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('reference', models.CharField(db_index=True, max_length=120, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('authorization_url', models.URLField(blank=True, default='', max_length=1000)),
                ('access_code', models.CharField(blank=True, default='', max_length=160)),
                ('order_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('measurement_request_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payment_pay_user_id_ae46c7_idx'), models.Index(fields=['provider', 'status'], name='payment_pay_provide_8bdf71_idx'), models.Index(fields=['purpose', 'status'], name='payment_pay_purpose_2b5751_idx')],
            },
        ),
    ]
