# Generated by Django 6.0.3 on 2026-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_expand_provider_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('qr', 'QR'), ('wallet', 'Wallet'), ('card', 'Card'), ('gift_card', 'Gift Card'), ('bank_deposit', 'Bank Deposit'), ('voucher', 'Voucher'), ('app', 'App'), ('cod', 'Cash On Delivery'), ('others', 'Others'), ('olive_pay', 'Olive Pay')], db_index=True, default='paystack', max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='code',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('qr', 'QR'), ('wallet', 'Wallet'), ('card', 'Card'), ('gift_card', 'Gift Card'), ('bank_deposit', 'Bank Deposit'), ('voucher', 'Voucher'), ('app', 'App'), ('cod', 'Cash On Delivery'), ('others', 'Others'), ('olive_pay', 'Olive Pay')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentproviderlog',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('qr', 'QR'), ('wallet', 'Wallet'), ('card', 'Card'), ('gift_card', 'Gift Card'), ('bank_deposit', 'Bank Deposit'), ('voucher', 'Voucher'), ('app', 'App'), ('cod', 'Cash On Delivery'), ('others', 'Others'), ('olive_pay', 'Olive Pay')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentwebhookevent',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('qr', 'QR'), ('wallet', 'Wallet'), ('card', 'Card'), ('gift_card', 'Gift Card'), ('bank_deposit', 'Bank Deposit'), ('voucher', 'Voucher'), ('app', 'App'), ('cod', 'Cash On Delivery'), ('others', 'Others'), ('olive_pay', 'Olive Pay')], db_index=True, max_length=40),
        ),
    ]
