# Generated by Django 6.0.3 on 2026-05-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentintent_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'flutterwave'), ('stripe', 'stripe'), ('paypal', 'paypal'), ('cash', 'cash'), ('bank_transfer', 'bank_transfer'), ('ussd', 'ussd'), ('qr', 'qr'), ('wallet', 'wallet'), ('card', 'card'), ('gift_card', 'gift_card'), ('bank_deposit', 'bank_deposit'), ('voucher', 'voucher'), ('app', 'app'), ('cod', 'cod'), ('others', 'others'), ('olive_pay', 'olive_pay')], db_index=True, default='paystack', max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='code',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'flutterwave'), ('stripe', 'stripe'), ('paypal', 'paypal'), ('cash', 'cash'), ('bank_transfer', 'bank_transfer'), ('ussd', 'ussd'), ('qr', 'qr'), ('wallet', 'wallet'), ('card', 'card'), ('gift_card', 'gift_card'), ('bank_deposit', 'bank_deposit'), ('voucher', 'voucher'), ('app', 'app'), ('cod', 'cod'), ('others', 'others'), ('olive_pay', 'olive_pay')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentproviderlog',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'flutterwave'), ('stripe', 'stripe'), ('paypal', 'paypal'), ('cash', 'cash'), ('bank_transfer', 'bank_transfer'), ('ussd', 'ussd'), ('qr', 'qr'), ('wallet', 'wallet'), ('card', 'card'), ('gift_card', 'gift_card'), ('bank_deposit', 'bank_deposit'), ('voucher', 'voucher'), ('app', 'app'), ('cod', 'cod'), ('others', 'others'), ('olive_pay', 'olive_pay')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentwebhookevent',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'flutterwave'), ('stripe', 'stripe'), ('paypal', 'paypal'), ('cash', 'cash'), ('bank_transfer', 'bank_transfer'), ('ussd', 'ussd'), ('qr', 'qr'), ('wallet', 'wallet'), ('card', 'card'), ('gift_card', 'gift_card'), ('bank_deposit', 'bank_deposit'), ('voucher', 'voucher'), ('app', 'app'), ('cod', 'cod'), ('others', 'others'), ('olive_pay', 'olive_pay')], db_index=True, max_length=40),
        ),
    ]
