# Generated by Django 6.0.3 on 2026-06-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_paymentintent_id_alter_paymentprovider_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='paymentproviderlog',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='paystacktransferrecipient',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
