# Generated by Django 6.0.3 on 2026-04-23 21:40

import apps.common.models.models
import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=0, help_text='Current highest sequence number issued.')),
            ],
            options={
                'verbose_name': 'Member ID Counter',
                'db_table': 'authentication_member_id_counter',
            },
        ),
        migrations.CreateModel(
            name='UnifiedUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Primary unique identifier for email-based auth.', max_length=254, null=True, unique=True, verbose_name='email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, help_text='Primary unique identifier for phone-based auth.', max_length=128, null=True, region=None, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, help_text='Cloudinary image public_id. Set via the /api/v1/upload/presign/ → direct upload → webhook flow. Use .url in serializers to retrieve the full HTTPS secure_url. In admin: use the file picker widget to upload directly to Cloudinary.', max_length=255, null=True, verbose_name='avatar')),
                ('bio', models.TextField(blank=True, help_text="User's biography.")),
                ('country', models.CharField(blank=True, db_index=True, help_text="User's country.", max_length=100)),
                ('state', models.CharField(blank=True, help_text="User's state or province.", max_length=100)),
                ('city', models.CharField(blank=True, help_text="User's city.", max_length=100)),
                ('address', models.CharField(blank=True, help_text="User's street address.", max_length=255)),
                ('role', models.CharField(choices=[('vendor', 'Vendor'), ('client', 'Client'), ('staff', 'Staff'), ('admin', 'Admin'), ('editor', 'Editor'), ('support', 'Support'), ('assistant', 'Assistant'), ('moderator', 'Moderator'), ('super_admin', 'Super Admin'), ('super_vendor', 'Super Vendor'), ('super_client', 'Super Client'), ('super_staff', 'Super Staff'), ('super_editor', 'Super Editor'), ('super_support', 'Super Support'), ('super_assistant', 'Super Assistant'), ('super_moderator', 'Super Moderator')], db_index=True, default='client', help_text='RBAC Role. Cannot be changed after creation.', max_length=20)),
                ('auth_provider', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('google', 'Google')], default='email', help_text='Authentication provider used at signup.', max_length=20)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='True if email/phone OTP is verified.')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='True if user account is active.')),
                ('member_id', models.CharField(blank=True, db_index=True, editable=False, help_text='Unique human-readable brand ID (e.g. FASTAR000062). Auto-generated on user creation. Cannot be changed.', max_length=12, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='unified_user_set', related_query_name='unified_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='unified_user_set', related_query_name='unified_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Unified User',
                'verbose_name_plural': 'Unified Users',
                'ordering': ['-date_joined'],
            },
            bases=(models.Model, apps.common.models.models.HardDeleteMixin),
        ),
        migrations.CreateModel(
            name='BiometricCredential',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('credential_id', models.BinaryField(help_text='The Credential ID generated by the authenticator.', unique=True)),
                ('public_key', models.BinaryField(help_text='The Public Key for signature verification.')),
                ('sign_count', models.IntegerField(default=0, help_text='Counter to prevent replay attacks.')),
                ('device_name', models.CharField(blank=True, help_text="User-friendly name (e.g., 'MacBook TouchID').", max_length=255, null=True)),
                ('user', models.ForeignKey(help_text='The user this credential belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='biometric_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Credential',
                'verbose_name_plural': 'Biometric Credentials',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('jti', models.CharField(db_index=True, help_text='JWT ID (jti claim) of the refresh token for this session. Used to match and blacklist via SimpleJWT.', max_length=255, unique=True)),
                ('client_type', models.CharField(choices=[('web', 'Web Browser'), ('mobile', 'Mobile App'), ('api', 'API Client'), ('unknown', 'Unknown')], default='unknown', help_text='Browser / mobile app / API client.', max_length=20)),
                ('browser_family', models.CharField(blank=True, help_text='Chrome, Firefox, Safari, etc.', max_length=100)),
                ('os_family', models.CharField(blank=True, help_text='Windows, macOS, iOS, Android, Linux, etc.', max_length=100)),
                ('device_name', models.CharField(blank=True, help_text="Human-readable label, e.g. 'Chrome on Windows', 'iPhone 15 Pro Max'.", max_length=200)),
                ('user_agent', models.TextField(blank=True, help_text='Raw User-Agent string.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address at session creation (login time).', null=True, unpack_ipv4=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Updated on every token refresh. Stale sessions = last_used_at old.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the refresh token expires (from JWT payload).', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='True for the session that corresponds to the JWT making the current request. Computed at serializer time, not stored.')),
                ('user', models.ForeignKey(help_text='The owner of this session.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Client IP address (supports IPv4 and IPv6).', unpack_ipv4=True)),
                ('user_agent', models.TextField(blank=True, help_text='Raw HTTP User-Agent string.')),
                ('client_type', models.CharField(choices=[('web', 'Web Browser'), ('mobile', 'Mobile App'), ('api', 'API Client'), ('curl', 'cURL / Script'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Derived from User-Agent: web / mobile / api / curl.', max_length=20)),
                ('browser_family', models.CharField(blank=True, help_text='Browser family: Chrome, Firefox, Safari, Unknown, etc.', max_length=100)),
                ('os_family', models.CharField(blank=True, help_text='Operating system: Windows, macOS, iOS, Android, Linux, etc.', max_length=100)),
                ('device_type', models.CharField(blank=True, help_text='Device category: desktop, mobile, tablet, bot, etc.', max_length=50)),
                ('country', models.CharField(blank=True, db_index=True, help_text='Country name derived from IP (via MaxMind / ipapi).', max_length=100)),
                ('country_code', models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 country code (e.g. 'NG', 'US').", max_length=3)),
                ('region', models.CharField(blank=True, help_text="State / region / province (e.g. 'Lagos', 'California').", max_length=100)),
                ('city', models.CharField(blank=True, help_text="City name (e.g. 'Lagos', 'San Francisco').", max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Approx. latitude from IP geo-lookup.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Approx. longitude from IP geo-lookup.', max_digits=9, null=True)),
                ('auth_method', models.CharField(choices=[('email', 'Email + Password'), ('phone', 'Phone + Password'), ('google', 'Google OAuth'), ('biometric', 'Biometric / FIDO2')], default='email', help_text='Authentication method used for this attempt.', max_length=20)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('suspicious', 'Suspicious')], db_index=True, default='failed', help_text='Result of the login attempt.', max_length=20)),
                ('failure_reason', models.CharField(blank=True, help_text="Short machine-readable failure code: 'invalid_credentials', 'account_inactive', 'account_deleted', 'rate_limited', 'mfa_required', etc.", max_length=100)),
                ('is_successful', models.BooleanField(db_index=True, default=False, help_text='True iff the login attempt succeeded and tokens were issued.')),
                ('risk_score', models.SmallIntegerField(default=0, help_text='Risk score 0-100. ≥70 triggers a security alert.')),
                ('is_new_device', models.BooleanField(default=False, help_text='True if this is the first time this device fingerprint was seen.')),
                ('is_new_country', models.BooleanField(default=False, help_text='True if the login country is new for this user.')),
                ('is_tor_exit_node', models.BooleanField(default=False, help_text='True if the IP is a known Tor exit node.')),
                ('user', models.ForeignKey(blank=True, help_text='NULL when a login attempt targets an unknown identifier (failed user-enumeration attempt).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='The session created by this successful login (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to='authentication.usersession')),
            ],
            options={
                'verbose_name': 'Login Event',
                'verbose_name_plural': 'Login Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['email'], name='uu_email_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['phone'], name='uu_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['role'], name='uu_role_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['is_verified'], name='uu_is_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['is_active'], name='uu_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['is_verified', 'is_active'], name='uu_is_verified_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['is_staff'], name='uu_is_staff_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['auth_provider'], name='uu_auth_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['member_id'], name='uu_member_id_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['country'], name='uu_country_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['country', 'is_active'], name='uu_country_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['email', 'role'], name='uu_email_role_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['phone', 'role'], name='uu_phone_role_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['auth_provider', 'is_verified'], name='uu_provider_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['role', 'is_active'], name='uu_role_active_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-last_used_at'], name='us_user_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['jti'], name='us_jti_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='us_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['user', '-created_at'], name='le_user_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['ip_address', '-created_at'], name='le_ip_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['outcome', '-created_at'], name='le_outcome_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['country', '-created_at'], name='le_country_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['is_successful'], name='le_success_idx'),
        ),
    ]
