# Generated by Django 6.0.2 on 2026-03-13 20:08

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=0, help_text='Current highest sequence number issued.')),
            ],
            options={
                'verbose_name': 'Member ID Counter',
                'db_table': 'authentication_member_id_counter',
            },
        ),
        migrations.CreateModel(
            name='UnifiedUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Primary unique identifier for email-based auth.', max_length=254, null=True, unique=True, verbose_name='email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, help_text='Primary unique identifier for phone-based auth.', max_length=128, null=True, region=None, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('avatar', models.ImageField(default='default/default-user.jpg', help_text="User's profile picture.", upload_to='avatars/%Y/%m/')),
                ('bio', models.TextField(blank=True, help_text="User's biography.")),
                ('country', models.CharField(blank=True, db_index=True, help_text="User's country.", max_length=100)),
                ('state', models.CharField(blank=True, help_text="User's state or province.", max_length=100)),
                ('city', models.CharField(blank=True, help_text="User's city.", max_length=100)),
                ('address', models.CharField(blank=True, help_text="User's street address.", max_length=255)),
                ('role', models.CharField(choices=[('vendor', 'Vendor'), ('client', 'Client'), ('staff', 'Staff'), ('admin', 'Admin'), ('editor', 'Editor'), ('support', 'Support'), ('assistant', 'Assistant')], db_index=True, default='client', help_text='RBAC Role. Cannot be changed after creation.', max_length=20)),
                ('auth_provider', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('google', 'Google')], default='email', help_text='Authentication provider used at signup.', max_length=20)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='True if email/phone OTP is verified.')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='True if user account is active.')),
                ('member_id', models.CharField(blank=True, db_index=True, editable=False, help_text='Unique human-readable brand ID (e.g. FASTAR000062). Auto-generated on user creation. Cannot be changed.', max_length=12, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='unified_user_set', related_query_name='unified_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='unified_user_set', related_query_name='unified_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Unified User',
                'verbose_name_plural': 'Unified Users',
                'ordering': ['-date_joined'],
            },
            bases=(models.Model, apps.common.models.HardDeleteMixin),
        ),
        migrations.CreateModel(
            name='BiometricCredential',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('credential_id', models.BinaryField(help_text='The Credential ID generated by the authenticator.', unique=True)),
                ('public_key', models.BinaryField(help_text='The Public Key for signature verification.')),
                ('sign_count', models.IntegerField(default=0, help_text='Counter to prevent replay attacks.')),
                ('device_name', models.CharField(blank=True, help_text="User-friendly name (e.g., 'MacBook TouchID').", max_length=255, null=True)),
                ('user', models.ForeignKey(help_text='The user this credential belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='biometric_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Credential',
                'verbose_name_plural': 'Biometric Credentials',
            },
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['email'], name='uu_email_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['phone'], name='uu_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['role'], name='uu_role_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['is_verified'], name='uu_is_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['is_active'], name='uu_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['auth_provider'], name='uu_auth_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['country'], name='uu_country_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['email', 'role'], name='uu_email_role_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['phone', 'role'], name='uu_phone_role_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['auth_provider', 'is_verified'], name='uu_provider_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['role', 'is_active'], name='uu_role_active_idx'),
        ),
    ]
