# Generated by Django 6.0.3 on 2026-04-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='fingerprint_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash derived from IP and User-Agent for coarse device fingerprinting without storing only raw identifiers.', max_length=128),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_seen_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Most recent IP address observed for this session.', null=True, unpack_ipv4=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_seen_user_agent',
            field=models.TextField(blank=True, help_text='Most recent User-Agent observed for this session.'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='refresh_token_family',
            field=models.CharField(blank=True, db_index=True, help_text='Stable family identifier for rotated refresh tokens when available. Falls back to the refresh token JTI for legacy tokens.', max_length=255),
        ),
        migrations.AddField(
            model_name='usersession',
            name='revoked_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the session was explicitly revoked.', null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='revoked_reason',
            field=models.CharField(blank=True, help_text='Operator-facing reason for revoking the session.', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='browser_family',
            field=models.CharField(blank=True, help_text='Chrome, Firefox, Safari, and other browser families.', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device_name',
            field=models.CharField(blank=True, help_text="Human-readable label such as 'Chrome on Windows'.", max_length=200),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the refresh token expires.', null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address captured at session creation time.', null=True, unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Frontend-only convenience flag. The API computes this at serializer time and does not rely on the stored database value.'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated when the session is refreshed or otherwise reused.'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='os_family',
            field=models.CharField(blank=True, help_text='Windows, macOS, iOS, Android, Linux, and similar platforms.', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Raw login-time User-Agent string.'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['revoked_at'], name='us_revoked_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['refresh_token_family'], name='us_family_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['fingerprint_hash'], name='us_fprint_idx'),
        ),
    ]
