# Generated by Django 6.0.3 on 2026-03-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifieduser',
            name='avatar',
            field=models.URLField(blank=True, help_text='Cloudinary HTTPS secure_url for user avatar. Set via the /api/v2/upload/presign/ → direct upload → webhook flow. Paste a Cloudinary URL directly in the admin if needed.', max_length=500, null=True),
        ),
    ]
