# Generated by Django 6.0.3 on 2026-03-17 12:43

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_avatar_imagefield_to_urlfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifieduser',
            name='avatar',
            field=models.URLField(blank=True, help_text='Cloudinary HTTPS secure_url for user avatar. Set via the /api/v1/upload/presign/ → direct upload → webhook flow. Paste a Cloudinary URL directly in the admin if needed.', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('jti', models.CharField(db_index=True, help_text='JWT ID (jti claim) of the refresh token for this session. Used to match and blacklist via SimpleJWT.', max_length=255, unique=True)),
                ('client_type', models.CharField(choices=[('web', 'Web Browser'), ('mobile', 'Mobile App'), ('api', 'API Client'), ('unknown', 'Unknown')], default='unknown', help_text='Browser / mobile app / API client.', max_length=20)),
                ('browser_family', models.CharField(blank=True, help_text='Chrome, Firefox, Safari, etc.', max_length=100)),
                ('os_family', models.CharField(blank=True, help_text='Windows, macOS, iOS, Android, Linux, etc.', max_length=100)),
                ('device_name', models.CharField(blank=True, help_text="Human-readable label for the session, e.g. 'Chrome on Windows', 'iPhone 15 Pro Max', 'cURL Script'.", max_length=200)),
                ('user_agent', models.TextField(blank=True, help_text='Raw User-Agent string for the session.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address at session creation (login time).', null=True, unpack_ipv4=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Updated on every token refresh. Stale sessions = last_used_at old.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the refresh token expires (from JWT payload).', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='True for the session that corresponds to the JWT making the current request. Computed at serializer time, not stored.')),
                ('user', models.ForeignKey(help_text='The owner of this session.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Client IP address (supports IPv4 and IPv6).', unpack_ipv4=True)),
                ('user_agent', models.TextField(blank=True, help_text='Raw HTTP User-Agent string.')),
                ('client_type', models.CharField(choices=[('web', 'Web Browser'), ('mobile', 'Mobile App'), ('api', 'API Client'), ('curl', 'cURL / Script'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Derived from User-Agent: web / mobile / api / curl.', max_length=20)),
                ('browser_family', models.CharField(blank=True, help_text='Browser family: Chrome, Firefox, Safari, Unknown, etc.', max_length=100)),
                ('os_family', models.CharField(blank=True, help_text='Operating system: Windows, macOS, iOS, Android, Linux, etc.', max_length=100)),
                ('device_type', models.CharField(blank=True, help_text='Device category: desktop, mobile, tablet, bot, etc.', max_length=50)),
                ('country', models.CharField(blank=True, db_index=True, help_text='Country name derived from IP (via MaxMind / ipapi).', max_length=100)),
                ('country_code', models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 country code (e.g. 'NG', 'US').", max_length=3)),
                ('region', models.CharField(blank=True, help_text="State / region / province (e.g. 'Lagos', 'California').", max_length=100)),
                ('city', models.CharField(blank=True, help_text="City name (e.g. 'Lagos', 'San Francisco').", max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Approx. latitude from IP geo-lookup.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Approx. longitude from IP geo-lookup.', max_digits=9, null=True)),
                ('auth_method', models.CharField(choices=[('email', 'Email + Password'), ('phone', 'Phone + Password'), ('google', 'Google OAuth'), ('biometric', 'Biometric / FIDO2')], default='email', help_text='Authentication method used for this attempt.', max_length=20)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('suspicious', 'Suspicious')], db_index=True, default='failed', help_text='Result of the login attempt.', max_length=20)),
                ('failure_reason', models.CharField(blank=True, help_text="Short machine-readable failure code: 'invalid_credentials', 'account_inactive', 'account_deleted', 'rate_limited', 'mfa_required', etc.", max_length=100)),
                ('is_successful', models.BooleanField(db_index=True, default=False, help_text='True iff the login attempt succeeded and tokens were issued.')),
                ('risk_score', models.SmallIntegerField(default=0, help_text='Risk score 0-100. Computed by Celery after the request: new country (+30), new device (+20), Tor exit node (+50), high-velocity (+40), etc. ≥70 triggers a security alert.')),
                ('is_new_device', models.BooleanField(default=False, help_text='True if this is the first time this device fingerprint was seen.')),
                ('is_new_country', models.BooleanField(default=False, help_text='True if the login country is new for this user.')),
                ('is_tor_exit_node', models.BooleanField(default=False, help_text='True if the IP is a known Tor exit node.')),
                ('user', models.ForeignKey(blank=True, help_text='NULL when a login attempt targets an unknown identifier (failed user-enumeration attempt).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='The session created by this successful login (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to='authentication.usersession')),
            ],
            options={
                'verbose_name': 'Login Event',
                'verbose_name_plural': 'Login Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-last_used_at'], name='us_user_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['jti'], name='us_jti_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='us_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['user', '-created_at'], name='le_user_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['ip_address', '-created_at'], name='le_ip_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['outcome', '-created_at'], name='le_outcome_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['country', '-created_at'], name='le_country_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['is_successful'], name='le_success_idx'),
        ),
    ]
