# Generated by Django 6.0.3 on 2026-05-11 03:54

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usersession_fingerprint_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometriccredential',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False),
        ),
    ]
