# Generated by Django 6.0.2 on 2026-02-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_biometriccredential_unifieduser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unifieduser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Unified User', 'verbose_name_plural': 'Unified Users'},
        ),
        migrations.RenameIndex(
            model_name='unifieduser',
            new_name='uu_email_role_idx',
            old_name='authenticat_email_19147e_idx',
        ),
        migrations.RenameIndex(
            model_name='unifieduser',
            new_name='uu_phone_role_idx',
            old_name='authenticat_phone_532574_idx',
        ),
        migrations.RenameIndex(
            model_name='unifieduser',
            new_name='uu_provider_verified_idx',
            old_name='authenticat_auth_pr_c6d242_idx',
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='address',
            field=models.CharField(blank=True, help_text="User's street address.", max_length=255),
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('google', 'Google')], default='email', help_text='Authentication provider used at signup.', max_length=20),
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='True if user account is active.'),
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='pid',
            field=models.CharField(blank=True, help_text='Legacy unique identifier for backward compatibility.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('client', 'Client'), ('staff', 'Staff'), ('admin', 'Admin'), ('editor', 'Editor'), ('support', 'Support'), ('assistant', 'Assistant')], db_index=True, default='client', help_text='RBAC Role. Cannot be changed after creation.', max_length=20),
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='state',
            field=models.CharField(blank=True, help_text="User's state or province.", max_length=100),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['email'], name='uu_email_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['phone'], name='uu_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['role'], name='uu_role_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['is_verified'], name='uu_is_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['is_active'], name='uu_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['auth_provider'], name='uu_auth_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['country'], name='uu_country_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['role', 'is_active'], name='uu_role_active_idx'),
        ),
    ]
