# Generated by Django 6.0.3 on 2026-06-05 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_biometriccredential_id_alter_loginevent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifieduser',
            name='data_retention_policy',
            field=models.CharField(blank=True, default='standard', help_text="'standard' (7yr) | 'minimal' (GDPR erasure requested) | 'legal_hold'.", max_length=20),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='is_processing_restricted',
            field=models.BooleanField(default=False, help_text='GDPR Article 18 — processing restriction flag.'),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='last_login_device',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='Explicit marketing communications consent.'),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='marketing_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='objected_processing_purposes',
            field=models.JSONField(default=list, help_text='GDPR Article 21 — list of opted-out processing purposes.'),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='preferred_language',
            field=models.CharField(blank=True, default='en', help_text="IETF language tag, e.g. 'en', 'yo', 'ha', 'ig'.", max_length=10),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='processing_restriction_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='User who referred this account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='risk_score',
            field=models.FloatField(default=0.0, help_text='0.0 (safe) – 1.0 (high risk). Updated on each login.'),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='timezone',
            field=models.CharField(blank=True, default='Africa/Lagos', help_text="IANA timezone string, e.g. 'Africa/Lagos'.", max_length=50),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='two_factor_backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='two_factor_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
