# Generated by Django 6.0.2 on 2026-02-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_unifieduser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifieduser',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='last name'),
        ),
    ]
