# Generated by Django 6.0.3 on 2026-06-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_phase12_unified_user_2026_scale_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifieduser',
            name='objected_processing_purposes',
            field=models.JSONField(blank=True, default=list, help_text='GDPR Article 21 — list of opted-out processing purposes.'),
        ),
    ]
