# Generated by Django 6.0.3 on 2026-04-05 23:32

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_client_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='default_shipping_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='favourite_colours',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='preferred_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='style_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.'),
        ),
    ]
