# Generated by Django 6.0.3 on 2026-04-13 01:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_clientprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short personal bio (max 500 chars).', max_length=500),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='default_shipping_address',
            field=models.TextField(blank=True, default='', help_text='Default shipping address for checkout.'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='favourite_colours',
            field=models.JSONField(blank=True, default=list, help_text='Favourite colour hex codes or names.'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='True once size, address, and style preferences are filled in.'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='preferred_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='', help_text='Preferred clothing size.', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='style_preferences',
            field=models.JSONField(blank=True, default=list, help_text='Style tags: ["casual", "afrocentric", "formal"]. Used by AI engine.'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='risk_score',
            field=models.SmallIntegerField(default=0, help_text='Risk score 0-100. ≥70 triggers a security alert.'),
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='User avatar image stored on Cloudinary. Upload via Django Admin file picker OR via the presign → direct-upload → webhook flow. In API responses, use str(avatar) to get the full Cloudinary URL.', max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('client', 'Client'), ('staff', 'Staff'), ('admin', 'Admin'), ('editor', 'Editor'), ('support', 'Support'), ('assistant', 'Assistant'), ('moderator', 'Moderator')], db_index=True, default='client', help_text='RBAC Role. Cannot be changed after creation.', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device_name',
            field=models.CharField(blank=True, help_text="Human-readable label, e.g. 'Chrome on Windows', 'iPhone 15 Pro Max'.", max_length=200),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Raw User-Agent string.'),
        ),
    ]
