# Generated by Django 6.0.3 on 2026-06-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_unifieduser_objected_processing_purposes'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometriccredential',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='loginevent',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
