# Generated by Django 6.0.3 on 2026-04-13 07:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0006_cloudinaryfield_avatar_moderator_role_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifieduser',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Cloudinary image public_id. Set via the /api/v1/upload/presign/ → direct upload → webhook flow. Use .url in serializers to retrieve the full HTTPS secure_url. In admin: use the file picker widget to upload directly to Cloudinary.', max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('client', 'Client'), ('staff', 'Staff'), ('admin', 'Admin'), ('editor', 'Editor'), ('support', 'Support'), ('assistant', 'Assistant'), ('moderator', 'Moderator'), ('super_admin', 'Super Admin'), ('super_vendor', 'Super Vendor'), ('super_client', 'Super Client'), ('super_staff', 'Super Staff'), ('super_editor', 'Super Editor'), ('super_support', 'Super Support'), ('super_assistant', 'Super Assistant'), ('super_moderator', 'Super Moderator')], db_index=True, default='client', help_text='RBAC Role. Cannot be changed after creation.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['is_verified', 'is_active'], name='uu_is_verified_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['is_staff'], name='uu_is_staff_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['member_id'], name='uu_member_id_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['country', 'is_active'], name='uu_country_is_active_idx'),
        ),
    ]
