# Generated by Django 6.0.2 on 2026-02-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_memberidcounter_rename_pid_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberidcounter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='member_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique human-readable brand ID (e.g. FASTAR000062). Auto-generated on user creation. Cannot be changed.', max_length=12, null=True, unique=True),
        ),
    ]
