# apps/ai/models/product_embedding.py
"""
ProductEmbedding — Stores marqo-FashionSigLIP vector embeddings for products.

Architecture:
  - One row per product (OneToOne with product.Product)
  - Separate model to keep Product model clean and focused
  - pgvector HNSW index for <50ms cosine similarity search
  - Updated by Celery embed_product task on every product save

pgvector installation:
  CREATE EXTENSION IF NOT EXISTS vector;
  (Handled by migration below)

HNSW index parameters:
  m=16, ef_construction=64 — Balanced accuracy/build-time trade-off
  For 100k+ products: increase m=32, ef_construction=128
"""

from __future__ import annotations

from django.db import models
from django.utils.translation import gettext_lazy as _
import pgvector.django

from apps.common.models import TimeStampedModel

VECTOR_DIM = 512  # marqo-FashionSigLIP output dimension


class ProductEmbedding(TimeStampedModel):
    """
    Fashion embedding vectors for a product, generated by marqo-FashionSigLIP.

    Three vector types:
      image_vector:    Visual embedding from product's primary image
      text_vector:     Semantic embedding from title + description
      combined_vector: Weighted average (60% image + 40% text) — used for search

    Query pattern:
        # Find products similar to a user's measurement query
        ProductEmbedding.objects.order_by(
            CosineDistance("combined_vector", query_vector)
        )[:20]

    Or via raw SQL with pgvector:
        SELECT product_id, 1 - (combined_vector <=> '[...]'::vector) AS similarity
        FROM ai_productembedding
        ORDER BY combined_vector <=> '[...]'::vector
        LIMIT 20;
    """

    product = models.OneToOneField(
        "product.Product",
        on_delete=models.CASCADE,
        related_name="embedding",
        verbose_name=_("Product"),
        db_index=True,
    )

    # ── Vector fields ─────────────────────────────────────────────────────────
    # Using JSONField as a portable fallback if pgvector extension isn't installed.
    # The Celery tasks use raw SQL for actual vector operations.
    # When pgvector is confirmed available, these can be swapped to VectorField.
    image_vector = pgvector.django.VectorField(
        dimensions=VECTOR_DIM,
        null=True,
        blank=True,
        verbose_name=_("Image Vector"),
        help_text=_(f"marqo-FashionSigLIP image embedding ({VECTOR_DIM}d). L2-normalized."),
    )
    text_vector = pgvector.django.VectorField(
        dimensions=VECTOR_DIM,
        null=True,
        blank=True,
        verbose_name=_("Text Vector"),
        help_text=_(f"marqo-FashionSigLIP text embedding ({VECTOR_DIM}d). L2-normalized."),
    )
    combined_vector = pgvector.django.VectorField(
        dimensions=VECTOR_DIM,
        null=True,
        blank=True,
        verbose_name=_("Combined Vector"),
        help_text=_(
            f"Weighted average: 60% image + 40% text ({VECTOR_DIM}d). "
            "Primary vector used for similarity search."
        ),
    )

    # ── Metadata ──────────────────────────────────────────────────────────────
    model_version = models.CharField(
        max_length=100,
        default="marqo-FashionSigLIP-B-16",
        verbose_name=_("Model Version"),
    )
    last_embedded_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_("Last Embedded At"),
    )
    embedding_status = models.CharField(
        max_length=20,
        choices=[
            ("pending",  _("Pending")),
            ("embedded", _("Embedded")),
            ("failed",   _("Failed")),
            ("skipped",  _("Skipped — No Image")),
        ],
        default="pending",
        db_index=True,
        verbose_name=_("Embedding Status"),
    )

    class Meta:
        verbose_name = _("Product Embedding")
        verbose_name_plural = _("Product Embeddings")
        ordering = ["-last_embedded_at"]
        indexes = [
            models.Index(fields=["embedding_status"], name="ai_pe_status_idx"),
        ]
        # HNSW indexes defined via migration using pgvector's CREATE INDEX USING hnsw
        # See: apps/ai/migrations/0002_add_pgvector_hnsw_indexes.py

    def __str__(self) -> str:
        has_img  = "✓img" if self.image_vector    else "✗img"
        has_text = "✓txt" if self.text_vector     else "✗txt"
        has_comb = "✓comb" if self.combined_vector else "✗comb"
        return f"Embedding [{has_img} {has_text} {has_comb}] — Product #{self.product_id}"
