# Generated by Django 6.0.3 on 2026-05-05 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_fix_cartitem_related_name_to_items'),
        ('product', '0004_anonymous_product_wishlist'),
        ('vendor', '0002_fix_cartitem_related_name_to_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productwishlist',
            name='uniq_session_product_wishlist',
        ),
        migrations.RenameField(
            model_name='productspecification',
            old_name='title',
            new_name='specification_title',
        ),
        migrations.RenameField(
            model_name='productspecification',
            old_name='content',
            new_name='specification_value',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_products', to='catalog.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='color_products', to='product.productcolor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='size_products', to='product.productsize'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category_products', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_products', to='product.producttag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor who owns this product. PROTECT prevents orphan listings.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_products', to='vendor.vendorprofile'),
        ),
        migrations.AlterField(
            model_name='productfaq',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_faqs', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productgallerymedia',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery_media', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_type',
            field=models.ForeignKey(blank=True, help_text='Taxonomy category this size belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sizes', to='product.productsizetype'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='product.product'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_product_tags', to='catalog.category'),
        ),
        migrations.AddConstraint(
            model_name='productwishlist',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False), ('user__isnull', True)), fields=('session_key', 'product'), name='uniq_session_product_wishlist'),
        ),
    ]
