# Generated by Django 6.0.3 on 2026-05-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_align_product_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.'),
        ),
    ]
