# Generated by Django 6.0.3 on 2026-05-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_coupon_id_alter_deliverycourier_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cash_payment_mode',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('cod', 'Cash On Delivery'), ('pay_at_shop', 'Pay At Shop'), ('both', 'Both')], default='disabled', help_text='Checkout gate for COD / Pay At Shop availability on this product.', max_length=20),
        ),
    ]
