# Generated by Django 6.0.3 on 2026-06-03 18:28

import apps.common.models.soft_delete
import django.db.models.deletion
import uuid
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_cash_payment_mode'),
        ('vendor', '0005_add_vendor_bank_account_and_kyc_legal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDraftSession',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUID7 — globally unique, time-ordered primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('draft_key', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(help_text='Partial JSON data of the product builder')),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('committed', 'Committed'), ('discarded', 'Discarded'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('linked_product', models.ForeignKey(blank=True, help_text='Populated once the draft is committed to a final Product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_sessions', to='product.product')),
                ('vendor', models.ForeignKey(help_text='Vendor who owns this draft.', on_delete=django.db.models.deletion.CASCADE, related_name='draft_sessions', to='vendor.vendorprofile')),
            ],
            options={
                'verbose_name': 'Product Draft Session',
                'verbose_name_plural': 'Product Draft Sessions',
                'ordering': ['-updated_at'],
            },
            bases=(apps.common.models.soft_delete.HardDeleteMixin, models.Model),
        ),
    ]
