# Generated by Django 6.0.3 on 2026-06-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_ai_sustainability_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
