# Generated by Django 6.0.3 on 2026-06-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_shipping_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=2500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productshippingprofile',
            name='preferred_couriers',
            field=models.ManyToManyField(blank=True, default='DHL,FedEx', help_text='Couriers the vendor prefers for this product.', related_name='preferred_for_custom_shipping_products', to='product.deliverycourier'),
        ),
        migrations.DeleteModel(
            name='ProductCertification',
        ),
    ]
