# Generated by Django 6.0.3 on 2026-04-23 21:39

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_blocked', 'Login Blocked'), ('logout', 'Logout'), ('token_refreshed', 'Token Refreshed'), ('google_login', 'Google OAuth Login'), ('register_success', 'Registration Success'), ('register_failed', 'Registration Failed'), ('account_created', 'Account Created'), ('account_updated', 'Account Updated'), ('account_soft_deleted', 'Account Soft-Deleted'), ('account_restored', 'Account Restored'), ('account_hard_deleted', 'Account Permanently Deleted'), ('email_verified', 'Email Verified'), ('phone_verified', 'Phone Verified'), ('avatar_uploaded', 'Avatar Uploaded'), ('avatar_cloudinary', 'Avatar Cloudinary Webhook'), ('password_changed', 'Password Changed'), ('password_reset_request', 'Password Reset Requested'), ('password_reset_done', 'Password Reset Completed'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('suspicious_activity', 'Suspicious Activity'), ('ip_blocked', 'IP Blocked'), ('failed_logins_exceeded', 'Failed Login Limit Exceeded'), ('admin_action', 'Admin Action'), ('admin_bulk_export', 'Admin Bulk Export'), ('admin_bulk_import', 'Admin Bulk Import'), ('admin_bulk_delete', 'Admin Bulk Delete'), ('settings_changed', 'Settings Changed'), ('data_viewed', 'Data Viewed'), ('data_exported', 'Data Exported'), ('sensitive_data_access', 'Sensitive Data Accessed'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_cancelled', 'Order Cancelled'), ('order_fulfilled', 'Order Fulfilled'), ('order_returned', 'Order Returned'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved'), ('cart_updated', 'Cart Updated'), ('checkout_started', 'Checkout Started'), ('checkout_completed', 'Checkout Completed'), ('checkout_abandoned', 'Checkout Abandoned'), ('measurement_created', 'Measurement Created'), ('measurement_updated', 'Measurement Updated'), ('measurement_deleted', 'Measurement Deleted'), ('ai_analysis_started', 'AI Analysis Started'), ('ai_analysis_completed', 'AI Analysis Completed'), ('ai_analysis_failed', 'AI Analysis Failed'), ('system_error', 'System Error'), ('api_call', 'API Call'), ('webhook_received', 'Webhook Received'), ('celery_task_failed', 'Celery Task Failed')], db_index=True, help_text='Type of business event.', max_length=60)),
                ('event_category', models.CharField(choices=[('authentication', 'Authentication'), ('authorization', 'Authorization'), ('account', 'Account Management'), ('profile', 'Profile'), ('security', 'Security'), ('admin', 'Admin Action'), ('data_access', 'Data Access'), ('data_modification', 'Data Modification'), ('system', 'System'), ('notification', 'Notification'), ('compliance', 'Compliance'), ('order', 'Order'), ('payment', 'Payment'), ('cart', 'Cart & Checkout'), ('measurement', 'AI Measurement')], db_index=True, help_text='Event category / domain.', max_length=60)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', help_text='Severity level of the event.', max_length=20)),
                ('action', models.TextField(help_text='Human-readable description of what happened.')),
                ('actor_email', models.EmailField(blank=True, db_index=True, help_text='Email snapshot at event time — preserved even if the user is deleted.', max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='Client IP address.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Full User-Agent string.', null=True)),
                ('device_type', models.CharField(blank=True, help_text='desktop / mobile / tablet / api / unknown', max_length=30, null=True)),
                ('browser_family', models.CharField(blank=True, help_text='Browser family (Chrome, Firefox, Safari, …)', max_length=80, null=True)),
                ('os_family', models.CharField(blank=True, help_text='OS family (Windows, macOS, Android, iOS, …)', max_length=80, null=True)),
                ('country', models.CharField(blank=True, db_index=True, help_text='GeoIP country or request origin (if resolved).', max_length=100, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, help_text='Unique request / trace ID for cross-service correlation.', max_length=64, null=True)),
                ('resource_type', models.CharField(blank=True, db_index=True, help_text="Model class name of the affected resource (e.g. 'UnifiedUser').", max_length=100, null=True)),
                ('resource_id', models.CharField(blank=True, db_index=True, help_text='PK of the affected resource.', max_length=255, null=True)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, PUT, PATCH, DELETE).', max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, help_text='Request URL path.', max_length=500, null=True)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, help_text='HTTP response status code.', null=True)),
                ('duration_ms', models.FloatField(blank=True, help_text='Handler execution time in milliseconds.', null=True)),
                ('old_values', models.JSONField(blank=True, help_text='Before-state snapshot (sanitised — no raw passwords).', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='After-state snapshot.', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Extra contextual data (arbitrary key-value).', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if event represents a failure.', null=True)),
                ('is_compliance', models.BooleanField(db_index=True, default=False, help_text='Flag events that must be retained for compliance audit.')),
                ('retention_days', models.PositiveIntegerField(default=2555, help_text='Days to retain this log entry.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this event was recorded. Immutable.')),
            ],
            options={
                'verbose_name': 'Audit Event Log',
                'verbose_name_plural': 'Audit Event Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
