# Generated by Django 6.0.3 on 2026-03-19 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial_audit_event_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditeventlog',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique request / trace ID for cross-service correlation.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='country',
            field=models.CharField(blank=True, db_index=True, help_text='GeoIP country or request origin (if resolved).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditeventlog',
            name='event_category',
            field=models.CharField(choices=[('authentication', 'Authentication'), ('authorization', 'Authorization'), ('account', 'Account Management'), ('profile', 'Profile'), ('security', 'Security'), ('admin', 'Admin Action'), ('data_access', 'Data Access'), ('data_modification', 'Data Modification'), ('system', 'System'), ('notification', 'Notification'), ('compliance', 'Compliance'), ('order', 'Order'), ('payment', 'Payment'), ('cart', 'Cart & Checkout'), ('measurement', 'AI Measurement')], db_index=True, help_text='Event category / domain.', max_length=60),
        ),
        migrations.AlterField(
            model_name='auditeventlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_blocked', 'Login Blocked'), ('logout', 'Logout'), ('token_refreshed', 'Token Refreshed'), ('google_login', 'Google OAuth Login'), ('register_success', 'Registration Success'), ('register_failed', 'Registration Failed'), ('account_created', 'Account Created'), ('account_updated', 'Account Updated'), ('account_soft_deleted', 'Account Soft-Deleted'), ('account_restored', 'Account Restored'), ('account_hard_deleted', 'Account Permanently Deleted'), ('email_verified', 'Email Verified'), ('phone_verified', 'Phone Verified'), ('avatar_uploaded', 'Avatar Uploaded'), ('avatar_cloudinary', 'Avatar Cloudinary Webhook'), ('password_changed', 'Password Changed'), ('password_reset_request', 'Password Reset Requested'), ('password_reset_done', 'Password Reset Completed'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('suspicious_activity', 'Suspicious Activity'), ('ip_blocked', 'IP Blocked'), ('failed_logins_exceeded', 'Failed Login Limit Exceeded'), ('admin_action', 'Admin Action'), ('admin_bulk_export', 'Admin Bulk Export'), ('admin_bulk_import', 'Admin Bulk Import'), ('admin_bulk_delete', 'Admin Bulk Delete'), ('settings_changed', 'Settings Changed'), ('data_viewed', 'Data Viewed'), ('data_exported', 'Data Exported'), ('sensitive_data_access', 'Sensitive Data Accessed'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_cancelled', 'Order Cancelled'), ('order_fulfilled', 'Order Fulfilled'), ('order_returned', 'Order Returned'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved'), ('cart_updated', 'Cart Updated'), ('checkout_started', 'Checkout Started'), ('checkout_completed', 'Checkout Completed'), ('checkout_abandoned', 'Checkout Abandoned'), ('measurement_created', 'Measurement Created'), ('measurement_updated', 'Measurement Updated'), ('measurement_deleted', 'Measurement Deleted'), ('ai_analysis_started', 'AI Analysis Started'), ('ai_analysis_completed', 'AI Analysis Completed'), ('ai_analysis_failed', 'AI Analysis Failed'), ('system_error', 'System Error'), ('api_call', 'API Call'), ('webhook_received', 'Webhook Received'), ('celery_task_failed', 'Celery Task Failed')], db_index=True, help_text='Type of business event.', max_length=60),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['correlation_id'], name='idx_ael_corr'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['country', '-created_at'], name='idx_ael_country'),
        ),
    ]
