# Generated by Django 6.0.3 on 2026-04-23 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditeventlog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who triggered this event. Null for unauthenticated/system events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['-created_at'], name='idx_ael_created'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['actor', '-created_at'], name='idx_ael_actor'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['event_type', '-created_at'], name='idx_ael_etype'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['event_category', '-created_at'], name='idx_ael_ecat'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['severity', '-created_at'], name='idx_ael_sev'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['ip_address', '-created_at'], name='idx_ael_ip'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='idx_ael_resource'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['is_compliance', '-created_at'], name='idx_ael_compliance'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['actor_email', '-created_at'], name='idx_ael_email'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['correlation_id'], name='idx_ael_corr'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['country', '-created_at'], name='idx_ael_country'),
        ),
    ]
