# Generated by Django 6.0.3 on 2026-05-10 02:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditeventlog',
            name='actor_role',
            field=models.CharField(blank=True, db_index=True, help_text='Role/type snapshot of actor at event time (client, vendor, admin, system).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='city',
            field=models.CharField(blank=True, help_text='GeoIP resolved city.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, help_text="ISO 3166-1 alpha-2 country code (e.g. 'NG', 'GB', 'US').", max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='JWT jti or session key — enables grouping all events in one session.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='auditeventlog',
            name='event_category',
            field=models.CharField(choices=[('authentication', 'Authentication'), ('authorization', 'Authorization'), ('account', 'Account Management'), ('profile', 'Profile'), ('security', 'Security'), ('admin', 'Admin Action'), ('data_access', 'Data Access'), ('data_modification', 'Data Modification'), ('system', 'System'), ('notification', 'Notification'), ('compliance', 'Compliance'), ('order', 'Order'), ('payment', 'Payment'), ('cart', 'Cart & Checkout'), ('measurement', 'AI Measurement'), ('wallet', 'Wallet & Ledger'), ('kyc', 'KYC & Identity'), ('vendor', 'Vendor'), ('catalog', 'Catalog & Products'), ('support', 'Customer Support'), ('chat', 'Chat & Messaging'), ('transactions', 'Transactions & Ledger'), ('provider', 'Payment Providers'), ('client', 'Client / Consumer'), ('settings', 'Platform Settings')], db_index=True, help_text='Event category / domain.', max_length=60),
        ),
        migrations.AlterField(
            model_name='auditeventlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_blocked', 'Login Blocked'), ('logout', 'Logout'), ('token_refreshed', 'Token Refreshed'), ('google_login', 'Google OAuth Login'), ('register_success', 'Registration Success'), ('register_failed', 'Registration Failed'), ('account_created', 'Account Created'), ('account_updated', 'Account Updated'), ('account_soft_deleted', 'Account Soft-Deleted'), ('account_restored', 'Account Restored'), ('account_hard_deleted', 'Account Permanently Deleted'), ('email_verified', 'Email Verified'), ('phone_verified', 'Phone Verified'), ('avatar_uploaded', 'Avatar Uploaded'), ('avatar_cloudinary', 'Avatar Cloudinary Webhook'), ('password_changed', 'Password Changed'), ('password_reset_request', 'Password Reset Requested'), ('password_reset_done', 'Password Reset Completed'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('suspicious_activity', 'Suspicious Activity'), ('ip_blocked', 'IP Blocked'), ('failed_logins_exceeded', 'Failed Login Limit Exceeded'), ('admin_action', 'Admin Action'), ('admin_bulk_export', 'Admin Bulk Export'), ('admin_bulk_import', 'Admin Bulk Import'), ('admin_bulk_delete', 'Admin Bulk Delete'), ('settings_changed', 'Settings Changed'), ('data_viewed', 'Data Viewed'), ('data_exported', 'Data Exported'), ('sensitive_data_access', 'Sensitive Data Accessed'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_cancelled', 'Order Cancelled'), ('order_fulfilled', 'Order Fulfilled'), ('order_returned', 'Order Returned'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved'), ('cart_updated', 'Cart Updated'), ('cart_item_added', 'Cart Item Added'), ('cart_item_removed', 'Cart Item Removed'), ('checkout_initiated', 'Checkout Initiated'), ('checkout_started', 'Checkout Started'), ('checkout_completed', 'Checkout Completed'), ('checkout_abandoned', 'Checkout Abandoned'), ('coupon_applied', 'Coupon Applied'), ('measurement_created', 'Measurement Created'), ('measurement_updated', 'Measurement Updated'), ('measurement_deleted', 'Measurement Deleted'), ('ai_analysis_started', 'AI Analysis Started'), ('ai_analysis_completed', 'AI Analysis Completed'), ('ai_analysis_failed', 'AI Analysis Failed'), ('wallet_topup', 'Wallet Top-Up'), ('wallet_withdrawal', 'Wallet Withdrawal'), ('wallet_escrow_hold', 'Escrow Hold'), ('wallet_escrow_release', 'Escrow Released'), ('wallet_created', 'Wallet Created'), ('kyc_submitted', 'KYC Submitted'), ('kyc_verified', 'KYC Verified'), ('kyc_rejected', 'KYC Rejected'), ('kyc_webhook', 'KYC Webhook Received'), ('kyc_retry', 'KYC Retry'), ('bvn_verified', 'BVN Verified'), ('nin_verified', 'NIN Verified'), ('vendor_registered', 'Vendor Registered'), ('vendor_kyc_gate_passed', 'Vendor KYC Gate Passed'), ('vendor_commission_changed', 'Vendor Commission Changed'), ('vendor_suspended', 'Vendor Suspended'), ('vendor_restored', 'Vendor Restored'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('product_published', 'Product Published'), ('product_unpublished', 'Product Unpublished'), ('review_created', 'Review Created'), ('review_posted', 'Review Posted'), ('review_flagged', 'Review Flagged'), ('cloudinary_webhook', 'Cloudinary Webhook'), ('ticket_created', 'Support Ticket Created'), ('ticket_escalated', 'Support Ticket Escalated'), ('ticket_resolved', 'Support Ticket Resolved'), ('ticket_closed', 'Support Ticket Closed'), ('sla_breach', 'SLA Breach'), ('chat_started', 'Chat Conversation Started'), ('chat_message_flagged', 'Chat Message Flagged'), ('conversation_started', 'Conversation Started'), ('message_sent', 'Message Sent'), ('message_deleted', 'Message Deleted'), ('websocket_connected', 'WebSocket Connected'), ('websocket_disconnected', 'WebSocket Disconnected'), ('ledger_entry_created', 'Ledger Entry Created'), ('commission_calculated', 'Commission Calculated'), ('payout_initiated', 'Payout Initiated'), ('payout_success', 'Payout Success'), ('payout_failed', 'Payout Failed'), ('transaction_created', 'Transaction Created'), ('provider_config_changed', 'Provider Config Changed'), ('provider_webhook_received', 'Provider Webhook Received'), ('provider_webhook_failed', 'Provider Webhook Failed'), ('provider_health_check', 'Provider Health Check'), ('provider_switched', 'Provider Switched'), ('circuit_breaker_opened', 'Circuit Breaker Opened'), ('circuit_breaker_closed', 'Circuit Breaker Closed'), ('client_registered', 'Client Registered'), ('client_address_added', 'Client Address Added'), ('client_measurement_linked', 'Measurement Linked'), ('notification_sent', 'Notification Sent'), ('notification_failed', 'Notification Delivery Failed'), ('settings_updated', 'Platform Settings Updated'), ('feature_flag_changed', 'Feature Flag Changed'), ('system_error', 'System Error'), ('api_call', 'API Call'), ('webhook_received', 'Webhook Received'), ('celery_task_failed', 'Celery Task Failed')], db_index=True, help_text='Type of business event.', max_length=60),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['country_code', '-created_at'], name='idx_ael_country_code'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['actor_role', '-created_at'], name='idx_ael_actor_role'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['session_id'], name='idx_ael_session'),
        ),
    ]
