# Generated by Django 6.0.3 on 2026-05-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0004_alter_auditeventlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditeventlog',
            name='client_device_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stable UUID v4 generated by the browser frontend. Persisted in localStorage so the same device ID appears across sessions. Enables cross-session device correlation — e.g. detecting an account accessed from a new device. Source: X-Device-ID request header.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='client_geo_accuracy_m',
            field=models.FloatField(blank=True, help_text='GPS position accuracy in metres. < 50m indicates high-accuracy mobile GPS. > 5000m indicates IP-based approximation or WiFi triangulation. Use accuracy to qualify any geographic assertions made from this data. Source: X-Client-Geo-Accuracy request header.', null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='client_geo_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text="GPS latitude from the browser Geolocation API. Only populated when the user has EXPLICITLY granted geolocation permission. Never populated without user consent — the frontend only sends this header after confirming permission state === 'granted'. Source: X-Client-Geo-Lat request header.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='client_geo_lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude from the browser Geolocation API. See client_geo_lat for consent and accuracy notes. Source: X-Client-Geo-Lng request header.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='client_locale',
            field=models.CharField(blank=True, help_text="Browser language/locale (e.g. 'en-NG', 'en-US', 'yo-NG'). Used for locale-specific fraud pattern detection and user experience analytics. Source: X-Client-Locale request header → navigator.language.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='client_platform',
            field=models.CharField(blank=True, help_text="OS platform as reported by the browser (e.g. 'Win32', 'MacIntel', 'Linux armv8l'). Modern browsers use navigator.userAgentData.platform; legacy browsers fall back to navigator.platform. Enriches the server-parsed os_family field. Source: X-Client-Platform request header.", max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='client_timezone',
            field=models.CharField(blank=True, help_text="IANA timezone identifier from the client browser (e.g. 'Africa/Lagos', 'Europe/London'). More accurate than IP-based timezone inference, especially when the user is on a VPN or behind a NAT. Source: X-Client-Timezone request header → Intl.DateTimeFormat().", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditeventlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_blocked', 'Login Blocked'), ('logout', 'Logout'), ('token_refreshed', 'Token Refreshed'), ('google_login', 'Google OAuth Login'), ('register_success', 'Registration Success'), ('register_failed', 'Registration Failed'), ('user_registered', 'User Registered'), ('registration_failed', 'Registration Failed (Hook)'), ('account_verified', 'Account Verified (OTP + Auto-Login)'), ('account_created', 'Account Created'), ('account_updated', 'Account Updated'), ('account_soft_deleted', 'Account Soft-Deleted'), ('account_restored', 'Account Restored'), ('account_hard_deleted', 'Account Permanently Deleted'), ('email_verified', 'Email Verified'), ('phone_verified', 'Phone Verified'), ('avatar_uploaded', 'Avatar Uploaded'), ('avatar_cloudinary', 'Avatar Cloudinary Webhook'), ('password_changed', 'Password Changed'), ('password_reset_request', 'Password Reset Requested'), ('password_reset_done', 'Password Reset Completed'), ('password_reset_failed', 'Password Reset Failed'), ('mfa_enabled', 'MFA Enabled'), ('mfa_DISABLED', 'MFA Disabled'), ('otp_generated', 'OTP Generated'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Verification Failed'), ('biometric_registered', 'Biometric Device Registered'), ('biometric_auth_success', 'Biometric Authentication Success'), ('biometric_auth_failed', 'Biometric Authentication Failed'), ('suspicious_activity', 'Suspicious Activity'), ('ip_blocked', 'IP Blocked'), ('failed_logins_exceeded', 'Failed Login Limit Exceeded'), ('session_revoked', 'Single Session Revoked'), ('session_revoke_all', 'All Other Sessions Revoked'), ('admin_action', 'Admin Action'), ('admin_bulk_export', 'Admin Bulk Export'), ('admin_bulk_import', 'Admin Bulk Import'), ('admin_bulk_delete', 'Admin Bulk Delete'), ('settings_changed', 'Settings Changed'), ('data_viewed', 'Data Viewed'), ('data_exported', 'Data Exported'), ('sensitive_data_access', 'Sensitive Data Accessed'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_cancelled', 'Order Cancelled'), ('order_fulfilled', 'Order Fulfilled'), ('order_returned', 'Order Returned'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved'), ('cart_updated', 'Cart Updated'), ('cart_item_added', 'Cart Item Added'), ('cart_item_removed', 'Cart Item Removed'), ('checkout_initiated', 'Checkout Initiated'), ('checkout_started', 'Checkout Started'), ('checkout_completed', 'Checkout Completed'), ('checkout_abandoned', 'Checkout Abandoned'), ('coupon_applied', 'Coupon Applied'), ('measurement_created', 'Measurement Created'), ('measurement_updated', 'Measurement Updated'), ('measurement_deleted', 'Measurement Deleted'), ('ai_analysis_started', 'AI Analysis Started'), ('ai_analysis_completed', 'AI Analysis Completed'), ('ai_analysis_failed', 'AI Analysis Failed'), ('wallet_topup', 'Wallet Top-Up'), ('wallet_withdrawal', 'Wallet Withdrawal'), ('wallet_withdrawal_requested', 'Wallet Withdrawal Requested'), ('wallet_escrow_hold', 'Escrow Hold'), ('wallet_escrow_release', 'Escrow Released'), ('wallet_escrow_refunded', 'Escrow Refunded'), ('wallet_created', 'Wallet Created'), ('wallet_pin_set', 'Wallet PIN Set'), ('wallet_pin_changed', 'Wallet PIN Changed'), ('wallet_transfer', 'Wallet Transfer'), ('kyc_submitted', 'KYC Submitted'), ('kyc_verified', 'KYC Verified'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('kyc_document_uploaded', 'KYC Document Uploaded'), ('kyc_webhook', 'KYC Webhook Received'), ('kyc_retry', 'KYC Retry'), ('bvn_verified', 'BVN Verified'), ('nin_verified', 'NIN Verified'), ('vendor_registered', 'Vendor Registered'), ('vendor_provisioned', 'Vendor Provisioned'), ('vendor_profile_updated', 'Vendor Profile Updated'), ('vendor_kyc_gate_passed', 'Vendor KYC Gate Passed'), ('vendor_commission_changed', 'Vendor Commission Changed'), ('vendor_suspended', 'Vendor Suspended'), ('vendor_restored', 'Vendor Restored'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('product_published', 'Product Published'), ('product_unpublished', 'Product Unpublished'), ('review_created', 'Review Created'), ('review_posted', 'Review Posted'), ('review_flagged', 'Review Flagged'), ('cloudinary_webhook', 'Cloudinary Webhook'), ('collection_created', 'Collection Created'), ('collection_updated', 'Collection Updated'), ('collection_deleted', 'Collection Deleted'), ('brand_created', 'Brand Created'), ('brand_updated', 'Brand Updated'), ('brand_deleted', 'Brand Deleted'), ('category_created', 'Category Created'), ('category_updated', 'Category Updated'), ('category_deleted', 'Category Deleted'), ('blog_post_created', 'Blog Post Created'), ('blog_post_updated', 'Blog Post Updated'), ('blog_post_deleted', 'Blog Post Deleted'), ('ticket_created', 'Support Ticket Created'), ('ticket_escalated', 'Support Ticket Escalated'), ('ticket_resolved', 'Support Ticket Resolved'), ('ticket_closed', 'Support Ticket Closed'), ('sla_breach', 'SLA Breach'), ('chat_started', 'Chat Conversation Started'), ('chat_message_flagged', 'Chat Message Flagged'), ('conversation_started', 'Conversation Started'), ('message_sent', 'Message Sent'), ('message_deleted', 'Message Deleted'), ('websocket_connected', 'WebSocket Connected'), ('websocket_disconnected', 'WebSocket Disconnected'), ('ledger_entry_created', 'Ledger Entry Created'), ('commission_calculated', 'Commission Calculated'), ('payout_initiated', 'Payout Initiated'), ('payout_success', 'Payout Success'), ('payout_failed', 'Payout Failed'), ('transaction_created', 'Transaction Created'), ('provider_config_changed', 'Provider Config Changed'), ('provider_webhook_received', 'Provider Webhook Received'), ('provider_webhook_failed', 'Provider Webhook Failed'), ('provider_health_check', 'Provider Health Check'), ('provider_switched', 'Provider Switched'), ('circuit_breaker_opened', 'Circuit Breaker Opened'), ('circuit_breaker_closed', 'Circuit Breaker Closed'), ('client_registered', 'Client Registered'), ('client_address_added', 'Client Address Added'), ('client_measurement_linked', 'Measurement Linked'), ('notification_sent', 'Notification Sent'), ('notification_failed', 'Notification Delivery Failed'), ('settings_updated', 'Platform Settings Updated'), ('feature_flag_changed', 'Feature Flag Changed'), ('system_error', 'System Error'), ('api_call', 'API Call'), ('webhook_received', 'Webhook Received'), ('celery_task_failed', 'Celery Task Failed')], db_index=True, help_text='Type of business event.', max_length=60),
        ),
    ]
