# Generated by Django 6.0.3 on 2026-05-30 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0005_wave_b3_client_context_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditeventlog',
            name='api_version',
            field=models.CharField(blank=True, db_index=True, help_text="API version extracted from the request path (e.g. 'v1', 'v2'). Enables per-version security and performance analysis. Auto-extracted from request_path by AuditContextMiddleware.", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='data_subject_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the GDPR/NDPR data subject (typically UnifiedUser.pk). Denormalised here so it survives a hard-delete of the UnifiedUser row. Used to fulfil GDPR Art. 15 Subject Access Requests (SARs) and Art. 17 Right-to-Erasure queries without a live FK join. Populated automatically from actor.pk when is_compliance=True.', null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='geo_city',
            field=models.CharField(blank=True, help_text="City from GeoIP enrichment (e.g. 'Lagos', 'London'). Dedicated Phase 9 field for new compliance queries without mixing old and new GeoIP provider results.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='geo_country_code',
            field=models.CharField(blank=True, db_index=True, help_text="ISO 3166-1 alpha-2 country code from GeoIP enrichment (e.g. 'NG', 'GB', 'US'). Strictly 2-char for PCI-DSS compliant geographic segmentation. Distinct from country_code which may vary in length across GeoIP providers.", max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='legal_hold',
            field=models.BooleanField(db_index=True, default=False, help_text='When True, this row is under legal hold and MUST NOT be deleted by any automated cleanup task, management command, or Celery beat job. Set by a superuser via Django admin when a row is subject to regulatory investigation, litigation, or CBN/SEC audit freeze. PCI-DSS v4 Req. 10.5: audit log records must be protected from modification.'),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='request_size_bytes',
            field=models.PositiveIntegerField(blank=True, help_text='Size of the incoming HTTP request body in bytes. Used for anomaly detection — unusually large requests may indicate data exfiltration attempts or malformed payload attacks.', null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='response_size_bytes',
            field=models.PositiveIntegerField(blank=True, help_text='Size of the outgoing HTTP response body in bytes. Used for bandwidth auditing and detecting abnormally large data exports (potential GDPR data breach indicator).', null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='session_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 fingerprint computed from the device+browser signature (User-Agent + Accept-Language + screen resolution + timezone). Enables cross-session device correlation for fraud detection without storing raw PII device identifiers. Populated by the frontend audit-headers builder via X-Session-Fingerprint header.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Reserved for future multi-tenant expansion. When Fashionistar moves to a multi-tenant architecture, this field partitions audit rows by tenant without requiring a DB schema split. Currently null for all rows.', null=True),
        ),
        migrations.AddField(
            model_name='auditeventlog',
            name='tls_version',
            field=models.CharField(blank=True, help_text="TLS version negotiated for this request (e.g. 'TLSv1.3', 'TLSv1.2'). PCI-DSS v4 Req. 10.3 mandates logging transport security details. Populated from the 'SSL_PROTOCOL' server variable via Nginx/Gunicorn.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='auditeventlog',
            name='retention_days',
            field=models.PositiveIntegerField(default=2555, help_text='Days to retain this log entry. -1 = infinite.'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['data_subject_id', '-created_at'], name='idx_ael_data_subject'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['legal_hold', '-created_at'], name='idx_ael_legal_hold'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['tenant_id', '-created_at'], name='idx_ael_tenant'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['session_fingerprint', '-created_at'], name='idx_ael_sess_fp'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['api_version', 'actor_email'], name='idx_ael_api_actor'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['actor', '-created_at'], name='idx_ael_actor_time'),
        ),
    ]
