# Generated by Django 6.0.3 on 2026-04-28 16:07

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('product_title_snapshot', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('blocked', 'Blocked'), ('escalated', 'Escalated (Admin Review)')], db_index=True, default='active', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unread_buyer_count', models.PositiveIntegerField(default=0)),
                ('unread_vendor_count', models.PositiveIntegerField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversations', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('offer', 'Price Offer'), ('system', 'System Notification'), ('delivery_confirm', 'Delivery Confirmation')], default='text', max_length=20)),
                ('body', models.TextField(blank=True)),
                ('is_read_by_buyer', models.BooleanField(default=False)),
                ('is_read_by_vendor', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatOffer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('product_title_snapshot', models.CharField(max_length=512)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Buyer Response'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled by Vendor')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='chat.conversation')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='chat.message')),
            ],
            options={
                'db_table': 'chat_offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cloudinary_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='chat_media')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='chat.message')),
            ],
            options={
                'db_table': 'chat_message_media',
            },
        ),
        migrations.CreateModel(
            name='ModerationFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment / Threats'), ('fraud', 'Fraud Attempt'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='chat.conversation')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_flags', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_moderation_flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatEscalation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_escalations', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation', to='chat.conversation')),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation', to='chat.moderationflag')),
            ],
            options={
                'db_table': 'chat_escalations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['buyer', 'status'], name='chat_conver_buyer_i_99e0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['vendor', 'status'], name='chat_conver_vendor__6ec899_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_0a903c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['author', 'is_read_by_buyer'], name='chat_messag_author__84f081_idx'),
        ),
    ]
