# Generated by Django 6.0.3 on 2026-06-05 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_buyer_vendor_set_null'),
        ('measurements', '0004_measurementsharetoken_measurementaccesslog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='measurement_share_token',
            field=models.ForeignKey(blank=True, help_text='Set when a client shares measurements in chat. Grants the vendor scoped, revocable access to measurement fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='measurements.measurementsharetoken'),
        ),
    ]
